#!/usr/bin/env python3
"""tests/generated/endpoints.rs 자동 생성기.

각 default_api 엔드포인트에 대해 wiremock 기반 라우팅 회귀 테스트를 생성한다.
4xx 응답을 매핑하고 `.expect(1)` 로 (a) 올바른 HTTP 메서드/경로로 라우팅되는지,
(b) 에러가 표면으로 전파되는지 검증한다. OpenAPI 갱신으로 경로가 바뀌면 즉시 실패한다.
"""
import glob
import os
import re
import subprocess

DEFAULT_API_PATH = "src/adapter/generated_api/default_api.rs"
MODELS_GLOB = "src/domain/models/*.rs"
OUT_PATH = "tests/generated/endpoints.rs"

with open(DEFAULT_API_PATH) as f:
    content = f.read()

# --- Default 보유 타입 집합 구성 (인자 기본값 생성용) ---
default_types = set()
for mf in glob.glob(MODELS_GLOB):
    with open(mf) as fh:
        mc = fh.read()
    has_default = bool(re.search(r"#\[derive\([^\)]*Default", mc))
    for m in re.finditer(r"pub (?:struct|enum) (\w+)", mc):
        if has_default:
            default_types.add(m.group(1))


def default_arg(typ):
    """인자 타입 → 기본값 리터럴. 생성 불가면 None (엔드포인트 skip 신호)."""
    t = typ.strip()
    if t.startswith("Option<"):
        return "None"
    if t == "&str":
        return '"test"'
    if t in ("i64", "i32", "u64", "u32", "f64", "f32", "usize", "isize"):
        return "0"
    if t == "bool":
        return "false"
    if t == "serde_json::Value":
        return "serde_json::Value::Null"
    if t.startswith("models::"):
        tn = t.split("::", 1)[1]
        if tn in default_types:
            return f"{t}::default()"
        return None
    if t in default_types:
        return f"{t}::default()"
    return None


def render_path_regex(template):
    """URI format 템플릿을 wiremock path 정규식으로 렌더.
    `{}/payments/{paymentId}` → `^/payments/[^/]+$` (첫 {} 는 base_path).
    변수 세그먼트는 `[^/]+` 로 와일드카드 처리하여, path param이 enum/모델 타입일 때
    Default 직렬화값이 달라도 라우팅 구조(세그먼트 수, 고정 부분)를 검증한다.
    """
    parts = template.split("{}", 1)
    rest = parts[1] if len(parts) > 1 else template
    rest = re.sub(r"\{[^}]*\}", "[^/]+", rest)
    return "^" + rest + "$"


def parse_args(args):
    """멀티라인 args → [(name, type), ...]."""
    out = []
    for arg in args.split(","):
        arg = arg.strip()
        if not arg or ":" not in arg:
            continue
        name, typ = arg.split(":", 1)
        out.append((name.strip(), typ.strip()))
    return out


# --- 함수별 시그니처 + URI + HTTP 메서드 추출 ---
sig_pat = (
    r"pub async fn (\w+)\(\s*configuration: &configuration::Configuration,?\s*(.*?)\s*\)"
    r"\s*->\s*Result\s*<\s*(.*?)\s*,\s*Error\s*<\s*(.*?)\s*>\s*,?\s*>"
)

endpoints = []
skipped = []
unextracted = []
for m in re.finditer(sig_pat, content, re.DOTALL):
    fn_name = m.group(1)
    args = parse_args(m.group(2))
    # 함수 본문 앞쪽에서 URI 템플릿과 HTTP 메서드 추출
    body = content[m.end(): m.end() + 3000]
    uri_m = re.search(r'let uri_str = format!\(\s*"([^"]+)"', body)
    method_m = re.search(r"reqwest::Method::([A-Z]+)", body)
    if not uri_m or not method_m:
        unextracted.append(fn_name)
        continue
    uri_template = uri_m.group(1)
    http_method = method_m.group(1)
    path = render_path_regex(uri_template)

    # 인자 기본값 생성; 하나라도 불가면 엔드포인트 skip
    arg_lits = []
    skip_reason = None
    for name, typ in args:
        lit = default_arg(typ)
        if lit is None:
            skip_reason = f"{name}: {typ}"
            break
        arg_lits.append(lit)
    if skip_reason:
        skipped.append((fn_name, skip_reason))
        continue
    endpoints.append((fn_name, http_method, path, arg_lits))

# --- 회귀 게이트 ---
total_async_fns = len(re.findall(r"pub async fn (\w+)\b", content))
covered = len(endpoints) + len(skipped) + len(unextracted)
assert covered == total_async_fns, (
    f"REGRESSION GATE FAILED: covered {covered} != {total_async_fns} async fns "
    f"({len(unextracted)} unextracted, {len(skipped)} skipped, {len(endpoints)} generated)"
)

# --- 테스트 파일 생성 ---
os.makedirs("tests/generated", exist_ok=True)
lines = [
    "//! AUTO-GENERATED by generate_tests.py — DO NOT EDIT.",
    "//! 각 default_api 엔드포인트의 라우팅(경로/메서드)과 4xx 에러 처리를 회귀 검증합니다.",
    "//! OpenAPI 갱신으로 엔드포인트 경로/메서드가 바뀌면 즉시 실패합니다.",
    "#![allow(clippy::all)]",
    "use portone_rs::v2::adapter::generated_api::{configuration::Configuration, default_api};",
    "use portone_rs::v2::domain::models;",
    "use serde_json::json;",
    "use wiremock::matchers::{method, path_regex};",
    "use wiremock::{Mock, MockServer, ResponseTemplate};",
    "",
]
for fn_name, http_method, p, arg_lits in endpoints:
    args_str = ", ".join(arg_lits)
    if args_str:
        args_str = ", " + args_str
    lines.append("#[tokio::test]")
    lines.append(f"async fn {fn_name}_routes_and_errors_on_4xx() {{")
    lines.append("    let __server = MockServer::start().await;")
    lines.append("    Mock::given(method(\"%s\"))" % http_method)
    lines.append("        .and(path_regex(\"%s\"))" % p)
    lines.append(
        "        .respond_with(ResponseTemplate::new(404).set_body_json("
        'json!({"type":"NOT_FOUND","message":"test"})))'
    )
    lines.append("        .expect(1)")
    lines.append("        .mount(&__server)")
    lines.append("        .await;")
    lines.append("    let mut __cfg = Configuration::new();")
    lines.append("    __cfg.base_path = __server.uri();")
    lines.append(
        "    let __result = default_api::%s(&__cfg%s).await;" % (fn_name, args_str)
    )
    lines.append(
        '        assert!(__result.is_err(), "%s should surface an error on 4xx");' % fn_name
    )
    lines.append("}")
    lines.append("")

with open(OUT_PATH, "w") as f:
    f.write("\n".join(lines))

print(
    f"Generated {len(endpoints)} endpoint tests "
    f"({len(skipped)} skipped for non-Default args, {len(unextracted)} unextracted) "
    f"out of {total_async_fns} async fns."
)
for name, reason in skipped:
    print(f"  skipped: {name} ({reason})")

# 생성 직후 포맷을 적용하여 커밋된 파일과 항상 일치(멱등)하도록 한다.
subprocess.run(["cargo", "fmt"], check=True)
