/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// Address : 분리 형식 주소  oneLine(한 줄 형식 주소) 필드는 항상 존재합니다.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Address {
    #[serde(rename = "ONE_LINE")]
    OneLine(Box<models::OneLineAddress>),
    #[serde(rename = "SEPARATED")]
    Separated(Box<models::SeparatedAddress>),
}

impl Default for Address {
    fn default() -> Self {
        Self::OneLine(Default::default())
    }
}
