/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// AlreadyPaidOrWaitingError : 결제가 이미 완료되었거나 대기중인 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlreadyPaidOrWaitingError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl AlreadyPaidOrWaitingError {
    /// 결제가 이미 완료되었거나 대기중인 경우
    pub fn new(r#type: String) -> AlreadyPaidOrWaitingError {
        AlreadyPaidOrWaitingError {
            r#type,
            message: None,
        }
    }
}
