/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ApplyEscrowLogisticsResponse : 에스크로 배송 정보 등록 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyEscrowLogisticsResponse {
    #[serde(rename = "invoiceNumber")]
    pub invoice_number: String,
    #[serde(rename = "sentAt")]
    pub sent_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "appliedAt")]
    pub applied_at: chrono::DateTime<chrono::FixedOffset>,
}

impl ApplyEscrowLogisticsResponse {
    /// 에스크로 배송 정보 등록 성공 응답
    pub fn new(
        invoice_number: String,
        sent_at: chrono::DateTime<chrono::FixedOffset>,
        applied_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> ApplyEscrowLogisticsResponse {
        ApplyEscrowLogisticsResponse {
            invoice_number,
            sent_at,
            applied_at,
        }
    }
}
