/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// AttachB2bTaxInvoiceFileBody : 세금계산서 파일 첨부 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachB2bTaxInvoiceFileBody {
    #[serde(rename = "fileId")]
    pub file_id: String,
}

impl AttachB2bTaxInvoiceFileBody {
    /// 세금계산서 파일 첨부 정보
    pub fn new(file_id: String) -> AttachB2bTaxInvoiceFileBody {
        AttachB2bTaxInvoiceFileBody { file_id }
    }
}
