/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceModificationCreateBody : 수정 세금계산서 생성 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bTaxInvoiceModificationCreateBody {
    #[serde(rename = "type")]
    pub r#type: models::B2bTaxInvoiceModificationType,
    /// taxInvoiceKeyType이 TAX_INVOICE_ID가 아닌 경우 필수 값입니다.
    #[serde(rename = "brn", skip_serializing_if = "Option::is_none")]
    pub brn: Option<String>,
    #[serde(rename = "taxInvoiceKey")]
    pub tax_invoice_key: String,
    #[serde(rename = "taxInvoiceKeyType", skip_serializing_if = "Option::is_none")]
    pub tax_invoice_key_type: Option<models::B2bTaxInvoiceKeyType>,
}

impl B2bTaxInvoiceModificationCreateBody {
    /// 수정 세금계산서 생성 입력 정보
    pub fn new(
        r#type: models::B2bTaxInvoiceModificationType,
        tax_invoice_key: String,
    ) -> B2bTaxInvoiceModificationCreateBody {
        B2bTaxInvoiceModificationCreateBody {
            r#type,
            brn: None,
            tax_invoice_key,
            tax_invoice_key_type: None,
        }
    }
}
