/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bCounterpartySelfOriginBrnMismatchError : 자사 사업자등록번호와 동일한 거래처를 생성할 수 없는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartySelfOriginBrnMismatchError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bCounterpartySelfOriginBrnMismatchError {
    /// 자사 사업자등록번호와 동일한 거래처를 생성할 수 없는 경우
    pub fn new(r#type: String) -> B2bCounterpartySelfOriginBrnMismatchError {
        B2bCounterpartySelfOriginBrnMismatchError {
            r#type,
            message: None,
        }
    }
}
