/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bBulkTaxInvoiceSourceType : 그룹 생성 방식
/// 그룹 생성 방식
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum B2bBulkTaxInvoiceSourceType {
    #[serde(rename = "SHEET")]
    #[default]
    Sheet,
    #[serde(rename = "PLATFORM")]
    Platform,
}

impl std::fmt::Display for B2bBulkTaxInvoiceSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sheet => write!(f, "SHEET"),
            Self::Platform => write!(f, "PLATFORM"),
        }
    }
}
