/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceSortInput : 세금계산서 다건 조회 시 정렬 조건
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bTaxInvoiceSortInput {
    #[serde(rename = "by", skip_serializing_if = "Option::is_none")]
    pub by: Option<models::B2bTaxInvoiceSortBy>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<models::SortOrder>,
}

impl B2bTaxInvoiceSortInput {
    /// 세금계산서 다건 조회 시 정렬 조건
    pub fn new() -> B2bTaxInvoiceSortInput {
        B2bTaxInvoiceSortInput {
            by: None,
            order: None,
        }
    }
}
