/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceSummary : 세금계산서 요약
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bTaxInvoiceSummary {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "taxationType")]
    pub taxation_type: models::B2bTaxInvoiceTaxationType,
    #[serde(rename = "documentModificationType")]
    pub document_modification_type: models::B2bTaxInvoiceDocumentModificationType,
    #[serde(rename = "isDelayed", skip_serializing_if = "Option::is_none")]
    pub is_delayed: Option<bool>,
    #[serde(rename = "issuanceType")]
    pub issuance_type: models::B2bTaxInvoiceIssuanceType,
    #[serde(rename = "bulkTaxInvoiceId", skip_serializing_if = "Option::is_none")]
    pub bulk_tax_invoice_id: Option<String>,
    #[serde(rename = "payoutId", skip_serializing_if = "Option::is_none")]
    pub payout_id: Option<String>,
    #[serde(rename = "totalSupplyAmount")]
    pub total_supply_amount: i64,
    #[serde(rename = "totalTaxAmount")]
    pub total_tax_amount: i64,
    #[serde(rename = "totalAmount")]
    pub total_amount: i64,
    #[serde(rename = "purposeType")]
    pub purpose_type: models::B2bTaxInvoicePurposeType,
    #[serde(rename = "supplierBrn")]
    pub supplier_brn: String,
    #[serde(rename = "supplierName")]
    pub supplier_name: String,
    #[serde(rename = "supplierRepresentativeName")]
    pub supplier_representative_name: String,
    #[serde(
        rename = "supplierDocumentKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub supplier_document_key: Option<String>,
    #[serde(
        rename = "supplierCounterpartyId",
        skip_serializing_if = "Option::is_none"
    )]
    pub supplier_counterparty_id: Option<String>,
    #[serde(rename = "recipientBrn")]
    pub recipient_brn: String,
    #[serde(rename = "recipientName")]
    pub recipient_name: String,
    #[serde(rename = "recipientRepresentativeName")]
    pub recipient_representative_name: String,
    #[serde(
        rename = "recipientDocumentKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_document_key: Option<String>,
    #[serde(
        rename = "recipientCounterpartyId",
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_counterparty_id: Option<String>,
    #[serde(
        rename = "recipientBusinessStatus",
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_business_status: Option<models::B2bCompanyStateBusinessStatus>,
    /// 상태가 CLOSED, SUSPENDED 상태인 경우에만 결과값 반환
    #[serde(
        rename = "recipientClosedSuspendedDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_closed_suspended_date: Option<chrono::NaiveDate>,
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "writeDate")]
    pub write_date: chrono::NaiveDate,
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "issuanceDueDate")]
    pub issuance_due_date: chrono::NaiveDate,
    #[serde(rename = "status")]
    pub status: models::B2bTaxInvoiceStatus,
    #[serde(rename = "draftedAt", skip_serializing_if = "Option::is_none")]
    pub drafted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "requestedAt", skip_serializing_if = "Option::is_none")]
    pub requested_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "issuedAt", skip_serializing_if = "Option::is_none")]
    pub issued_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "openedAt", skip_serializing_if = "Option::is_none")]
    pub opened_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "statusUpdatedAt")]
    pub status_updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "ntsSentAt", skip_serializing_if = "Option::is_none")]
    pub nts_sent_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// 세금계산서 발행(전자서명) 시점에 자동으로 부여
    #[serde(rename = "ntsApprovalNumber", skip_serializing_if = "Option::is_none")]
    pub nts_approval_number: Option<String>,
    #[serde(rename = "ntsResult", skip_serializing_if = "Option::is_none")]
    pub nts_result: Option<String>,
    #[serde(
        rename = "ntsResultReceivedAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub nts_result_received_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// 국세청 발급 결과 코드로 영문 3자리 + 숫자 3자리로 구성됨
    #[serde(rename = "ntsResultCode", skip_serializing_if = "Option::is_none")]
    pub nts_result_code: Option<String>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// 최대 99개
    #[serde(rename = "items")]
    pub items: Vec<models::B2bTaxInvoiceItem>,
}

impl B2bTaxInvoiceSummary {
    /// 세금계산서 요약
    pub fn new(
        id: String,
        taxation_type: models::B2bTaxInvoiceTaxationType,
        document_modification_type: models::B2bTaxInvoiceDocumentModificationType,
        issuance_type: models::B2bTaxInvoiceIssuanceType,
        total_supply_amount: i64,
        total_tax_amount: i64,
        total_amount: i64,
        purpose_type: models::B2bTaxInvoicePurposeType,
        supplier_brn: String,
        supplier_name: String,
        supplier_representative_name: String,
        recipient_brn: String,
        recipient_name: String,
        recipient_representative_name: String,
        write_date: chrono::NaiveDate,
        issuance_due_date: chrono::NaiveDate,
        status: models::B2bTaxInvoiceStatus,
        status_updated_at: chrono::DateTime<chrono::FixedOffset>,
        items: Vec<models::B2bTaxInvoiceItem>,
    ) -> B2bTaxInvoiceSummary {
        B2bTaxInvoiceSummary {
            id,
            taxation_type,
            document_modification_type,
            is_delayed: None,
            issuance_type,
            bulk_tax_invoice_id: None,
            payout_id: None,
            total_supply_amount,
            total_tax_amount,
            total_amount,
            purpose_type,
            supplier_brn,
            supplier_name,
            supplier_representative_name,
            supplier_document_key: None,
            supplier_counterparty_id: None,
            recipient_brn,
            recipient_name,
            recipient_representative_name,
            recipient_document_key: None,
            recipient_counterparty_id: None,
            recipient_business_status: None,
            recipient_closed_suspended_date: None,
            write_date,
            issuance_due_date,
            status,
            drafted_at: None,
            requested_at: None,
            issued_at: None,
            opened_at: None,
            status_updated_at,
            nts_sent_at: None,
            nts_approval_number: None,
            nts_result: None,
            nts_result_received_at: None,
            nts_result_code: None,
            memo: None,
            items,
        }
    }
}
