/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bExternalServiceError : 외부 서비스에서 에러가 발생한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bExternalServiceError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bExternalServiceError {
    /// 외부 서비스에서 에러가 발생한 경우
    pub fn new(r#type: String) -> B2bExternalServiceError {
        B2bExternalServiceError {
            r#type,
            message: None,
        }
    }
}
