/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// B2bCounterpartyFilter : 거래처 검색 필터
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartyFilter {
    /// prefix 검색
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "brn", skip_serializing_if = "Option::is_none")]
    pub brn: Option<String>,
    /// 포함 검색
    #[serde(rename = "companyName", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    #[serde(rename = "representativeName", skip_serializing_if = "Option::is_none")]
    pub representative_name: Option<String>,
    #[serde(rename = "contactName", skip_serializing_if = "Option::is_none")]
    pub contact_name: Option<String>,
    #[serde(rename = "contactPhone", skip_serializing_if = "Option::is_none")]
    pub contact_phone: Option<String>,
    #[serde(rename = "contactEmail", skip_serializing_if = "Option::is_none")]
    pub contact_email: Option<String>,
    #[serde(rename = "businessStatuses", skip_serializing_if = "Option::is_none")]
    pub business_statuses: Option<Vec<models::B2bCounterpartyBusinessStatus>>,
    #[serde(
        rename = "ntsConnectionStatuses",
        skip_serializing_if = "Option::is_none"
    )]
    pub nts_connection_statuses: Option<Vec<models::B2bNtsConnectionStatus>>,
    /// 특정 ID 목록으로 필터링
    #[serde(rename = "counterpartyIds", skip_serializing_if = "Option::is_none")]
    pub counterparty_ids: Option<Vec<String>>,
}

impl B2bCounterpartyFilter {
    /// 거래처 검색 필터
    pub fn new() -> B2bCounterpartyFilter {
        B2bCounterpartyFilter {
            id: None,
            brn: None,
            company_name: None,
            representative_name: None,
            contact_name: None,
            contact_phone: None,
            contact_email: None,
            business_statuses: None,
            nts_connection_statuses: None,
            counterparty_ids: None,
        }
    }
}
