/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// B2bCounterpartyInput : 거래처 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartyInput {
    /// `-` 없이 숫자로만 구성됩니다.
    #[serde(rename = "brn")]
    pub brn: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "representativeName", skip_serializing_if = "Option::is_none")]
    pub representative_name: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "businessType", skip_serializing_if = "Option::is_none")]
    pub business_type: Option<String>,
    #[serde(rename = "businessClass", skip_serializing_if = "Option::is_none")]
    pub business_class: Option<String>,
    #[serde(rename = "contact", skip_serializing_if = "Option::is_none")]
    pub contact: Option<Box<models::B2bCounterpartyContactInput>>,
    /// 최대 5명까지 등록할 수 있습니다.
    #[serde(rename = "additionalContacts", skip_serializing_if = "Option::is_none")]
    pub additional_contacts: Option<Vec<models::B2bCounterpartyContactInput>>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
}

impl B2bCounterpartyInput {
    /// 거래처 입력 정보
    pub fn new(brn: String) -> B2bCounterpartyInput {
        B2bCounterpartyInput {
            brn,
            name: None,
            representative_name: None,
            address: None,
            business_type: None,
            business_class: None,
            contact: None,
            additional_contacts: None,
            memo: None,
        }
    }
}
