/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceNonDeletableStatusError : 세금계산서가 삭제 가능한 상태가 아닌 경우  삭제 가능한 상태는 `DRAFTED`, `ISSUE_REFUSED`, `REQUEST_CANCELLED_BY_RECIPIENT`, `ISSUE_CANCELLED_BY_SUPPLIER`, `SENDING_FAILED` 입니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bTaxInvoiceNonDeletableStatusError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bTaxInvoiceNonDeletableStatusError {
    /// 세금계산서가 삭제 가능한 상태가 아닌 경우  삭제 가능한 상태는 `DRAFTED`, `ISSUE_REFUSED`, `REQUEST_CANCELLED_BY_RECIPIENT`, `ISSUE_CANCELLED_BY_SUPPLIER`, `SENDING_FAILED` 입니다.
    pub fn new(r#type: String) -> B2bTaxInvoiceNonDeletableStatusError {
        B2bTaxInvoiceNonDeletableStatusError {
            r#type,
            message: None,
        }
    }
}
