/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bCounterpartyVerificationBrnMismatchError : 검증 결과의 사업자등록번호가 일치하지 않는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartyVerificationBrnMismatchError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bCounterpartyVerificationBrnMismatchError {
    /// 검증 결과의 사업자등록번호가 일치하지 않는 경우
    pub fn new(r#type: String) -> B2bCounterpartyVerificationBrnMismatchError {
        B2bCounterpartyVerificationBrnMismatchError {
            r#type,
            message: None,
        }
    }
}
