/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bSearchDateType : 조회 기준
/// 조회 기준
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum B2bSearchDateType {
    #[serde(rename = "REGISTER")]
    #[default]
    Register,
    #[serde(rename = "WRITE")]
    Write,
    #[serde(rename = "ISSUE")]
    Issue,
}

impl std::fmt::Display for B2bSearchDateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Register => write!(f, "REGISTER"),
            Self::Write => write!(f, "WRITE"),
            Self::Issue => write!(f, "ISSUE"),
        }
    }
}
