/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bCounterpartyVerificationNotFoundError : 검증 결과를 찾을 수 없는 경우  사업자 정보 검증 결과를 찾을 수 없습니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartyVerificationNotFoundError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bCounterpartyVerificationNotFoundError {
    /// 검증 결과를 찾을 수 없는 경우  사업자 정보 검증 결과를 찾을 수 없습니다.
    pub fn new(r#type: String) -> B2bCounterpartyVerificationNotFoundError {
        B2bCounterpartyVerificationNotFoundError {
            r#type,
            message: None,
        }
    }
}
