/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceContact : 세금계산서 담당자
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bTaxInvoiceContact {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "mobilePhoneNumber", skip_serializing_if = "Option::is_none")]
    pub mobile_phone_number: Option<String>,
    #[serde(rename = "email")]
    pub email: String,
}

impl B2bTaxInvoiceContact {
    /// 세금계산서 담당자
    pub fn new(email: String) -> B2bTaxInvoiceContact {
        B2bTaxInvoiceContact {
            name: None,
            department: None,
            phone_number: None,
            mobile_phone_number: None,
            email,
        }
    }
}
