/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceTaxationType : 과세 유형
/// 과세 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum B2bTaxInvoiceTaxationType {
    #[serde(rename = "TAXABLE")]
    #[default]
    Taxable,
    #[serde(rename = "ZERO_RATED")]
    ZeroRated,
    #[serde(rename = "FREE")]
    Free,
}

impl std::fmt::Display for B2bTaxInvoiceTaxationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Taxable => write!(f, "TAXABLE"),
            Self::ZeroRated => write!(f, "ZERO_RATED"),
            Self::Free => write!(f, "FREE"),
        }
    }
}
