/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bBulkTaxInvoiceStat : 세금계산서 상태별 집계 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bBulkTaxInvoiceStat {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "amountSum")]
    pub amount_sum: i64,
}

impl B2bBulkTaxInvoiceStat {
    /// 세금계산서 상태별 집계 정보
    pub fn new(count: i32, amount_sum: i64) -> B2bBulkTaxInvoiceStat {
        B2bBulkTaxInvoiceStat { count, amount_sum }
    }
}
