/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceAdditionalContact : 추가 담당자
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bTaxInvoiceAdditionalContact {
    /// 최대 100자
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
}

impl B2bTaxInvoiceAdditionalContact {
    /// 추가 담당자
    pub fn new(email: String) -> B2bTaxInvoiceAdditionalContact {
        B2bTaxInvoiceAdditionalContact {
            name: None,
            email,
            phone_number: None,
        }
    }
}
