/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bCounterpartyBrnInvalidError : 사업자등록번호가 유효하지 않은 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartyBrnInvalidError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bCounterpartyBrnInvalidError {
    /// 사업자등록번호가 유효하지 않은 경우
    pub fn new(r#type: String) -> B2bCounterpartyBrnInvalidError {
        B2bCounterpartyBrnInvalidError {
            r#type,
            message: None,
        }
    }
}
