/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bModificationNotProvidedError : 세금계산서 수정 입력 정보를 찾을 수 없는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bModificationNotProvidedError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bModificationNotProvidedError {
    /// 세금계산서 수정 입력 정보를 찾을 수 없는 경우
    pub fn new(r#type: String) -> B2bModificationNotProvidedError {
        B2bModificationNotProvidedError {
            r#type,
            message: None,
        }
    }
}
