/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceKeyType : 세금계산서 식별자 유형
/// 세금계산서 식별자 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum B2bTaxInvoiceKeyType {
    #[serde(rename = "SUPPLIER")]
    #[default]
    Supplier,
    #[serde(rename = "RECIPIENT")]
    Recipient,
    #[serde(rename = "TAX_INVOICE_ID")]
    TaxInvoiceId,
}

impl std::fmt::Display for B2bTaxInvoiceKeyType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Supplier => write!(f, "SUPPLIER"),
            Self::Recipient => write!(f, "RECIPIENT"),
            Self::TaxInvoiceId => write!(f, "TAX_INVOICE_ID"),
        }
    }
}
