/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceIssuanceType : 발행 유형
/// 발행 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum B2bTaxInvoiceIssuanceType {
    #[serde(rename = "NORMAL")]
    #[default]
    Normal,
    #[serde(rename = "REVERSE")]
    Reverse,
}

impl std::fmt::Display for B2bTaxInvoiceIssuanceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal => write!(f, "NORMAL"),
            Self::Reverse => write!(f, "REVERSE"),
        }
    }
}
