/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceDocumentModificationType : 세금계산서 문서 수정 발행 유형
/// 세금계산서 문서 수정 발행 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum B2bTaxInvoiceDocumentModificationType {
    #[serde(rename = "NORMAL")]
    #[default]
    Normal,
    #[serde(rename = "MODIFICATION")]
    Modification,
}

impl std::fmt::Display for B2bTaxInvoiceDocumentModificationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal => write!(f, "NORMAL"),
            Self::Modification => write!(f, "MODIFICATION"),
        }
    }
}
