/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bTaxInvoiceModificationType : 수정 사유
/// 수정 사유
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum B2bTaxInvoiceModificationType {
    #[serde(rename = "CORRECTION_OF_ENTRY_ERRORS")]
    #[default]
    CorrectionOfEntryErrors,
    #[serde(rename = "CHANGE_IN_SUPPLY_COST")]
    ChangeInSupplyCost,
    #[serde(rename = "RETURN")]
    Return,
    #[serde(rename = "CANCELLATION_OF_CONTRACT")]
    CancellationOfContract,
    #[serde(rename = "DUPLICATE_ISSUANCE_DUE_TO_ERROR")]
    DuplicateIssuanceDueToError,
}

impl std::fmt::Display for B2bTaxInvoiceModificationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CorrectionOfEntryErrors => write!(f, "CORRECTION_OF_ENTRY_ERRORS"),
            Self::ChangeInSupplyCost => write!(f, "CHANGE_IN_SUPPLY_COST"),
            Self::Return => write!(f, "RETURN"),
            Self::CancellationOfContract => write!(f, "CANCELLATION_OF_CONTRACT"),
            Self::DuplicateIssuanceDueToError => write!(f, "DUPLICATE_ISSUANCE_DUE_TO_ERROR"),
        }
    }
}
