/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// B2bTaxInvoice : 세금계산서
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bTaxInvoice {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: models::B2bTaxInvoiceStatus,
    #[serde(rename = "taxationType")]
    pub taxation_type: models::B2bTaxInvoiceTaxationType,
    #[serde(rename = "documentModificationType")]
    pub document_modification_type: models::B2bTaxInvoiceDocumentModificationType,
    #[serde(rename = "isDelayed", skip_serializing_if = "Option::is_none")]
    pub is_delayed: Option<bool>,
    #[serde(rename = "issuanceType")]
    pub issuance_type: models::B2bTaxInvoiceIssuanceType,
    #[serde(rename = "bulkTaxInvoiceId", skip_serializing_if = "Option::is_none")]
    pub bulk_tax_invoice_id: Option<String>,
    #[serde(rename = "serialNumber", skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    /// 입력 범위(4자리) : 0 ~ 9999
    #[serde(rename = "bookVolume", skip_serializing_if = "Option::is_none")]
    pub book_volume: Option<i32>,
    /// 입력 범위(4자리) : 0 ~ 9999
    #[serde(rename = "bookIssue", skip_serializing_if = "Option::is_none")]
    pub book_issue: Option<i32>,
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "writeDate")]
    pub write_date: chrono::NaiveDate,
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "issuanceDueDate")]
    pub issuance_due_date: chrono::NaiveDate,
    #[serde(rename = "purposeType")]
    pub purpose_type: models::B2bTaxInvoicePurposeType,
    #[serde(rename = "totalSupplyAmount")]
    pub total_supply_amount: i64,
    #[serde(rename = "totalTaxAmount")]
    pub total_tax_amount: i64,
    #[serde(rename = "totalAmount")]
    pub total_amount: i64,
    #[serde(rename = "cashAmount", skip_serializing_if = "Option::is_none")]
    pub cash_amount: Option<i64>,
    #[serde(rename = "checkAmount", skip_serializing_if = "Option::is_none")]
    pub check_amount: Option<i64>,
    #[serde(rename = "creditAmount", skip_serializing_if = "Option::is_none")]
    pub credit_amount: Option<i64>,
    #[serde(rename = "noteAmount", skip_serializing_if = "Option::is_none")]
    pub note_amount: Option<i64>,
    /// 최대 3개
    #[serde(rename = "remarks")]
    pub remarks: Vec<String>,
    #[serde(
        rename = "supplierDocumentKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub supplier_document_key: Option<String>,
    #[serde(rename = "supplier")]
    pub supplier: Box<models::B2bTaxInvoiceCompany>,
    #[serde(
        rename = "recipientDocumentKey",
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_document_key: Option<String>,
    #[serde(rename = "recipient")]
    pub recipient: Box<models::B2bTaxInvoiceCompany>,
    #[serde(rename = "sendSms", skip_serializing_if = "Option::is_none")]
    pub send_sms: Option<bool>,
    #[serde(rename = "modification", skip_serializing_if = "Option::is_none")]
    pub modification: Option<Box<models::B2bTaxInvoiceModification>>,
    /// 최대 99개
    #[serde(rename = "items")]
    pub items: Vec<models::B2bTaxInvoiceItem>,
    /// 최대 5명
    #[serde(rename = "additionalContacts")]
    pub additional_contacts: Vec<models::B2bTaxInvoiceAdditionalContact>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "draftedAt", skip_serializing_if = "Option::is_none")]
    pub drafted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "requestedAt", skip_serializing_if = "Option::is_none")]
    pub requested_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "issuedAt", skip_serializing_if = "Option::is_none")]
    pub issued_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "statusUpdatedAt", skip_serializing_if = "Option::is_none")]
    pub status_updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "ntsSentAt", skip_serializing_if = "Option::is_none")]
    pub nts_sent_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// 세금계산서 발행(전자서명) 시점에 자동으로 부여
    #[serde(rename = "ntsApprovalNumber", skip_serializing_if = "Option::is_none")]
    pub nts_approval_number: Option<String>,
    #[serde(rename = "ntsResult", skip_serializing_if = "Option::is_none")]
    pub nts_result: Option<String>,
    /// 국세청 발급 결과 코드로 영문 3자리 + 숫자 3자리로 구성됨
    #[serde(rename = "ntsResultCode", skip_serializing_if = "Option::is_none")]
    pub nts_result_code: Option<String>,
    #[serde(
        rename = "ntsResultReceivedAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub nts_result_received_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "deletedAt", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl B2bTaxInvoice {
    /// 세금계산서
    pub fn new(
        id: String,
        status: models::B2bTaxInvoiceStatus,
        taxation_type: models::B2bTaxInvoiceTaxationType,
        document_modification_type: models::B2bTaxInvoiceDocumentModificationType,
        issuance_type: models::B2bTaxInvoiceIssuanceType,
        write_date: chrono::NaiveDate,
        issuance_due_date: chrono::NaiveDate,
        purpose_type: models::B2bTaxInvoicePurposeType,
        total_supply_amount: i64,
        total_tax_amount: i64,
        total_amount: i64,
        remarks: Vec<String>,
        supplier: models::B2bTaxInvoiceCompany,
        recipient: models::B2bTaxInvoiceCompany,
        items: Vec<models::B2bTaxInvoiceItem>,
        additional_contacts: Vec<models::B2bTaxInvoiceAdditionalContact>,
    ) -> B2bTaxInvoice {
        B2bTaxInvoice {
            id,
            status,
            taxation_type,
            document_modification_type,
            is_delayed: None,
            issuance_type,
            bulk_tax_invoice_id: None,
            serial_number: None,
            book_volume: None,
            book_issue: None,
            write_date,
            issuance_due_date,
            purpose_type,
            total_supply_amount,
            total_tax_amount,
            total_amount,
            cash_amount: None,
            check_amount: None,
            credit_amount: None,
            note_amount: None,
            remarks,
            supplier_document_key: None,
            supplier: Box::new(supplier),
            recipient_document_key: None,
            recipient: Box::new(recipient),
            send_sms: None,
            modification: None,
            items,
            additional_contacts,
            memo: None,
            drafted_at: None,
            requested_at: None,
            issued_at: None,
            status_updated_at: None,
            nts_sent_at: None,
            nts_approval_number: None,
            nts_result: None,
            nts_result_code: None,
            nts_result_received_at: None,
            deleted_at: None,
        }
    }
}
