/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bCounterpartyMissingRequiredFieldsError : 필수 입력 항목이 누락된 경우  거래처 생성/수정 시 필수 입력 항목이 누락되었습니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartyMissingRequiredFieldsError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bCounterpartyMissingRequiredFieldsError {
    /// 필수 입력 항목이 누락된 경우  거래처 생성/수정 시 필수 입력 항목이 누락되었습니다.
    pub fn new(r#type: String) -> B2bCounterpartyMissingRequiredFieldsError {
        B2bCounterpartyMissingRequiredFieldsError {
            r#type,
            message: None,
        }
    }
}
