/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bCompanyStateBusinessStatus : 영업 상태
/// 영업 상태
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum B2bCompanyStateBusinessStatus {
    #[serde(rename = "IN_BUSINESS")]
    #[default]
    InBusiness,
    #[serde(rename = "CLOSED")]
    Closed,
    #[serde(rename = "SUSPENDED")]
    Suspended,
}

impl std::fmt::Display for B2bCompanyStateBusinessStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InBusiness => write!(f, "IN_BUSINESS"),
            Self::Closed => write!(f, "CLOSED"),
            Self::Suspended => write!(f, "SUSPENDED"),
        }
    }
}
