/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bCounterpartyPartnerNotDeletableError : 파트너 연동 거래처는 삭제할 수 없는 경우  파트너와 연동된 거래처는 직접 삭제할 수 없습니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartyPartnerNotDeletableError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bCounterpartyPartnerNotDeletableError {
    /// 파트너 연동 거래처는 삭제할 수 없는 경우  파트너와 연동된 거래처는 직접 삭제할 수 없습니다.
    pub fn new(r#type: String) -> B2bCounterpartyPartnerNotDeletableError {
        B2bCounterpartyPartnerNotDeletableError {
            r#type,
            message: None,
        }
    }
}
