/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bCounterpartyBrnModificationNotAllowedError : 사업자등록번호 수정이 허용되지 않는 경우  거래처의 사업자등록번호는 수정할 수 없습니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartyBrnModificationNotAllowedError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bCounterpartyBrnModificationNotAllowedError {
    /// 사업자등록번호 수정이 허용되지 않는 경우  거래처의 사업자등록번호는 수정할 수 없습니다.
    pub fn new(r#type: String) -> B2bCounterpartyBrnModificationNotAllowedError {
        B2bCounterpartyBrnModificationNotAllowedError {
            r#type,
            message: None,
        }
    }
}
