/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// B2bCounterpartyTooManyAdditionalContactsError : 추가 담당자가 너무 많은 경우  추가 담당자는 최대 5명까지 등록할 수 있습니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2bCounterpartyTooManyAdditionalContactsError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl B2bCounterpartyTooManyAdditionalContactsError {
    /// 추가 담당자가 너무 많은 경우  추가 담당자는 최대 5명까지 등록할 수 있습니다.
    pub fn new(r#type: String) -> B2bCounterpartyTooManyAdditionalContactsError {
        B2bCounterpartyTooManyAdditionalContactsError {
            r#type,
            message: None,
        }
    }
}
