/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// BankInfo : 은행 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankInfo {
    #[serde(rename = "bank")]
    pub bank: models::Bank,
    #[serde(rename = "name")]
    pub name: Box<models::BankInfoName>,
}

impl BankInfo {
    /// 은행 정보
    pub fn new(bank: models::Bank, name: models::BankInfoName) -> BankInfo {
        BankInfo {
            bank,
            name: Box::new(name),
        }
    }
}
