/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// BankInfoName : 은행 명칭
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankInfoName {
    #[serde(rename = "ko")]
    pub ko: String,
}

impl BankInfoName {
    /// 은행 명칭
    pub fn new(ko: String) -> BankInfoName {
        BankInfoName { ko }
    }
}
