/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// BeforeRegisteredPaymentEscrow : 배송 정보 등록 전
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeforeRegisteredPaymentEscrow {
    #[serde(rename = "status")]
    pub status: String,
}

impl BeforeRegisteredPaymentEscrow {
    /// 배송 정보 등록 전
    pub fn new(status: String) -> BeforeRegisteredPaymentEscrow {
        BeforeRegisteredPaymentEscrow { status }
    }
}
