/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingKeyInfoSummary {
    #[serde(rename = "billingKey")]
    pub billing_key: String,
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<Box<Vec<models::SelectedChannel>>>,
    #[serde(rename = "issuedAt")]
    pub issued_at: chrono::DateTime<chrono::FixedOffset>,
}

impl BillingKeyInfoSummary {
    pub fn new(
        billing_key: String,
        issued_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> BillingKeyInfoSummary {
        BillingKeyInfoSummary {
            billing_key,
            channels: None,
            issued_at,
        }
    }
}
