/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// BillingKeyInfo : 빌링키 정보
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum BillingKeyInfo {
    #[serde(rename = "DELETED")]
    Deleted(Box<models::DeletedBillingKeyInfo>),
    #[serde(rename = "ISSUED")]
    Issued(Box<models::IssuedBillingKeyInfo>),
}

impl Default for BillingKeyInfo {
    fn default() -> Self {
        Self::Deleted(Default::default())
    }
}
