/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// BillingKeyNotFoundError : 빌링키가 존재하지 않는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingKeyNotFoundError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl BillingKeyNotFoundError {
    /// 빌링키가 존재하지 않는 경우
    pub fn new(r#type: String) -> BillingKeyNotFoundError {
        BillingKeyNotFoundError {
            r#type,
            message: None,
        }
    }
}
