/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// BillingKeyFailure : 발급 실패 상세 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingKeyFailure {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "pgCode", skip_serializing_if = "Option::is_none")]
    pub pg_code: Option<String>,
    #[serde(rename = "pgMessage", skip_serializing_if = "Option::is_none")]
    pub pg_message: Option<String>,
    #[serde(rename = "failedAt")]
    pub failed_at: chrono::DateTime<chrono::FixedOffset>,
}

impl BillingKeyFailure {
    /// 발급 실패 상세 정보
    pub fn new(failed_at: chrono::DateTime<chrono::FixedOffset>) -> BillingKeyFailure {
        BillingKeyFailure {
            message: None,
            pg_code: None,
            pg_message: None,
            failed_at,
        }
    }
}
