/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// BillingKeyFilterInput : 빌링키 다건 조회를 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingKeyFilterInput {
    /// Merchant 사용자만 사용가능하며, 지정되지 않은 경우 고객사 전체 빌링키를 조회합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    #[serde(rename = "timeRangeField", skip_serializing_if = "Option::is_none")]
    pub time_range_field: Option<models::BillingKeyTimeRangeField>,
    /// 값을 입력하지 않으면 end의 90일 전으로 설정됩니다.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// 값을 입력하지 않으면 현재 시점으로 설정됩니다.
    #[serde(rename = "until", skip_serializing_if = "Option::is_none")]
    pub until: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// 값을 입력하지 않으면 빌링키 상태 필터링이 적용되지 않습니다.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Vec<models::BillingKeyStatus>>,
    /// 값을 입력하지 않으면 스마트 라우팅 그룹 아이디 필터링이 적용되지 않습니다.
    #[serde(rename = "channelGroupIds", skip_serializing_if = "Option::is_none")]
    pub channel_group_ids: Option<Vec<String>>,
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    #[serde(rename = "platformType", skip_serializing_if = "Option::is_none")]
    pub platform_type: Option<models::PaymentClientType>,
    #[serde(rename = "textSearch", skip_serializing_if = "Option::is_none")]
    pub text_search: Option<Box<models::BillingKeyTextSearch>>,
    /// 값을 입력하지 않으면 PG사 결제 모듈 필터링이 적용되지 않습니다.
    #[serde(rename = "pgProviders", skip_serializing_if = "Option::is_none")]
    pub pg_providers: Option<Vec<models::PgProvider>>,
    /// 값을 입력하지 않으면 PG사 필터링이 적용되지 않습니다.
    #[serde(rename = "pgCompanies", skip_serializing_if = "Option::is_none")]
    pub pg_companies: Option<Vec<models::PgCompany>>,
    /// 값을 입력하지 않으면 결제수단 필터링이 적용되지 않습니다.
    #[serde(rename = "methods", skip_serializing_if = "Option::is_none")]
    pub methods: Option<Vec<models::BillingKeyPaymentMethodType>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<models::PortOneVersion>,
}

impl BillingKeyFilterInput {
    /// 빌링키 다건 조회를 위한 입력 정보
    pub fn new() -> BillingKeyFilterInput {
        BillingKeyFilterInput {
            store_id: None,
            time_range_field: None,
            from: None,
            until: None,
            status: None,
            channel_group_ids: None,
            customer_id: None,
            platform_type: None,
            text_search: None,
            pg_providers: None,
            pg_companies: None,
            methods: None,
            version: None,
        }
    }
}
