/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// BillingKeyTimeRangeField : 빌링키 다건 조회 시, 시각 범위를 적용할 필드
/// 빌링키 다건 조회 시, 시각 범위를 적용할 필드
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum BillingKeyTimeRangeField {
    #[serde(rename = "REQUESTED_AT")]
    #[default]
    RequestedAt,
    #[serde(rename = "ISSUED_AT")]
    IssuedAt,
    #[serde(rename = "DELETED_AT")]
    DeletedAt,
    #[serde(rename = "STATUS_TIMESTAMP")]
    StatusTimestamp,
}

impl std::fmt::Display for BillingKeyTimeRangeField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RequestedAt => write!(f, "REQUESTED_AT"),
            Self::IssuedAt => write!(f, "ISSUED_AT"),
            Self::DeletedAt => write!(f, "DELETED_AT"),
            Self::StatusTimestamp => write!(f, "STATUS_TIMESTAMP"),
        }
    }
}
