/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// BillingKeyPaymentMethod : 빌링키 발급 수단 정보
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BillingKeyPaymentMethod {
    #[serde(rename = "BillingKeyPaymentMethodCard")]
    BillingKeyPaymentMethodCard(Box<models::BillingKeyPaymentMethodCard>),
    #[serde(rename = "BillingKeyPaymentMethodEasyPay")]
    BillingKeyPaymentMethodEasyPay(Box<models::BillingKeyPaymentMethodEasyPay>),
    #[serde(rename = "BillingKeyPaymentMethodMobile")]
    BillingKeyPaymentMethodMobile(Box<models::BillingKeyPaymentMethodMobile>),
    #[serde(rename = "BillingKeyPaymentMethodPaypal")]
    BillingKeyPaymentMethodPaypal(Box<models::BillingKeyPaymentMethodPaypal>),
    #[serde(rename = "BillingKeyPaymentMethodTransfer")]
    BillingKeyPaymentMethodTransfer(Box<models::BillingKeyPaymentMethodTransfer>),
}

impl Default for BillingKeyPaymentMethod {
    fn default() -> Self {
        Self::BillingKeyPaymentMethodCard(Default::default())
    }
}
