/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// BillingKeyPaymentMethodMobile : 모바일 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingKeyPaymentMethodMobile {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
}

impl BillingKeyPaymentMethodMobile {
    /// 모바일 정보
    pub fn new(r#type: String) -> BillingKeyPaymentMethodMobile {
        BillingKeyPaymentMethodMobile {
            r#type,
            phone_number: None,
        }
    }
}
