/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CancelAmountExceedsCancellableAmountError : 결제 취소 금액이 취소 가능 금액을 초과한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelAmountExceedsCancellableAmountError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl CancelAmountExceedsCancellableAmountError {
    /// 결제 취소 금액이 취소 가능 금액을 초과한 경우
    pub fn new(r#type: String) -> CancelAmountExceedsCancellableAmountError {
        CancelAmountExceedsCancellableAmountError {
            r#type,
            message: None,
        }
    }
}
