/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CancelTaxAmountExceedsCancellableTaxAmountError : 취소 과세 금액이 취소 가능한 과세 금액을 초과한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelTaxAmountExceedsCancellableTaxAmountError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl CancelTaxAmountExceedsCancellableTaxAmountError {
    /// 취소 과세 금액이 취소 가능한 과세 금액을 초과한 경우
    pub fn new(r#type: String) -> CancelTaxAmountExceedsCancellableTaxAmountError {
        CancelTaxAmountExceedsCancellableTaxAmountError {
            r#type,
            message: None,
        }
    }
}
