/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CancelPaymentResponse : 결제 취소 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelPaymentResponse {
    #[serde(rename = "cancellation")]
    pub cancellation: Box<models::PaymentCancellation>,
}

impl CancelPaymentResponse {
    /// 결제 취소 성공 응답
    pub fn new(cancellation: models::PaymentCancellation) -> CancelPaymentResponse {
        CancelPaymentResponse {
            cancellation: Box::new(cancellation),
        }
    }
}
