/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CancelB2bTaxInvoiceRequestBody : 세금계산서 역발행 요청 취소 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelB2bTaxInvoiceRequestBody {
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
}

impl CancelB2bTaxInvoiceRequestBody {
    /// 세금계산서 역발행 요청 취소 정보
    pub fn new() -> CancelB2bTaxInvoiceRequestBody {
        CancelB2bTaxInvoiceRequestBody { memo: None }
    }
}
