/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CapturePaymentBody : 수동 매입 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapturePaymentBody {
    /// 접근 권한이 있는 상점 아이디만 입력 가능하며, 미입력시 인증 정보의 상점 아이디를 사용합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
}

impl CapturePaymentBody {
    /// 수동 매입 입력 정보
    pub fn new() -> CapturePaymentBody {
        CapturePaymentBody { store_id: None }
    }
}
