/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CardOwnerType : 카드 소유주 유형
/// 카드 소유주 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CardOwnerType {
    #[serde(rename = "PERSONAL")]
    #[default]
    Personal,
    #[serde(rename = "CORPORATE")]
    Corporate,
}

impl std::fmt::Display for CardOwnerType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Personal => write!(f, "PERSONAL"),
            Self::Corporate => write!(f, "CORPORATE"),
        }
    }
}
