/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// Card : 카드 상세 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Card {
    #[serde(rename = "publisher", skip_serializing_if = "Option::is_none")]
    pub publisher: Option<String>,
    #[serde(rename = "issuer", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<String>,
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<models::CardBrand>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::CardType>,
    #[serde(rename = "ownerType", skip_serializing_if = "Option::is_none")]
    pub owner_type: Option<models::CardOwnerType>,
    #[serde(rename = "bin", skip_serializing_if = "Option::is_none")]
    pub bin: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
}

impl Card {
    /// 카드 상세 정보
    pub fn new() -> Card {
        Card {
            publisher: None,
            issuer: None,
            brand: None,
            r#type: None,
            owner_type: None,
            bin: None,
            name: None,
            number: None,
        }
    }
}
