/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// Carrier : 통신사
/// 통신사
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Carrier {
    #[serde(rename = "SKT")]
    #[default]
    Skt,
    #[serde(rename = "KT")]
    Kt,
    #[serde(rename = "LGU")]
    Lgu,
    #[serde(rename = "SKT_MVNO")]
    SktMvno,
    #[serde(rename = "KT_MVNO")]
    KtMvno,
    #[serde(rename = "LGU_MVNO")]
    LguMvno,
}

impl std::fmt::Display for Carrier {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Skt => write!(f, "SKT"),
            Self::Kt => write!(f, "KT"),
            Self::Lgu => write!(f, "LGU"),
            Self::SktMvno => write!(f, "SKT_MVNO"),
            Self::KtMvno => write!(f, "KT_MVNO"),
            Self::LguMvno => write!(f, "LGU_MVNO"),
        }
    }
}
