/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CashReceiptFilterInput : 현금영수증 다건 조회를 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashReceiptFilterInput {
    /// Merchant 사용자만 사용가능하며, 지정되지 않은 경우 고객사 전체 현금영수증을 조회합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    #[serde(rename = "timeRangeField", skip_serializing_if = "Option::is_none")]
    pub time_range_field: Option<models::CashReceiptTimeRangeField>,
    /// 값을 입력하지 않으면 end의 90일 전으로 설정됩니다.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// 값을 입력하지 않으면 현재 시점으로 설정됩니다.
    #[serde(rename = "until", skip_serializing_if = "Option::is_none")]
    pub until: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "paymentId", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<String>,
    #[serde(rename = "isTest", skip_serializing_if = "Option::is_none")]
    pub is_test: Option<bool>,
    #[serde(rename = "orderName", skip_serializing_if = "Option::is_none")]
    pub order_name: Option<String>,
    /// 값을 입력하지 않으면 필터링이 적용되지 않습니다.
    #[serde(rename = "statuses", skip_serializing_if = "Option::is_none")]
    pub statuses: Option<Vec<models::CashReceiptStatus>>,
    #[serde(rename = "isManual", skip_serializing_if = "Option::is_none")]
    pub is_manual: Option<bool>,
    #[serde(rename = "pgReceiptId", skip_serializing_if = "Option::is_none")]
    pub pg_receipt_id: Option<String>,
    #[serde(rename = "pgMerchantId", skip_serializing_if = "Option::is_none")]
    pub pg_merchant_id: Option<String>,
    /// 값을 입력하지 않으면 PG사 결제 모듈 필터링이 적용되지 않습니다.
    #[serde(rename = "pgProviders", skip_serializing_if = "Option::is_none")]
    pub pg_providers: Option<Vec<models::PgProvider>>,
    /// 값을 입력하지 않으면 PG사 필터링이 적용되지 않습니다.
    #[serde(rename = "pgCompanies", skip_serializing_if = "Option::is_none")]
    pub pg_companies: Option<Vec<models::PgCompany>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<models::PortOneVersion>,
    /// 값을 입력하지 않으면 필터링이 적용되지 않습니다.
    #[serde(rename = "types", skip_serializing_if = "Option::is_none")]
    pub types: Option<Vec<models::CashReceiptType>>,
}

impl CashReceiptFilterInput {
    /// 현금영수증 다건 조회를 위한 입력 정보
    pub fn new() -> CashReceiptFilterInput {
        CashReceiptFilterInput {
            store_id: None,
            time_range_field: None,
            from: None,
            until: None,
            payment_id: None,
            is_test: None,
            order_name: None,
            statuses: None,
            is_manual: None,
            pg_receipt_id: None,
            pg_merchant_id: None,
            pg_providers: None,
            pg_companies: None,
            version: None,
            types: None,
        }
    }
}
