/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CashReceiptIssuanceStatus : 현금영수증 발행여부
/// 현금영수증 발행여부
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CashReceiptIssuanceStatus {
    #[serde(rename = "ISSUED")]
    #[default]
    Issued,
    #[serde(rename = "NOT_ISSUED")]
    NotIssued,
}

impl std::fmt::Display for CashReceiptIssuanceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Issued => write!(f, "ISSUED"),
            Self::NotIssued => write!(f, "NOT_ISSUED"),
        }
    }
}
