/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CashReceipt : 현금영수증 내역
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum CashReceipt {
    #[serde(rename = "CANCELLED")]
    Cancelled(Box<models::CancelledCashReceipt>),
    #[serde(rename = "ISSUE_FAILED")]
    IssueFailed(Box<models::IssueFailedCashReceipt>),
    #[serde(rename = "ISSUED")]
    Issued(Box<models::IssuedCashReceipt>),
}

impl Default for CashReceipt {
    fn default() -> Self {
        Self::Cancelled(Default::default())
    }
}
