/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CashReceiptSummary : 현금영수증 내역
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashReceiptSummary {
    #[serde(rename = "issueNumber")]
    pub issue_number: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "pgReceiptId")]
    pub pg_receipt_id: String,
}

impl CashReceiptSummary {
    /// 현금영수증 내역
    pub fn new(issue_number: String, url: String, pg_receipt_id: String) -> CashReceiptSummary {
        CashReceiptSummary {
            issue_number,
            url,
            pg_receipt_id,
        }
    }
}
