/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CashReceiptSortInput : 현금영수증 다건 조회 시 정렬 조건
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashReceiptSortInput {
    #[serde(rename = "by", skip_serializing_if = "Option::is_none")]
    pub by: Option<models::CashReceiptSortBy>,
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<models::SortOrder>,
}

impl CashReceiptSortInput {
    /// 현금영수증 다건 조회 시 정렬 조건
    pub fn new() -> CashReceiptSortInput {
        CashReceiptSortInput {
            by: None,
            order: None,
        }
    }
}
