/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CashReceiptInputType : 입력 시 발급 유형
/// 입력 시 발급 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CashReceiptInputType {
    #[serde(rename = "PERSONAL")]
    #[default]
    Personal,
    #[serde(rename = "CORPORATE")]
    Corporate,
    #[serde(rename = "NO_RECEIPT")]
    NoReceipt,
}

impl std::fmt::Display for CashReceiptInputType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Personal => write!(f, "PERSONAL"),
            Self::Corporate => write!(f, "CORPORATE"),
            Self::NoReceipt => write!(f, "NO_RECEIPT"),
        }
    }
}
