/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ChannelSpecificFailure {
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::ChannelSpecificFailureInvalidRequest>),
    #[serde(rename = "PG_PROVIDER")]
    PgProvider(Box<models::ChannelSpecificFailurePgProvider>),
}

impl Default for ChannelSpecificFailure {
    fn default() -> Self {
        Self::InvalidRequest(Default::default())
    }
}
