/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ChannelSpecificFailurePgProvider : PG사에서 오류를 전달한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelSpecificFailurePgProvider {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "channel")]
    pub channel: Box<models::SelectedChannel>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "pgCode")]
    pub pg_code: String,
    #[serde(rename = "pgMessage")]
    pub pg_message: String,
}

impl ChannelSpecificFailurePgProvider {
    /// PG사에서 오류를 전달한 경우
    pub fn new(
        r#type: String,
        channel: models::SelectedChannel,
        pg_code: String,
        pg_message: String,
    ) -> ChannelSpecificFailurePgProvider {
        ChannelSpecificFailurePgProvider {
            r#type,
            channel: Box::new(channel),
            message: None,
            pg_code,
            pg_message,
        }
    }
}
