/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CloseVirtualAccountResponse : 가상계좌 말소 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloseVirtualAccountResponse {
    #[serde(rename = "closedAt")]
    pub closed_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CloseVirtualAccountResponse {
    /// 가상계좌 말소 성공 응답
    pub fn new(closed_at: chrono::DateTime<chrono::FixedOffset>) -> CloseVirtualAccountResponse {
        CloseVirtualAccountResponse { closed_at }
    }
}
