/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CompletePlatformPayoutByPartnerSettlementIdsResponse : 일괄 지급 완료 처리 결과
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletePlatformPayoutByPartnerSettlementIdsResponse {
    #[serde(rename = "bulkPayoutId", skip_serializing_if = "Option::is_none")]
    pub bulk_payout_id: Option<String>,
    #[serde(
        rename = "bulkPayoutGraphqlId",
        skip_serializing_if = "Option::is_none"
    )]
    pub bulk_payout_graphql_id: Option<String>,
    #[serde(rename = "payoutCount")]
    pub payout_count: i32,
    #[serde(rename = "partnerSettlementCount")]
    pub partner_settlement_count: i32,
}

impl CompletePlatformPayoutByPartnerSettlementIdsResponse {
    /// 일괄 지급 완료 처리 결과
    pub fn new(
        payout_count: i32,
        partner_settlement_count: i32,
    ) -> CompletePlatformPayoutByPartnerSettlementIdsResponse {
        CompletePlatformPayoutByPartnerSettlementIdsResponse {
            bulk_payout_id: None,
            bulk_payout_graphql_id: None,
            payout_count,
            partner_settlement_count,
        }
    }
}
