/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ConfirmPaymentBody : 결제 승인 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfirmPaymentBody {
    /// 접근 권한이 있는 상점 아이디만 입력 가능하며, 미입력시 인증 정보의 상점 아이디를 사용합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    /// 인증 완료 시 발급된 토큰입니다.
    #[serde(rename = "paymentToken")]
    pub payment_token: String,
    /// 검증용 파라미터로, 결제 시도 아이디와 일치하지 않을 경우 오류가 반환됩니다.
    #[serde(rename = "txId", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<models::Currency>,
    /// 검증용 파라미터로, 결제 건 총 금액과 일치하지 않을 경우 오류가 반환됩니다. 값 전달을 권장합니다.
    #[serde(rename = "totalAmount", skip_serializing_if = "Option::is_none")]
    pub total_amount: Option<i64>,
    /// 검증용 파라미터로, 결제 건 면세 금액과 일치하지 않을 경우 오류가 반환됩니다.
    #[serde(rename = "taxFreeAmount", skip_serializing_if = "Option::is_none")]
    pub tax_free_amount: Option<i64>,
    /// 검증용 파라미터로, 결제 건 테스트 여부와 일치하지 않을 경우 오류가 반환됩니다. 값 전달을 권장합니다.
    #[serde(rename = "isTest", skip_serializing_if = "Option::is_none")]
    pub is_test: Option<bool>,
    /// 결제가 성공했을 때 웹훅을 전송하지 않으려면 true로 설정합니다. 가상계좌 입금 완료 등 외부 이벤트로 결제가 완료되는 경우 발생하는 웹훅은 스킵되지 않습니다.
    #[serde(rename = "skipWebhook", skip_serializing_if = "Option::is_none")]
    pub skip_webhook: Option<bool>,
}

impl ConfirmPaymentBody {
    /// 결제 승인 입력 정보
    pub fn new(payment_token: String) -> ConfirmPaymentBody {
        ConfirmPaymentBody {
            store_id: None,
            payment_token,
            tx_id: None,
            currency: None,
            total_amount: None,
            tax_free_amount: None,
            is_test: None,
            skip_webhook: None,
        }
    }
}
