/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ConfirmEscrowBody : 에스크로 구매 확정 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfirmEscrowBody {
    /// 접근 권한이 있는 상점 아이디만 입력 가능하며, 미입력시 인증 정보의 상점 아이디를 사용합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    /// 구매확정요청 주체가 고객사 관리자인지 구매자인지 구분하기 위한 필드입니다. 네이버페이 전용 파라미터이며, 구분이 모호한 경우 고객사 관리자(true)로 입력합니다.
    #[serde(rename = "fromStore", skip_serializing_if = "Option::is_none")]
    pub from_store: Option<bool>,
}

impl ConfirmEscrowBody {
    /// 에스크로 구매 확정 입력 정보
    pub fn new() -> ConfirmEscrowBody {
        ConfirmEscrowBody {
            store_id: None,
            from_store: None,
        }
    }
}
