/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ConfirmPaymentError {
    #[serde(rename = "ALREADY_PAID")]
    AlreadyPaid(Box<models::AlreadyPaidError>),
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INFORMATION_MISMATCH")]
    InformationMismatch(Box<models::InformationMismatchError>),
    #[serde(rename = "INVALID_PAYMENT_TOKEN")]
    InvalidPaymentToken(Box<models::InvalidPaymentTokenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PAYMENT_NOT_FOUND")]
    PaymentNotFound(Box<models::PaymentNotFoundError>),
    #[serde(rename = "PG_PROVIDER")]
    PgProvider(Box<models::PgProviderError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for ConfirmPaymentError {
    fn default() -> Self {
        Self::AlreadyPaid(Default::default())
    }
}
