/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ConfirmedBillingKeyIssueAndPaySummary : 빌링키 발급 및 초회 결제 수동 승인 완료 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfirmedBillingKeyIssueAndPaySummary {
    #[serde(rename = "billingKey")]
    pub billing_key: String,
    #[serde(rename = "paymentId")]
    pub payment_id: String,
}

impl ConfirmedBillingKeyIssueAndPaySummary {
    /// 빌링키 발급 및 초회 결제 수동 승인 완료 응답
    pub fn new(billing_key: String, payment_id: String) -> ConfirmedBillingKeyIssueAndPaySummary {
        ConfirmedBillingKeyIssueAndPaySummary {
            billing_key,
            payment_id,
        }
    }
}
