/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ConfirmedBillingKeySummary : 빌링키 발급 수동 승인 완료 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfirmedBillingKeySummary {
    #[serde(rename = "billingKey")]
    pub billing_key: String,
}

impl ConfirmedBillingKeySummary {
    /// 빌링키 발급 수동 승인 완료 응답
    pub fn new(billing_key: String) -> ConfirmedBillingKeySummary {
        ConfirmedBillingKeySummary { billing_key }
    }
}
