/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ConnectBulkPartnerCounterpartyResponse : 파트너 일괄 거래처 연동 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectBulkPartnerCounterpartyResponse {
    #[serde(rename = "bulkTask")]
    pub bulk_task: Box<models::PlatformBulkTask>,
}

impl ConnectBulkPartnerCounterpartyResponse {
    /// 파트너 일괄 거래처 연동 응답
    pub fn new(bulk_task: models::PlatformBulkTask) -> ConnectBulkPartnerCounterpartyResponse {
        ConnectBulkPartnerCounterpartyResponse {
            bulk_task: Box::new(bulk_task),
        }
    }
}
