/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ConnectBulkPartnerCounterpartyBody : 파트너 일괄 거래처 연동 요청 정보  파트너들을 일괄 거래처 연동합니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectBulkPartnerCounterpartyBody {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::PlatformPartnerFilterInput>>,
}

impl ConnectBulkPartnerCounterpartyBody {
    /// 파트너 일괄 거래처 연동 요청 정보  파트너들을 일괄 거래처 연동합니다.
    pub fn new() -> ConnectBulkPartnerCounterpartyBody {
        ConnectBulkPartnerCounterpartyBody { filter: None }
    }
}
