/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ConnectPartnerCounterpartyResponse : 파트너 거래처 연동 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectPartnerCounterpartyResponse {
    #[serde(rename = "partner")]
    pub partner: Box<models::PlatformPartner>,
}

impl ConnectPartnerCounterpartyResponse {
    /// 파트너 거래처 연동 응답
    pub fn new(partner: models::PlatformPartner) -> ConnectPartnerCounterpartyResponse {
        ConnectPartnerCounterpartyResponse {
            partner: Box::new(partner),
        }
    }
}
