/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CreatePlatformPartnersError {
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PLATFORM_CONTRACTS_NOT_FOUND")]
    PlatformContractsNotFound(Box<models::PlatformContractsNotFoundError>),
    #[serde(rename = "PLATFORM_CURRENCY_NOT_SUPPORTED")]
    PlatformCurrencyNotSupported(Box<models::PlatformCurrencyNotSupportedError>),
    #[serde(rename = "PLATFORM_NOT_ENABLED")]
    PlatformNotEnabled(Box<models::PlatformNotEnabledError>),
    #[serde(rename = "PLATFORM_PARTNER_IDS_ALREADY_EXISTS")]
    PlatformPartnerIdsAlreadyExists(Box<models::PlatformPartnerIdsAlreadyExistError>),
    #[serde(rename = "PLATFORM_PARTNER_IDS_DUPLICATED")]
    PlatformPartnerIdsDuplicated(Box<models::PlatformPartnerIdsDuplicatedError>),
    #[serde(rename = "PLATFORM_USER_DEFINED_PROPERTY_NOT_FOUND")]
    PlatformUserDefinedPropertyNotFound(Box<models::PlatformUserDefinedPropertyNotFoundError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for CreatePlatformPartnersError {
    fn default() -> Self {
        Self::Forbidden(Default::default())
    }
}
