/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformAdditionalFeePolicyResponse : 플랫폼 생성 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformAdditionalFeePolicyResponse {
    #[serde(rename = "additionalFeePolicy")]
    pub additional_fee_policy: Box<models::PlatformAdditionalFeePolicy>,
}

impl CreatePlatformAdditionalFeePolicyResponse {
    /// 플랫폼 생성 성공 응답 정보
    pub fn new(
        additional_fee_policy: models::PlatformAdditionalFeePolicy,
    ) -> CreatePlatformAdditionalFeePolicyResponse {
        CreatePlatformAdditionalFeePolicyResponse {
            additional_fee_policy: Box::new(additional_fee_policy),
        }
    }
}
