/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformOrderTransferBodyOrderDetail : 주문 정보  주문 금액 또는 주문 항목 하나만 입력 가능합니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformOrderTransferBodyOrderDetail {
    #[serde(rename = "orderAmount", skip_serializing_if = "Option::is_none")]
    pub order_amount: Option<i64>,
    #[serde(rename = "orderLines", skip_serializing_if = "Option::is_none")]
    pub order_lines: Option<Vec<models::CreatePlatformOrderTransferBodyOrderLine>>,
}

impl CreatePlatformOrderTransferBodyOrderDetail {
    /// 주문 정보  주문 금액 또는 주문 항목 하나만 입력 가능합니다.
    pub fn new() -> CreatePlatformOrderTransferBodyOrderDetail {
        CreatePlatformOrderTransferBodyOrderDetail {
            order_amount: None,
            order_lines: None,
        }
    }
}
