/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreateB2bCounterpartyResponse : 거래처 생성 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateB2bCounterpartyResponse {
    #[serde(rename = "counterparty")]
    pub counterparty: Box<models::B2bCounterparty>,
}

impl CreateB2bCounterpartyResponse {
    /// 거래처 생성 응답 정보
    pub fn new(counterparty: models::B2bCounterparty) -> CreateB2bCounterpartyResponse {
        CreateB2bCounterpartyResponse {
            counterparty: Box::new(counterparty),
        }
    }
}
