/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformOrderTransferBodyExternalPaymentDetail : 외부 결제 상세 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformOrderTransferBodyExternalPaymentDetail {
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "orderName", skip_serializing_if = "Option::is_none")]
    pub order_name: Option<String>,
    #[serde(rename = "paidAt", skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<Box<models::PlatformPaymentMethodInput>>,
}

impl CreatePlatformOrderTransferBodyExternalPaymentDetail {
    /// 외부 결제 상세 정보
    pub fn new(currency: models::Currency) -> CreatePlatformOrderTransferBodyExternalPaymentDetail {
        CreatePlatformOrderTransferBodyExternalPaymentDetail {
            currency,
            order_name: None,
            paid_at: None,
            method: None,
        }
    }
}
