/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CreatePlatformOrderTransferError {
    #[serde(rename="FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename="INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename="PLATFORM_ADDITIONAL_FEE_POLICIES_NOT_FOUND")]
    PlatformAdditionalFeePoliciesNotFound(Box<models::PlatformAdditionalFeePoliciesNotFoundError>),
    #[serde(rename="PLATFORM_ADDITIONAL_FIXED_AMOUNT_FEE_CURRENCY_AND_SETTLEMENT_CURRENCY_MISMATCHED")]
    PlatformAdditionalFixedAmountFeeCurrencyAndSettlementCurrencyMismatched(Box<models::PlatformAdditionalFixedAmountFeeCurrencyAndSettlementCurrencyMismatchedError>),
    #[serde(rename="PLATFORM_CONTRACT_NOT_FOUND")]
    PlatformContractNotFound(Box<models::PlatformContractNotFoundError>),
    #[serde(rename="PLATFORM_CONTRACT_PLATFORM_FIXED_AMOUNT_FEE_CURRENCY_AND_SETTLEMENT_CURRENCY_MISMATCHED")]
    PlatformContractPlatformFixedAmountFeeCurrencyAndSettlementCurrencyMismatched(Box<models::PlatformContractPlatformFixedAmountFeeCurrencyAndSettlementCurrencyMismatchedError>),
    #[serde(rename="PLATFORM_CURRENCY_NOT_SUPPORTED")]
    PlatformCurrencyNotSupported(Box<models::PlatformCurrencyNotSupportedError>),
    #[serde(rename="PLATFORM_DISCOUNT_SHARE_POLICIES_NOT_FOUND")]
    PlatformDiscountSharePoliciesNotFound(Box<models::PlatformDiscountSharePoliciesNotFoundError>),
    #[serde(rename="PLATFORM_NOT_ENABLED")]
    PlatformNotEnabled(Box<models::PlatformNotEnabledError>),
    #[serde(rename="PLATFORM_PARTNER_NOT_FOUND")]
    PlatformPartnerNotFound(Box<models::PlatformPartnerNotFoundError>),
    #[serde(rename="PLATFORM_PAYMENT_NOT_FOUND")]
    PlatformPaymentNotFound(Box<models::PlatformPaymentNotFoundError>),
    #[serde(rename="PLATFORM_PRODUCT_ID_DUPLICATED")]
    PlatformProductIdDuplicated(Box<models::PlatformProductIdDuplicatedError>),
    #[serde(rename="PLATFORM_SETTLEMENT_AMOUNT_EXCEEDED")]
    PlatformSettlementAmountExceeded(Box<models::PlatformSettlementAmountExceededError>),
    #[serde(rename="PLATFORM_SETTLEMENT_DATE_EARLIER_THAN_SETTLEMENT_START_DATE")]
    PlatformSettlementDateEarlierThanSettlementStartDate(Box<models::PlatformSettlementDateEarlierThanSettlementStartDateError>),
    #[serde(rename="PLATFORM_SETTLEMENT_PARAMETER_NOT_FOUND")]
    PlatformSettlementParameterNotFound(Box<models::PlatformSettlementParameterNotFoundError>),
    #[serde(rename="PLATFORM_SETTLEMENT_PAYMENT_AMOUNT_EXCEEDED_PORT_ONE_PAYMENT")]
    PlatformSettlementPaymentAmountExceededPortOnePayment(Box<models::PlatformSettlementPaymentAmountExceededPortOnePaymentError>),
    #[serde(rename="PLATFORM_SETTLEMENT_SUPPLY_WITH_VAT_AMOUNT_EXCEEDED_PORT_ONE_PAYMENT")]
    PlatformSettlementSupplyWithVatAmountExceededPortOnePayment(Box<models::PlatformSettlementSupplyWithVatAmountExceededPortOnePaymentError>),
    #[serde(rename="PLATFORM_SETTLEMENT_TAX_FREE_AMOUNT_EXCEEDED_PORT_ONE_PAYMENT")]
    PlatformSettlementTaxFreeAmountExceededPortOnePayment(Box<models::PlatformSettlementTaxFreeAmountExceededPortOnePaymentError>),
    #[serde(rename="PLATFORM_TRANSFER_ALREADY_EXISTS")]
    PlatformTransferAlreadyExists(Box<models::PlatformTransferAlreadyExistsError>),
    #[serde(rename="PLATFORM_TRANSFER_ID_ALREADY_USED")]
    PlatformTransferIdAlreadyUsed(Box<models::PlatformTransferIdAlreadyUsedError>),
    #[serde(rename="PLATFORM_USER_DEFINED_PROPERTY_NOT_FOUND")]
    PlatformUserDefinedPropertyNotFound(Box<models::PlatformUserDefinedPropertyNotFoundError>),
    #[serde(rename="UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for CreatePlatformOrderTransferError {
    fn default() -> Self {
        Self::Forbidden(Default::default())
    }
}
