/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformManualTransferBody : 수기 정산건 생성을 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformManualTransferBody {
    #[serde(rename = "partnerId")]
    pub partner_id: String,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "settlementAmount")]
    pub settlement_amount: i64,
    #[serde(
        rename = "settlementTaxFreeAmount",
        skip_serializing_if = "Option::is_none"
    )]
    pub settlement_tax_free_amount: Option<i64>,
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "settlementDate")]
    pub settlement_date: chrono::NaiveDate,
    /// Query Parameter의 test에 값이 제공된 경우 Query Parameter의 test를 사용하고 해당 값은 무시됩니다. Query Parameter의 test와 Request Body의 isForTest에 모두 값이 제공되지 않으면 기본값인 false로 적용됩니다.
    #[serde(rename = "isForTest", skip_serializing_if = "Option::is_none")]
    pub is_for_test: Option<bool>,
    #[serde(
        rename = "userDefinedProperties",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_defined_properties: Option<Vec<models::PlatformUserDefinedPropertyKeyValue>>,
    /// 명시하지 않으면 id 가 임의로 생성됩니다.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "settlementCurrency", skip_serializing_if = "Option::is_none")]
    pub settlement_currency: Option<models::Currency>,
}

impl CreatePlatformManualTransferBody {
    /// 수기 정산건 생성을 위한 입력 정보
    pub fn new(
        partner_id: String,
        settlement_amount: i64,
        settlement_date: chrono::NaiveDate,
    ) -> CreatePlatformManualTransferBody {
        CreatePlatformManualTransferBody {
            partner_id,
            memo: None,
            settlement_amount,
            settlement_tax_free_amount: None,
            settlement_date,
            is_for_test: None,
            user_defined_properties: None,
            id: None,
            settlement_currency: None,
        }
    }
}
