/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrderTransferResponse {
    #[serde(rename = "transfer")]
    pub transfer: Box<models::PlatformOrderTransfer>,
}

impl CreateOrderTransferResponse {
    pub fn new(transfer: models::PlatformOrderTransfer) -> CreateOrderTransferResponse {
        CreateOrderTransferResponse {
            transfer: Box::new(transfer),
        }
    }
}
