/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformPartnerResponse : 파트너 생성 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformPartnerResponse {
    #[serde(rename = "partner")]
    pub partner: Box<models::PlatformPartner>,
}

impl CreatePlatformPartnerResponse {
    /// 파트너 생성 성공 응답
    pub fn new(partner: models::PlatformPartner) -> CreatePlatformPartnerResponse {
        CreatePlatformPartnerResponse {
            partner: Box::new(partner),
        }
    }
}
