/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformContractBody : 계약 객체 생성을 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformContractBody {
    /// 명시하지 않는 경우 포트원이 임의의 아이디를 발급해드립니다.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "platformFee")]
    pub platform_fee: Box<models::PlatformFeeInput>,
    #[serde(rename = "settlementCycle")]
    pub settlement_cycle: Box<models::PlatformSettlementCycleInput>,
    #[serde(rename = "platformFeeVatPayer")]
    pub platform_fee_vat_payer: models::PlatformPayer,
    #[serde(rename = "subtractPaymentVatAmount")]
    pub subtract_payment_vat_amount: bool,
}

impl CreatePlatformContractBody {
    /// 계약 객체 생성을 위한 입력 정보
    pub fn new(
        name: String,
        platform_fee: models::PlatformFeeInput,
        settlement_cycle: models::PlatformSettlementCycleInput,
        platform_fee_vat_payer: models::PlatformPayer,
        subtract_payment_vat_amount: bool,
    ) -> CreatePlatformContractBody {
        CreatePlatformContractBody {
            id: None,
            name,
            memo: None,
            platform_fee: Box::new(platform_fee),
            settlement_cycle: Box::new(settlement_cycle),
            platform_fee_vat_payer,
            subtract_payment_vat_amount,
        }
    }
}
