/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CreatePlatformOrderCancelTransferBodyExternalCancellationDetail : 외부 결제 상세 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformOrderCancelTransferBodyExternalCancellationDetail {
    #[serde(rename = "cancelledAt", skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl CreatePlatformOrderCancelTransferBodyExternalCancellationDetail {
    /// 외부 결제 상세 정보
    pub fn new() -> CreatePlatformOrderCancelTransferBodyExternalCancellationDetail {
        CreatePlatformOrderCancelTransferBodyExternalCancellationDetail { cancelled_at: None }
    }
}
