/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformAdditionalFeePolicyBody : 추가 수수료 정책 생성을 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformAdditionalFeePolicyBody {
    /// 명시하지 않으면 id 가 임의로 생성됩니다.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "fee")]
    pub fee: Box<models::PlatformFeeInput>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "vatPayer")]
    pub vat_payer: models::PlatformPayer,
}

impl CreatePlatformAdditionalFeePolicyBody {
    /// 추가 수수료 정책 생성을 위한 입력 정보
    pub fn new(
        name: String,
        fee: models::PlatformFeeInput,
        vat_payer: models::PlatformPayer,
    ) -> CreatePlatformAdditionalFeePolicyBody {
        CreatePlatformAdditionalFeePolicyBody {
            id: None,
            name,
            fee: Box::new(fee),
            memo: None,
            vat_payer,
        }
    }
}
