/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformDiscountSharePolicyResponse : 할인 분담 정책 생성 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformDiscountSharePolicyResponse {
    #[serde(rename = "discountSharePolicy")]
    pub discount_share_policy: Box<models::PlatformDiscountSharePolicy>,
}

impl CreatePlatformDiscountSharePolicyResponse {
    /// 할인 분담 정책 생성 성공 응답
    pub fn new(
        discount_share_policy: models::PlatformDiscountSharePolicy,
    ) -> CreatePlatformDiscountSharePolicyResponse {
        CreatePlatformDiscountSharePolicyResponse {
            discount_share_policy: Box::new(discount_share_policy),
        }
    }
}
