/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CreatePaymentSessionResponse : 결제 세션 생성 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePaymentSessionResponse {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "expiresAt")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CreatePaymentSessionResponse {
    /// 결제 세션 생성 성공 응답
    pub fn new(
        session_id: String,
        url: String,
        expires_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> CreatePaymentSessionResponse {
        CreatePaymentSessionResponse {
            session_id,
            url,
            expires_at,
        }
    }
}
