/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformOrderTransferBody : 주문 정산건 생성을 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformOrderTransferBody {
    #[serde(rename = "partnerId")]
    pub partner_id: String,
    /// 기본값은 파트너의 기본 계약 아이디 입니다.
    #[serde(rename = "contractId", skip_serializing_if = "Option::is_none")]
    pub contract_id: Option<String>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "paymentId")]
    pub payment_id: String,
    #[serde(rename = "orderDetail")]
    pub order_detail: Box<models::CreatePlatformOrderTransferBodyOrderDetail>,
    /// 주문 항목과 면세 금액을 같이 전달하시면 최종 면세 금액은 주문 항목의 면세 금액이 아닌 전달해주신 면세 금액으로 적용됩니다.
    #[serde(rename = "taxFreeAmount", skip_serializing_if = "Option::is_none")]
    pub tax_free_amount: Option<i64>,
    /// 기본값은 결제 일시 입니다.
    #[serde(
        rename = "settlementStartDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub settlement_start_date: Option<chrono::NaiveDate>,
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "settlementDate", skip_serializing_if = "Option::is_none")]
    pub settlement_date: Option<chrono::NaiveDate>,
    #[serde(rename = "discounts")]
    pub discounts: Vec<models::CreatePlatformOrderCancelTransferBodyDiscount>,
    #[serde(rename = "additionalFees")]
    pub additional_fees: Vec<models::CreatePlatformOrderTransferBodyAdditionalFee>,
    #[serde(
        rename = "externalPaymentDetail",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_payment_detail:
        Option<Box<models::CreatePlatformOrderTransferBodyExternalPaymentDetail>>,
    /// Query Parameter의 test에 값이 제공된 경우 Query Parameter의 test를 사용하고 해당 값은 무시됩니다. Query Parameter의 test와 Request Body의 isForTest에 모두 값이 제공되지 않으면 기본값인 false로 적용됩니다.
    #[serde(rename = "isForTest", skip_serializing_if = "Option::is_none")]
    pub is_for_test: Option<bool>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters:
        Option<std::collections::HashMap<String, models::PlatformSettlementParameterValue>>,
    #[serde(
        rename = "userDefinedProperties",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_defined_properties: Option<Vec<models::PlatformUserDefinedPropertyKeyValue>>,
    /// 명시하지 않으면 id 가 임의로 생성됩니다.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl CreatePlatformOrderTransferBody {
    /// 주문 정산건 생성을 위한 입력 정보
    pub fn new(
        partner_id: String,
        payment_id: String,
        order_detail: models::CreatePlatformOrderTransferBodyOrderDetail,
        discounts: Vec<models::CreatePlatformOrderCancelTransferBodyDiscount>,
        additional_fees: Vec<models::CreatePlatformOrderTransferBodyAdditionalFee>,
    ) -> CreatePlatformOrderTransferBody {
        CreatePlatformOrderTransferBody {
            partner_id,
            contract_id: None,
            memo: None,
            payment_id,
            order_detail: Box::new(order_detail),
            tax_free_amount: None,
            settlement_start_date: None,
            settlement_date: None,
            discounts,
            additional_fees,
            external_payment_detail: None,
            is_for_test: None,
            parameters: None,
            user_defined_properties: None,
            id: None,
        }
    }
}
