/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformPartnerBodyTypeBusiness {
    #[serde(rename = "companyName")]
    pub company_name: String,
    #[serde(rename = "taxationType", skip_serializing_if = "Option::is_none")]
    pub taxation_type: Option<models::PlatformPartnerTaxationType>,
    #[serde(rename = "businessRegistrationNumber")]
    pub business_registration_number: String,
    #[serde(rename = "representativeName")]
    pub representative_name: String,
    #[serde(rename = "companyAddress", skip_serializing_if = "Option::is_none")]
    pub company_address: Option<String>,
    #[serde(rename = "businessType", skip_serializing_if = "Option::is_none")]
    pub business_type: Option<String>,
    #[serde(rename = "businessClass", skip_serializing_if = "Option::is_none")]
    pub business_class: Option<String>,
    #[serde(
        rename = "companyVerificationId",
        skip_serializing_if = "Option::is_none"
    )]
    pub company_verification_id: Option<String>,
}

impl CreatePlatformPartnerBodyTypeBusiness {
    pub fn new(
        company_name: String,
        business_registration_number: String,
        representative_name: String,
    ) -> CreatePlatformPartnerBodyTypeBusiness {
        CreatePlatformPartnerBodyTypeBusiness {
            company_name,
            taxation_type: None,
            business_registration_number,
            representative_name,
            company_address: None,
            business_type: None,
            business_class: None,
            company_verification_id: None,
        }
    }
}
