/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformPartnersResponse : 파트너 다건 생성 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformPartnersResponse {
    #[serde(rename = "partners")]
    pub partners: Vec<models::PlatformPartner>,
}

impl CreatePlatformPartnersResponse {
    /// 파트너 다건 생성 성공 응답
    pub fn new(partners: Vec<models::PlatformPartner>) -> CreatePlatformPartnersResponse {
        CreatePlatformPartnersResponse { partners }
    }
}
