/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CreatePlatformPartnerBody : 파트너 생성을 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePlatformPartnerBody {
    /// 고객사 서버에 등록된 파트너 지칭 아이디와 동일하게 설정하는 것을 권장합니다. 명시하지 않는 경우 포트원이 임의의 아이디를 발급해드립니다.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "contact")]
    pub contact: Box<models::CreatePlatformPartnerBodyContact>,
    #[serde(rename = "account")]
    pub account: Box<models::CreatePlatformPartnerBodyAccount>,
    /// 이미 존재하는 계약 아이디를 등록해야 합니다.
    #[serde(rename = "defaultContractId")]
    pub default_contract_id: String,
    /// 총 256자까지 입력할 수 있습니다.
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// 최대 10개까지 입력할 수 있습니다.
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "type")]
    pub r#type: Box<models::CreatePlatformPartnerBodyType>,
    #[serde(
        rename = "userDefinedProperties",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_defined_properties:
        Option<std::collections::HashMap<String, models::PlatformUserDefinedPropertyValue>>,
}

impl CreatePlatformPartnerBody {
    /// 파트너 생성을 위한 입력 정보
    pub fn new(
        name: String,
        contact: models::CreatePlatformPartnerBodyContact,
        account: models::CreatePlatformPartnerBodyAccount,
        default_contract_id: String,
        tags: Vec<String>,
        r#type: models::CreatePlatformPartnerBodyType,
    ) -> CreatePlatformPartnerBody {
        CreatePlatformPartnerBody {
            id: None,
            name,
            contact: Box::new(contact),
            account: Box::new(account),
            default_contract_id,
            memo: None,
            tags,
            r#type: Box::new(r#type),
            user_defined_properties: None,
        }
    }
}
