/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CreateB2bFileUploadUrlBody : 파일 업로드 URL 생성 요청 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateB2bFileUploadUrlBody {
    #[serde(rename = "fileName")]
    pub file_name: String,
}

impl CreateB2bFileUploadUrlBody {
    /// 파일 업로드 URL 생성 요청 정보
    pub fn new(file_name: String) -> CreateB2bFileUploadUrlBody {
        CreateB2bFileUploadUrlBody { file_name }
    }
}
