/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// CustomerNameInput : 고객 이름 입력 정보  두 개의 이름 형식 중 한 가지만 선택하여 입력해주세요.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerNameInput {
    #[serde(rename = "full", skip_serializing_if = "Option::is_none")]
    pub full: Option<String>,
    #[serde(rename = "separated", skip_serializing_if = "Option::is_none")]
    pub separated: Option<Box<models::CustomerSeparatedName>>,
}

impl CustomerNameInput {
    /// 고객 이름 입력 정보  두 개의 이름 형식 중 한 가지만 선택하여 입력해주세요.
    pub fn new() -> CustomerNameInput {
        CustomerNameInput {
            full: None,
            separated: None,
        }
    }
}
