/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DateRangeOption {
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<chrono::NaiveDate>,
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "until", skip_serializing_if = "Option::is_none")]
    pub until: Option<chrono::NaiveDate>,
}

impl DateRangeOption {
    pub fn new() -> DateRangeOption {
        DateRangeOption {
            from: None,
            until: None,
        }
    }
}
