/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DeleteB2bTaxInvoiceAttachmentError {
    #[serde(rename = "B2B_EXTERNAL_SERVICE")]
    B2BExternalService(Box<models::B2bExternalServiceError>),
    #[serde(rename = "B2B_NOT_ENABLED")]
    B2BNotEnabled(Box<models::B2bNotEnabledError>),
    #[serde(rename = "B2B_TAX_INVOICE_ATTACHMENT_NOT_FOUND")]
    B2BTaxInvoiceAttachmentNotFound(Box<models::B2bTaxInvoiceAttachmentNotFoundError>),
    #[serde(rename = "B2B_TAX_INVOICE_NOT_DRAFTED_STATUS")]
    B2BTaxInvoiceNotDraftedStatus(Box<models::B2bTaxInvoiceNotDraftedStatusError>),
    #[serde(rename = "B2B_TAX_INVOICE_NOT_FOUND")]
    B2BTaxInvoiceNotFound(Box<models::B2bTaxInvoiceNotFoundError>),
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for DeleteB2bTaxInvoiceAttachmentError {
    fn default() -> Self {
        Self::B2BExternalService(Default::default())
    }
}
