/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DeleteB2bCounterpartyError {
    #[serde(rename = "B2B_COUNTERPARTY_NOT_FOUND")]
    B2BCounterpartyNotFound(Box<models::B2bCounterpartyNotFoundError>),
    #[serde(rename = "B2B_COUNTERPARTY_ONGOING_TAX_INVOICE_EXISTS")]
    B2BCounterpartyOngoingTaxInvoiceExists(
        Box<models::B2bCounterpartyOngoingTaxInvoiceExistsError>,
    ),
    #[serde(rename = "B2B_COUNTERPARTY_PARTNER_NOT_DELETABLE")]
    B2BCounterpartyPartnerNotDeletable(Box<models::B2bCounterpartyPartnerNotDeletableError>),
    #[serde(rename = "B2B_EXTERNAL_SERVICE")]
    B2BExternalService(Box<models::B2bExternalServiceError>),
    #[serde(rename = "B2B_NOT_ENABLED")]
    B2BNotEnabled(Box<models::B2bNotEnabledError>),
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for DeleteB2bCounterpartyError {
    fn default() -> Self {
        Self::B2BCounterpartyNotFound(Default::default())
    }
}
