/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DeletePlatformTransferError {
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PLATFORM_CANCEL_ORDER_TRANSFERS_EXISTS")]
    PlatformCancelOrderTransfersExists(Box<models::PlatformCancelOrderTransfersExistsError>),
    #[serde(rename = "PLATFORM_NOT_ENABLED")]
    PlatformNotEnabled(Box<models::PlatformNotEnabledError>),
    #[serde(rename = "PLATFORM_TRANSFER_NON_DELETABLE_STATUS")]
    PlatformTransferNonDeletableStatus(Box<models::PlatformTransferNonDeletableStatusError>),
    #[serde(rename = "PLATFORM_TRANSFER_NOT_FOUND")]
    PlatformTransferNotFound(Box<models::PlatformTransferNotFoundError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for DeletePlatformTransferError {
    fn default() -> Self {
        Self::Forbidden(Default::default())
    }
}
