/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DeleteBillingKeyError {
    #[serde(rename = "BILLING_KEY_ALREADY_DELETED")]
    BillingKeyAlreadyDeleted(Box<models::BillingKeyAlreadyDeletedError>),
    #[serde(rename = "BILLING_KEY_NOT_FOUND")]
    BillingKeyNotFound(Box<models::BillingKeyNotFoundError>),
    #[serde(rename = "BILLING_KEY_NOT_ISSUED")]
    BillingKeyNotIssued(Box<models::BillingKeyNotIssuedError>),
    #[serde(rename = "CHANNEL_SPECIFIC")]
    ChannelSpecific(Box<models::ChannelSpecificError>),
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PAYMENT_SCHEDULE_ALREADY_EXISTS")]
    PaymentScheduleAlreadyExists(Box<models::PaymentScheduleAlreadyExistsError>),
    #[serde(rename = "PG_PROVIDER")]
    PgProvider(Box<models::PgProviderError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for DeleteBillingKeyError {
    fn default() -> Self {
        Self::BillingKeyAlreadyDeleted(Default::default())
    }
}
