/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DeleteBillingKeyResponse : 빌링키 삭제 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteBillingKeyResponse {
    #[serde(rename = "deletedAt")]
    pub deleted_at: chrono::DateTime<chrono::FixedOffset>,
}

impl DeleteBillingKeyResponse {
    /// 빌링키 삭제 성공 응답
    pub fn new(deleted_at: chrono::DateTime<chrono::FixedOffset>) -> DeleteBillingKeyResponse {
        DeleteBillingKeyResponse { deleted_at }
    }
}
