/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// Dispute : 분쟁 내역
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Dispute {
    #[serde(rename = "status")]
    pub status: models::DisputeStatus,
    #[serde(rename = "pgDisputeId", skip_serializing_if = "Option::is_none")]
    pub pg_dispute_id: Option<String>,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "resolvedAt", skip_serializing_if = "Option::is_none")]
    pub resolved_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl Dispute {
    /// 분쟁 내역
    pub fn new(
        status: models::DisputeStatus,
        reason: String,
        created_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> Dispute {
        Dispute {
            status,
            pg_dispute_id: None,
            reason,
            created_at,
            resolved_at: None,
        }
    }
}
