/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadB2bTaxInvoicesSheetBody {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::GetB2bTaxInvoicesBodyFilter>>,
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<models::TaxInvoicesSheetField>>,
    #[serde(rename = "test", skip_serializing_if = "Option::is_none")]
    pub test: Option<bool>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<models::B2bTaxInvoiceSortInput>>,
}

impl DownloadB2bTaxInvoicesSheetBody {
    pub fn new() -> DownloadB2bTaxInvoicesSheetBody {
        DownloadB2bTaxInvoicesSheetBody {
            filter: None,
            fields: None,
            test: None,
            sort: None,
        }
    }
}
