/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// EasyPayProvider : 간편 결제사
/// 간편 결제사
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum EasyPayProvider {
    #[serde(rename = "SAMSUNGPAY")]
    #[default]
    Samsungpay,
    #[serde(rename = "KAKAOPAY")]
    Kakaopay,
    #[serde(rename = "NAVERPAY")]
    Naverpay,
    #[serde(rename = "PAYCO")]
    Payco,
    #[serde(rename = "SSGPAY")]
    Ssgpay,
    #[serde(rename = "CHAI")]
    Chai,
    #[serde(rename = "LPAY")]
    Lpay,
    #[serde(rename = "KPAY")]
    Kpay,
    #[serde(rename = "TOSSPAY")]
    Tosspay,
    #[serde(rename = "LGPAY")]
    Lgpay,
    #[serde(rename = "PINPAY")]
    Pinpay,
    #[serde(rename = "APPLEPAY")]
    Applepay,
    #[serde(rename = "SKPAY")]
    Skpay,
    #[serde(rename = "TOSS_BRANDPAY")]
    TossBrandpay,
    #[serde(rename = "KB_APP")]
    KbApp,
    #[serde(rename = "ALIPAY")]
    Alipay,
    #[serde(rename = "HYPHEN")]
    Hyphen,
    #[serde(rename = "TMONEY")]
    Tmoney,
    #[serde(rename = "PAYPAL")]
    Paypal,
    #[serde(rename = "SMILEPAY")]
    Smilepay,
    #[serde(rename = "MIR")]
    Mir,
    #[serde(rename = "WECHAT")]
    Wechat,
    #[serde(rename = "LINEPAY")]
    Linepay,
    #[serde(rename = "KLARNA")]
    Klarna,
    #[serde(rename = "GRABPAY")]
    Grabpay,
    #[serde(rename = "SHOPEEPAY")]
    Shopeepay,
    #[serde(rename = "JKOPAY")]
    Jkopay,
    #[serde(rename = "PAYPAY")]
    Paypay,
    #[serde(rename = "AMAZONPAY")]
    Amazonpay,
    #[serde(rename = "RAKUTENPAY")]
    Rakutenpay,
    #[serde(rename = "DBARAI")]
    Dbarai,
    #[serde(rename = "AUPAY")]
    Aupay,
    #[serde(rename = "MERPAY")]
    Merpay,
    #[serde(rename = "MONEYTREE")]
    Moneytree,
    #[serde(rename = "KPLUS")]
    Kplus,
    #[serde(rename = "TINABA")]
    Tinaba,
    #[serde(rename = "BILL_EASE")]
    BillEase,
    #[serde(rename = "KREDIVO")]
    Kredivo,
    #[serde(rename = "RABBIT_LINE_PAY")]
    RabbitLinePay,
    #[serde(rename = "ALIPAY_HK")]
    AlipayHk,
    #[serde(rename = "AKULAKU_PAY_LATER")]
    AkulakuPayLater,
    #[serde(rename = "BOOST")]
    Boost,
    #[serde(rename = "BPI")]
    Bpi,
    #[serde(rename = "DANA")]
    Dana,
    #[serde(rename = "G_CASH")]
    GCash,
    #[serde(rename = "HIPAY")]
    Hipay,
    #[serde(rename = "MPAY")]
    Mpay,
    #[serde(rename = "TOUCH_N_GO")]
    TouchNGo,
    #[serde(rename = "TRUE_MONEY")]
    TrueMoney,
    #[serde(rename = "DOKU_WALLET")]
    DokuWallet,
    #[serde(rename = "JENIUS_PAY")]
    JeniusPay,
    #[serde(rename = "OVO")]
    Ovo,
    #[serde(rename = "MAYA")]
    Maya,
    #[serde(rename = "QRIS")]
    Qris,
    #[serde(rename = "THAI_QR")]
    ThaiQr,
    #[serde(rename = "GOOGLE_PAY")]
    GooglePay,
}

impl std::fmt::Display for EasyPayProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Samsungpay => write!(f, "SAMSUNGPAY"),
            Self::Kakaopay => write!(f, "KAKAOPAY"),
            Self::Naverpay => write!(f, "NAVERPAY"),
            Self::Payco => write!(f, "PAYCO"),
            Self::Ssgpay => write!(f, "SSGPAY"),
            Self::Chai => write!(f, "CHAI"),
            Self::Lpay => write!(f, "LPAY"),
            Self::Kpay => write!(f, "KPAY"),
            Self::Tosspay => write!(f, "TOSSPAY"),
            Self::Lgpay => write!(f, "LGPAY"),
            Self::Pinpay => write!(f, "PINPAY"),
            Self::Applepay => write!(f, "APPLEPAY"),
            Self::Skpay => write!(f, "SKPAY"),
            Self::TossBrandpay => write!(f, "TOSS_BRANDPAY"),
            Self::KbApp => write!(f, "KB_APP"),
            Self::Alipay => write!(f, "ALIPAY"),
            Self::Hyphen => write!(f, "HYPHEN"),
            Self::Tmoney => write!(f, "TMONEY"),
            Self::Paypal => write!(f, "PAYPAL"),
            Self::Smilepay => write!(f, "SMILEPAY"),
            Self::Mir => write!(f, "MIR"),
            Self::Wechat => write!(f, "WECHAT"),
            Self::Linepay => write!(f, "LINEPAY"),
            Self::Klarna => write!(f, "KLARNA"),
            Self::Grabpay => write!(f, "GRABPAY"),
            Self::Shopeepay => write!(f, "SHOPEEPAY"),
            Self::Jkopay => write!(f, "JKOPAY"),
            Self::Paypay => write!(f, "PAYPAY"),
            Self::Amazonpay => write!(f, "AMAZONPAY"),
            Self::Rakutenpay => write!(f, "RAKUTENPAY"),
            Self::Dbarai => write!(f, "DBARAI"),
            Self::Aupay => write!(f, "AUPAY"),
            Self::Merpay => write!(f, "MERPAY"),
            Self::Moneytree => write!(f, "MONEYTREE"),
            Self::Kplus => write!(f, "KPLUS"),
            Self::Tinaba => write!(f, "TINABA"),
            Self::BillEase => write!(f, "BILL_EASE"),
            Self::Kredivo => write!(f, "KREDIVO"),
            Self::RabbitLinePay => write!(f, "RABBIT_LINE_PAY"),
            Self::AlipayHk => write!(f, "ALIPAY_HK"),
            Self::AkulakuPayLater => write!(f, "AKULAKU_PAY_LATER"),
            Self::Boost => write!(f, "BOOST"),
            Self::Bpi => write!(f, "BPI"),
            Self::Dana => write!(f, "DANA"),
            Self::GCash => write!(f, "G_CASH"),
            Self::Hipay => write!(f, "HIPAY"),
            Self::Mpay => write!(f, "MPAY"),
            Self::TouchNGo => write!(f, "TOUCH_N_GO"),
            Self::TrueMoney => write!(f, "TRUE_MONEY"),
            Self::DokuWallet => write!(f, "DOKU_WALLET"),
            Self::JeniusPay => write!(f, "JENIUS_PAY"),
            Self::Ovo => write!(f, "OVO"),
            Self::Maya => write!(f, "MAYA"),
            Self::Qris => write!(f, "QRIS"),
            Self::ThaiQr => write!(f, "THAI_QR"),
            Self::GooglePay => write!(f, "GOOGLE_PAY"),
        }
    }
}
