/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// EvaluateCheckoutProfileResponse : 체크아웃 프로필 평가 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvaluateCheckoutProfileResponse {
    #[serde(rename = "methods", skip_serializing_if = "Option::is_none")]
    pub methods: Option<Box<Vec<models::EvaluatedCheckoutMethod>>>,
}

impl EvaluateCheckoutProfileResponse {
    /// 체크아웃 프로필 평가 성공 응답
    pub fn new() -> EvaluateCheckoutProfileResponse {
        EvaluateCheckoutProfileResponse { methods: None }
    }
}
