/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// FailedPgBillingKeyIssueResponse : 빌링키 발급 실패 채널 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FailedPgBillingKeyIssueResponse {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "channel")]
    pub channel: Box<models::SelectedChannel>,
    #[serde(rename = "failure")]
    pub failure: Box<models::BillingKeyFailure>,
}

impl FailedPgBillingKeyIssueResponse {
    /// 빌링키 발급 실패 채널 응답
    pub fn new(
        r#type: String,
        channel: models::SelectedChannel,
        failure: models::BillingKeyFailure,
    ) -> FailedPgBillingKeyIssueResponse {
        FailedPgBillingKeyIssueResponse {
            r#type,
            channel: Box::new(channel),
            failure: Box::new(failure),
        }
    }
}
