/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// FailedPaymentCancellation : 취소 실패 상태
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FailedPaymentCancellation {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "pgCancellationId", skip_serializing_if = "Option::is_none")]
    pub pg_cancellation_id: Option<String>,
    #[serde(rename = "totalAmount")]
    pub total_amount: i64,
    #[serde(rename = "taxFreeAmount")]
    pub tax_free_amount: i64,
    #[serde(rename = "vatAmount")]
    pub vat_amount: i64,
    #[serde(
        rename = "easyPayDiscountAmount",
        skip_serializing_if = "Option::is_none"
    )]
    pub easy_pay_discount_amount: Option<i64>,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "cancelledAt", skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "requestedAt")]
    pub requested_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "trigger", skip_serializing_if = "Option::is_none")]
    pub trigger: Option<models::Trigger>,
}

impl FailedPaymentCancellation {
    /// 취소 실패 상태
    pub fn new(
        status: String,
        id: String,
        total_amount: i64,
        tax_free_amount: i64,
        vat_amount: i64,
        reason: String,
        requested_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> FailedPaymentCancellation {
        FailedPaymentCancellation {
            status,
            id,
            pg_cancellation_id: None,
            total_amount,
            tax_free_amount,
            vat_amount,
            easy_pay_discount_amount: None,
            reason,
            cancelled_at: None,
            requested_at,
            trigger: None,
        }
    }
}
