/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetBankInfosResponse : 은행 정보 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBankInfosResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::BankInfo>,
}

impl GetBankInfosResponse {
    /// 은행 정보 조회 성공 응답 정보
    pub fn new(items: Vec<models::BankInfo>) -> GetBankInfosResponse {
        GetBankInfosResponse { items }
    }
}
