/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum GetPaymentSessionError {
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "SESSION_EXPIRED")]
    SessionExpired(Box<models::SessionExpiredError>),
    #[serde(rename = "SESSION_NOT_FOUND")]
    SessionNotFound(Box<models::SessionNotFoundError>),
}

impl Default for GetPaymentSessionError {
    fn default() -> Self {
        Self::InvalidRequest(Default::default())
    }
}
