/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetB2bTaxInvoicesBodyFilter : 세금계산서 다건 조회 필터
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetB2bTaxInvoicesBodyFilter {
    #[serde(rename = "primaryFilter", skip_serializing_if = "Option::is_none")]
    pub primary_filter: Option<Box<models::GetB2bTaxInvoicesBodyPrimaryFilter>>,
    #[serde(rename = "supplierBrn", skip_serializing_if = "Option::is_none")]
    pub supplier_brn: Option<String>,
    /// 역발행의 경우 공급자 사업자등록번호, 정발행의 경우 공급받는자 사업자등록번호에 대해 조회합니다.
    #[serde(rename = "partnerBrn", skip_serializing_if = "Option::is_none")]
    pub partner_brn: Option<String>,
    /// 미입력시 모든 상태를 조회합니다.
    #[serde(rename = "statuses", skip_serializing_if = "Option::is_none")]
    pub statuses: Option<Vec<models::B2bTaxInvoiceStatus>>,
    #[serde(rename = "taxationTypes", skip_serializing_if = "Option::is_none")]
    pub taxation_types: Option<Vec<models::B2bTaxInvoiceTaxationType>>,
    #[serde(
        rename = "documentModificationTypes",
        skip_serializing_if = "Option::is_none"
    )]
    pub document_modification_types: Option<Vec<models::B2bTaxInvoiceDocumentModificationType>>,
    #[serde(rename = "isDelayed", skip_serializing_if = "Option::is_none")]
    pub is_delayed: Option<bool>,
    #[serde(rename = "issuanceTypes", skip_serializing_if = "Option::is_none")]
    pub issuance_types: Option<Vec<models::B2bTaxInvoiceIssuanceType>>,
    #[serde(rename = "purposeTypes", skip_serializing_if = "Option::is_none")]
    pub purpose_types: Option<Vec<models::B2bTaxInvoicePurposeType>>,
    /// 거래처 ID로 필터링합니다. 공급자 또는 공급받는자 거래처 ID에 대해 조회합니다.
    #[serde(rename = "counterpartyId", skip_serializing_if = "Option::is_none")]
    pub counterparty_id: Option<String>,
    /// counterpartyId 조건과 함께 거래처의 사업자등록번호 매칭 조건을 추가할지 여부입니다.
    #[serde(rename = "includeBrnMatch", skip_serializing_if = "Option::is_none")]
    pub include_brn_match: Option<bool>,
}

impl GetB2bTaxInvoicesBodyFilter {
    /// 세금계산서 다건 조회 필터
    pub fn new() -> GetB2bTaxInvoicesBodyFilter {
        GetB2bTaxInvoicesBodyFilter {
            primary_filter: None,
            supplier_brn: None,
            partner_brn: None,
            statuses: None,
            taxation_types: None,
            document_modification_types: None,
            is_delayed: None,
            issuance_types: None,
            purpose_types: None,
            counterparty_id: None,
            include_brn_match: None,
        }
    }
}
