/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetIdentityVerificationsResponse : 본인인증 내역 다건 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetIdentityVerificationsResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::IdentityVerification>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
}

impl GetIdentityVerificationsResponse {
    /// 본인인증 내역 다건 조회 성공 응답 정보
    pub fn new(
        items: Vec<models::IdentityVerification>,
        page: models::PageInfo,
    ) -> GetIdentityVerificationsResponse {
        GetIdentityVerificationsResponse {
            items,
            page: Box::new(page),
        }
    }
}
