/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformPayoutsResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::PlatformPayout>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
    #[serde(rename = "counts")]
    pub counts: Box<models::PlatformPayoutStatusStats>,
}

impl GetPlatformPayoutsResponse {
    pub fn new(
        items: Vec<models::PlatformPayout>,
        page: models::PageInfo,
        counts: models::PlatformPayoutStatusStats,
    ) -> GetPlatformPayoutsResponse {
        GetPlatformPayoutsResponse {
            items,
            page: Box::new(page),
            counts: Box::new(counts),
        }
    }
}
