/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPaymentReconciliationTransactionVatReportResponse {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Box<Vec<models::PaymentReconciliationVatReportItem>>>,
    #[serde(rename = "summary")]
    pub summary: Box<models::PaymentReconciliationVatReportSummary>,
    #[serde(rename = "pgSpecifiers", skip_serializing_if = "Option::is_none")]
    pub pg_specifiers: Option<Box<Vec<models::ReconciliationPgSpecifier>>>,
}

impl GetPaymentReconciliationTransactionVatReportResponse {
    pub fn new(
        summary: models::PaymentReconciliationVatReportSummary,
    ) -> GetPaymentReconciliationTransactionVatReportResponse {
        GetPaymentReconciliationTransactionVatReportResponse {
            items: None,
            summary: Box::new(summary),
            pg_specifiers: None,
        }
    }
}
