/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetB2bTaxInvoicesResponse : 세금계산서 다건 조회 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetB2bTaxInvoicesResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::B2bTaxInvoiceSummary>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
}

impl GetB2bTaxInvoicesResponse {
    /// 세금계산서 다건 조회 성공 응답
    pub fn new(
        items: Vec<models::B2bTaxInvoiceSummary>,
        page: models::PageInfo,
    ) -> GetB2bTaxInvoicesResponse {
        GetB2bTaxInvoicesResponse {
            items,
            page: Box::new(page),
        }
    }
}
