/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetAllPaymentEventsByCursorResponse : 결제 이벤트 커서 기반 대용량 다건 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllPaymentEventsByCursorResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::PaymentEventWithCursor>,
}

impl GetAllPaymentEventsByCursorResponse {
    /// 결제 이벤트 커서 기반 대용량 다건 조회 성공 응답 정보
    pub fn new(items: Vec<models::PaymentEventWithCursor>) -> GetAllPaymentEventsByCursorResponse {
        GetAllPaymentEventsByCursorResponse { items }
    }
}
