/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformTransferSummariesResponse {
    #[serde(rename = "transferSummaries")]
    pub transfer_summaries: Vec<models::PlatformTransferSummary>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
}

impl GetPlatformTransferSummariesResponse {
    pub fn new(
        transfer_summaries: Vec<models::PlatformTransferSummary>,
        page: models::PageInfo,
    ) -> GetPlatformTransferSummariesResponse {
        GetPlatformTransferSummariesResponse {
            transfer_summaries,
            page: Box::new(page),
        }
    }
}
