/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetPgCardPromotionsResponse : PG사 카드 프로모션 조회 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPgCardPromotionsResponse {
    #[serde(rename = "promotions", skip_serializing_if = "Option::is_none")]
    pub promotions: Option<Box<Vec<models::PgCardPromotion>>>,
}

impl GetPgCardPromotionsResponse {
    /// PG사 카드 프로모션 조회 응답
    pub fn new() -> GetPgCardPromotionsResponse {
        GetPgCardPromotionsResponse { promotions: None }
    }
}
