/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformBulkPayoutsResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::PlatformBulkPayout>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
    #[serde(rename = "counts")]
    pub counts: Box<models::PlatformBulkPayoutStatusStats>,
}

impl GetPlatformBulkPayoutsResponse {
    pub fn new(
        items: Vec<models::PlatformBulkPayout>,
        page: models::PageInfo,
        counts: models::PlatformBulkPayoutStatusStats,
    ) -> GetPlatformBulkPayoutsResponse {
        GetPlatformBulkPayoutsResponse {
            items,
            page: Box::new(page),
            counts: Box::new(counts),
        }
    }
}
