/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetPaymentSchedulesBody : 결제 예약 다건 조회를 위한 입력 정보  조회 결과는 결제 예정 시점(timeToPay) 기준 최신 순으로 정렬됩니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPaymentSchedulesBody {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::PageInput>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<models::PaymentScheduleSortInput>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::PaymentScheduleFilterInput>>,
}

impl GetPaymentSchedulesBody {
    /// 결제 예약 다건 조회를 위한 입력 정보  조회 결과는 결제 예정 시점(timeToPay) 기준 최신 순으로 정렬됩니다.
    pub fn new() -> GetPaymentSchedulesBody {
        GetPaymentSchedulesBody {
            page: None,
            sort: None,
            filter: None,
        }
    }
}
