/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetB2bCounterpartiesBody : 거래처 검색 요청 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetB2bCounterpartiesBody {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::PageInput>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::B2bCounterpartyFilter>>,
}

impl GetB2bCounterpartiesBody {
    /// 거래처 검색 요청 정보
    pub fn new() -> GetB2bCounterpartiesBody {
        GetB2bCounterpartiesBody {
            page: None,
            filter: None,
        }
    }
}
