/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetPlatformAdditionalFeePoliciesResponse : 추가 수수료 정책 다건 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformAdditionalFeePoliciesResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::PlatformAdditionalFeePolicy>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
}

impl GetPlatformAdditionalFeePoliciesResponse {
    /// 추가 수수료 정책 다건 조회 성공 응답 정보
    pub fn new(
        items: Vec<models::PlatformAdditionalFeePolicy>,
        page: models::PageInfo,
    ) -> GetPlatformAdditionalFeePoliciesResponse {
        GetPlatformAdditionalFeePoliciesResponse {
            items,
            page: Box::new(page),
        }
    }
}
