/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetPlatformTransferSummariesBody : 정산건 요약 다건 조회를 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformTransferSummariesBody {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::PageInput>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::PlatformTransferFilterInput>>,
}

impl GetPlatformTransferSummariesBody {
    /// 정산건 요약 다건 조회를 위한 입력 정보
    pub fn new() -> GetPlatformTransferSummariesBody {
        GetPlatformTransferSummariesBody {
            page: None,
            filter: None,
        }
    }
}
