/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// GetB2bBusinessInfosBody : 사업자등록 정보 조회를 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetB2bBusinessInfosBody {
    #[serde(rename = "brnList")]
    pub brn_list: Vec<String>,
}

impl GetB2bBusinessInfosBody {
    /// 사업자등록 정보 조회를 위한 입력 정보
    pub fn new(brn_list: Vec<String>) -> GetB2bBusinessInfosBody {
        GetB2bBusinessInfosBody { brn_list }
    }
}
