/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetPlatformPartnerSettlementsResponse : 정산내역 다건 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformPartnerSettlementsResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::PlatformPartnerSettlement>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
    #[serde(rename = "counts")]
    pub counts: Box<models::PlatformPartnerSettlementStatusStats>,
}

impl GetPlatformPartnerSettlementsResponse {
    /// 정산내역 다건 조회 성공 응답 정보
    pub fn new(
        items: Vec<models::PlatformPartnerSettlement>,
        page: models::PageInfo,
        counts: models::PlatformPartnerSettlementStatusStats,
    ) -> GetPlatformPartnerSettlementsResponse {
        GetPlatformPartnerSettlementsResponse {
            items,
            page: Box::new(page),
            counts: Box::new(counts),
        }
    }
}
