/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetB2bTaxInvoiceAttachmentsResponse : 세금계산서 첨부파일 목록 조회 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetB2bTaxInvoiceAttachmentsResponse {
    #[serde(rename = "attachments")]
    pub attachments: Vec<models::B2bTaxInvoiceAttachment>,
}

impl GetB2bTaxInvoiceAttachmentsResponse {
    /// 세금계산서 첨부파일 목록 조회 성공 응답
    pub fn new(
        attachments: Vec<models::B2bTaxInvoiceAttachment>,
    ) -> GetB2bTaxInvoiceAttachmentsResponse {
        GetB2bTaxInvoiceAttachmentsResponse { attachments }
    }
}
