/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetB2bCounterpartiesResponse : 거래처 검색 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetB2bCounterpartiesResponse {
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
    #[serde(rename = "items")]
    pub items: Vec<models::B2bCounterparty>,
}

impl GetB2bCounterpartiesResponse {
    /// 거래처 검색 성공 응답
    pub fn new(
        page: models::PageInfo,
        items: Vec<models::B2bCounterparty>,
    ) -> GetB2bCounterpartiesResponse {
        GetB2bCounterpartiesResponse {
            page: Box::new(page),
            items,
        }
    }
}
