/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetBillingKeyInfosResponse : 빌링키 다건 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBillingKeyInfosResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::BillingKeyInfo>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
}

impl GetBillingKeyInfosResponse {
    /// 빌링키 다건 조회 성공 응답 정보
    pub fn new(
        items: Vec<models::BillingKeyInfo>,
        page: models::PageInfo,
    ) -> GetBillingKeyInfosResponse {
        GetBillingKeyInfosResponse {
            items,
            page: Box::new(page),
        }
    }
}
