/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetPlatformContractsResponse : 계약 다건 조회 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformContractsResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::PlatformContract>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
}

impl GetPlatformContractsResponse {
    /// 계약 다건 조회 성공 응답
    pub fn new(
        items: Vec<models::PlatformContract>,
        page: models::PageInfo,
    ) -> GetPlatformContractsResponse {
        GetPlatformContractsResponse {
            items,
            page: Box::new(page),
        }
    }
}
