/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetPlatformDiscountSharePoliciesResponse : 할인 분담 정책 다건 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPlatformDiscountSharePoliciesResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::PlatformDiscountSharePolicy>,
    #[serde(rename = "page")]
    pub page: Box<models::PageInfo>,
}

impl GetPlatformDiscountSharePoliciesResponse {
    /// 할인 분담 정책 다건 조회 성공 응답 정보
    pub fn new(
        items: Vec<models::PlatformDiscountSharePolicy>,
        page: models::PageInfo,
    ) -> GetPlatformDiscountSharePoliciesResponse {
        GetPlatformDiscountSharePoliciesResponse {
            items,
            page: Box::new(page),
        }
    }
}
