/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetB2bBusinessInfosResponse : 사업자등록 정보 조회 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetB2bBusinessInfosResponse {
    #[serde(rename = "result")]
    pub result: Vec<models::B2bBusinessInfoResult>,
}

impl GetB2bBusinessInfosResponse {
    /// 사업자등록 정보 조회 성공 응답
    pub fn new(result: Vec<models::B2bBusinessInfoResult>) -> GetB2bBusinessInfosResponse {
        GetB2bBusinessInfosResponse { result }
    }
}
