/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// GetB2bTaxInvoicesBody : 세금 계산서 다건 조회를 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetB2bTaxInvoicesBody {
    /// true 이면 테스트 모드로 실행되며, false 이거나 주어지지 않은 경우 테스트 모드를 사용하지 않습니다.
    #[serde(rename = "test", skip_serializing_if = "Option::is_none")]
    pub test: Option<bool>,
    /// 0부터 시작하는 페이지 번호. 기본 값은 0.
    #[serde(rename = "pageNumber", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
    /// 각 페이지 당 포함할 객체 수. 기본 값은 500이며 최대 1000까지 요청가능합니다.
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::GetB2bTaxInvoicesBodyFilter>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Box<models::B2bTaxInvoiceSortInput>>,
}

impl GetB2bTaxInvoicesBody {
    /// 세금 계산서 다건 조회를 위한 입력 정보
    pub fn new() -> GetB2bTaxInvoicesBody {
        GetB2bTaxInvoicesBody {
            test: None,
            page_number: None,
            page_size: None,
            filter: None,
            sort: None,
        }
    }
}
