/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// GetB2bTaxInvoicePopupUrlResponse : 세금계산서 팝업 URL 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetB2bTaxInvoicePopupUrlResponse {
    #[serde(rename = "url")]
    pub url: String,
}

impl GetB2bTaxInvoicePopupUrlResponse {
    /// 세금계산서 팝업 URL 성공 응답
    pub fn new(url: String) -> GetB2bTaxInvoicePopupUrlResponse {
        GetB2bTaxInvoicePopupUrlResponse { url }
    }
}
