/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// IdentityVerificationVerifiedCustomer : 인증된 고객 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentityVerificationVerifiedCustomer {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<models::IdentityVerificationOperator>,
    /// 특수 문자(-) 없이 숫자로만 이루어진 번호 형식입니다. 다날: 별도 계약이 필요합니다. KG이니시스: 항상 제공합니다.
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// 포트원 V2 본인인증 건의 경우 항상 존재합니다.
    #[serde(rename = "birthDate", skip_serializing_if = "Option::is_none")]
    pub birth_date: Option<chrono::NaiveDate>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<models::Gender>,
    /// 다날: 별도 계약이 필요합니다. KG이니시스: 항상 제공합니다.
    #[serde(rename = "isForeigner", skip_serializing_if = "Option::is_none")]
    pub is_foreigner: Option<bool>,
    /// 개인을 식별하기 위한 고유 정보입니다. 다날: 항상 제공합니다. KG이니시스: 카카오를 제외한 인증사에서 제공합니다.
    #[serde(rename = "ci", skip_serializing_if = "Option::is_none")]
    pub ci: Option<String>,
    /// 중복 가입을 방지하기 위해 개인을 식별하는 사이트별 고유 정보입니다. 다날: 항상 제공합니다. KG이니시스: 제공하지 않습니다.
    #[serde(rename = "di", skip_serializing_if = "Option::is_none")]
    pub di: Option<String>,
}

impl IdentityVerificationVerifiedCustomer {
    /// 인증된 고객 정보
    pub fn new(name: String) -> IdentityVerificationVerifiedCustomer {
        IdentityVerificationVerifiedCustomer {
            id: None,
            name,
            operator: None,
            phone_number: None,
            birth_date: None,
            gender: None,
            is_foreigner: None,
            ci: None,
            di: None,
        }
    }
}
