/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// IdentityVerificationStatus : 본인인증 상태
/// 본인인증 상태
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum IdentityVerificationStatus {
    #[serde(rename = "READY")]
    #[default]
    Ready,
    #[serde(rename = "VERIFIED")]
    Verified,
    #[serde(rename = "FAILED")]
    Failed,
}

impl std::fmt::Display for IdentityVerificationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ready => write!(f, "READY"),
            Self::Verified => write!(f, "VERIFIED"),
            Self::Failed => write!(f, "FAILED"),
        }
    }
}
