/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// IdentityVerificationMethod : 본인인증 방식
/// 본인인증 방식
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum IdentityVerificationMethod {
    #[serde(rename = "SMS")]
    #[default]
    Sms,
    #[serde(rename = "APP")]
    App,
}

impl std::fmt::Display for IdentityVerificationMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sms => write!(f, "SMS"),
            Self::App => write!(f, "APP"),
        }
    }
}
