/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// IdentityVerificationSortBy : 본인인증 내역 정렬 기준
/// 본인인증 내역 정렬 기준
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum IdentityVerificationSortBy {
    #[serde(rename = "REQUESTED_AT")]
    #[default]
    RequestedAt,
    #[serde(rename = "VERIFIED_AT")]
    VerifiedAt,
    #[serde(rename = "FAILED_AT")]
    FailedAt,
    #[serde(rename = "STATUS_UPDATED_AT")]
    StatusUpdatedAt,
}

impl std::fmt::Display for IdentityVerificationSortBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RequestedAt => write!(f, "REQUESTED_AT"),
            Self::VerifiedAt => write!(f, "VERIFIED_AT"),
            Self::FailedAt => write!(f, "FAILED_AT"),
            Self::StatusUpdatedAt => write!(f, "STATUS_UPDATED_AT"),
        }
    }
}
