/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// InstantBillingKeyPaymentMethodInput : 빌링키 발급 시 결제 수단 입력 양식  `card`를 반드시 입력해 주세요.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstantBillingKeyPaymentMethodInput {
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<Box<models::InstantBillingKeyPaymentMethodInputCard>>,
}

impl InstantBillingKeyPaymentMethodInput {
    /// 빌링키 발급 시 결제 수단 입력 양식  `card`를 반드시 입력해 주세요.
    pub fn new() -> InstantBillingKeyPaymentMethodInput {
        InstantBillingKeyPaymentMethodInput { card: None }
    }
}
