/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// InstantPaymentMethodInput : 수기 결제 수단 입력 정보  하나의 필드만 입력합니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstantPaymentMethodInput {
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<Box<models::InstantPaymentMethodInputCard>>,
    #[serde(rename = "virtualAccount", skip_serializing_if = "Option::is_none")]
    pub virtual_account: Option<Box<models::InstantPaymentMethodInputVirtualAccount>>,
}

impl InstantPaymentMethodInput {
    /// 수기 결제 수단 입력 정보  하나의 필드만 입력합니다.
    pub fn new() -> InstantPaymentMethodInput {
        InstantPaymentMethodInput {
            card: None,
            virtual_account: None,
        }
    }
}
