/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// InstantBillingKeyPaymentMethodInputCard : 카드 수단 정보 입력 양식
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstantBillingKeyPaymentMethodInputCard {
    #[serde(rename = "credential")]
    pub credential: Box<models::CardCredential>,
}

impl InstantBillingKeyPaymentMethodInputCard {
    /// 카드 수단 정보 입력 양식
    pub fn new(credential: models::CardCredential) -> InstantBillingKeyPaymentMethodInputCard {
        InstantBillingKeyPaymentMethodInputCard {
            credential: Box::new(credential),
        }
    }
}
