/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// InstantPaymentInput : 수기 결제 요청 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstantPaymentInput {
    /// 접근 권한이 있는 상점 아이디만 입력 가능하며, 미입력시 인증 정보의 상점 아이디를 사용합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    /// 채널 키 또는 채널 그룹 ID 필수
    #[serde(rename = "channelKey", skip_serializing_if = "Option::is_none")]
    pub channel_key: Option<String>,
    /// 채널 키 또는 채널 그룹 ID 필수
    #[serde(rename = "channelGroupId", skip_serializing_if = "Option::is_none")]
    pub channel_group_id: Option<String>,
    #[serde(rename = "method")]
    pub method: Box<models::InstantPaymentMethodInput>,
    #[serde(rename = "orderName")]
    pub order_name: String,
    /// 기본값은 false 입니다.
    #[serde(rename = "isCulturalExpense", skip_serializing_if = "Option::is_none")]
    pub is_cultural_expense: Option<bool>,
    /// 기본값은 false 입니다.
    #[serde(rename = "isEscrow", skip_serializing_if = "Option::is_none")]
    pub is_escrow: Option<bool>,
    #[serde(rename = "customer", skip_serializing_if = "Option::is_none")]
    pub customer: Option<Box<models::CustomerInput>>,
    #[serde(rename = "customData", skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<String>,
    #[serde(rename = "amount")]
    pub amount: Box<models::PaymentAmountInput>,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<models::Country>,
    /// 결제 웹훅 주소입니다. 상점에 설정되어 있는 값보다 우선적으로 적용됩니다. 빈 배열은 무시됩니다.
    #[serde(rename = "noticeUrls", skip_serializing_if = "Option::is_none")]
    pub notice_urls: Option<Vec<String>>,
    /// 입력된 값이 없을 경우에는 빈 배열로 해석됩니다.
    #[serde(rename = "products", skip_serializing_if = "Option::is_none")]
    pub products: Option<Vec<models::PaymentProduct>>,
    #[serde(rename = "productCount", skip_serializing_if = "Option::is_none")]
    pub product_count: Option<i32>,
    #[serde(rename = "productType", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<models::PaymentProductType>,
    #[serde(rename = "shippingAddress", skip_serializing_if = "Option::is_none")]
    pub shipping_address: Option<Box<models::SeparatedAddressInput>>,
    #[serde(rename = "promotionId", skip_serializing_if = "Option::is_none")]
    pub promotion_id: Option<String>,
    #[serde(rename = "bypass", skip_serializing_if = "Option::is_none")]
    pub bypass: Option<serde_json::Value>,
    /// 결제가 성공했을 때 웹훅을 전송하지 않으려면 true로 설정합니다. 가상계좌 입금 완료 등 외부 이벤트로 결제가 완료되는 경우 발생하는 웹훅은 스킵되지 않습니다.
    #[serde(rename = "skipWebhook", skip_serializing_if = "Option::is_none")]
    pub skip_webhook: Option<bool>,
}

impl InstantPaymentInput {
    /// 수기 결제 요청 정보
    pub fn new(
        method: models::InstantPaymentMethodInput,
        order_name: String,
        amount: models::PaymentAmountInput,
        currency: models::Currency,
    ) -> InstantPaymentInput {
        InstantPaymentInput {
            store_id: None,
            channel_key: None,
            channel_group_id: None,
            method: Box::new(method),
            order_name,
            is_cultural_expense: None,
            is_escrow: None,
            customer: None,
            custom_data: None,
            amount: Box::new(amount),
            currency,
            country: None,
            notice_urls: None,
            products: None,
            product_count: None,
            product_type: None,
            shipping_address: None,
            promotion_id: None,
            bypass: None,
            skip_webhook: None,
        }
    }
}
