/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// InstantPaymentMethodInputVirtualAccount : 가상계좌 수단 정보 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstantPaymentMethodInputVirtualAccount {
    #[serde(rename = "bank")]
    pub bank: models::Bank,
    #[serde(rename = "expiry")]
    pub expiry: Box<models::InstantPaymentMethodInputVirtualAccountExpiry>,
    #[serde(rename = "option")]
    pub option: Box<models::InstantPaymentMethodInputVirtualAccountOption>,
    #[serde(rename = "cashReceipt", skip_serializing_if = "Option::is_none")]
    pub cash_receipt: Option<Box<models::InstantPaymentMethodInputVirtualAccountCashReceiptInfo>>,
    #[serde(rename = "remitteeName", skip_serializing_if = "Option::is_none")]
    pub remittee_name: Option<String>,
}

impl InstantPaymentMethodInputVirtualAccount {
    /// 가상계좌 수단 정보 입력 정보
    pub fn new(
        bank: models::Bank,
        expiry: models::InstantPaymentMethodInputVirtualAccountExpiry,
        option: models::InstantPaymentMethodInputVirtualAccountOption,
    ) -> InstantPaymentMethodInputVirtualAccount {
        InstantPaymentMethodInputVirtualAccount {
            bank,
            expiry: Box::new(expiry),
            option: Box::new(option),
            cash_receipt: None,
            remittee_name: None,
        }
    }
}
