/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// InstantPaymentMethodInputVirtualAccountOption : 가상계좌 발급 방식
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstantPaymentMethodInputVirtualAccountOption {
    #[serde(rename = "type")]
    pub r#type: models::InstantPaymentMethodInputVirtualAccountOptionType,
    #[serde(rename = "fixed", skip_serializing_if = "Option::is_none")]
    pub fixed: Option<Box<models::InstantPaymentMethodInputVirtualAccountOptionFixed>>,
}

impl InstantPaymentMethodInputVirtualAccountOption {
    /// 가상계좌 발급 방식
    pub fn new(
        r#type: models::InstantPaymentMethodInputVirtualAccountOptionType,
    ) -> InstantPaymentMethodInputVirtualAccountOption {
        InstantPaymentMethodInputVirtualAccountOption {
            r#type,
            fixed: None,
        }
    }
}
