/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// InstantPaymentMethodInputVirtualAccountCashReceiptInfo : 가상계좌 결제 시 현금영수증 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstantPaymentMethodInputVirtualAccountCashReceiptInfo {
    #[serde(rename = "type")]
    pub r#type: models::CashReceiptInputType,
    #[serde(rename = "customerIdentityNumber")]
    pub customer_identity_number: String,
}

impl InstantPaymentMethodInputVirtualAccountCashReceiptInfo {
    /// 가상계좌 결제 시 현금영수증 정보
    pub fn new(
        r#type: models::CashReceiptInputType,
        customer_identity_number: String,
    ) -> InstantPaymentMethodInputVirtualAccountCashReceiptInfo {
        InstantPaymentMethodInputVirtualAccountCashReceiptInfo {
            r#type,
            customer_identity_number,
        }
    }
}
