/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// InvalidRequestError : 요청된 입력 정보가 유효하지 않은 경우  허가되지 않은 값, 올바르지 않은 형식의 요청 등이 모두 해당됩니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidRequestError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl InvalidRequestError {
    /// 요청된 입력 정보가 유효하지 않은 경우  허가되지 않은 값, 올바르지 않은 형식의 요청 등이 모두 해당됩니다.
    pub fn new(r#type: String) -> InvalidRequestError {
        InvalidRequestError {
            r#type,
            message: None,
        }
    }
}
