/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// IssueCashReceiptPaymentMethodType : 현금영수증 발급 가능 결제 수단
/// 현금영수증 발급 가능 결제 수단
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum IssueCashReceiptPaymentMethodType {
    #[serde(rename = "TRANSFER")]
    #[default]
    Transfer,
    #[serde(rename = "VIRTUAL_ACCOUNT")]
    VirtualAccount,
}

impl std::fmt::Display for IssueCashReceiptPaymentMethodType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Transfer => write!(f, "TRANSFER"),
            Self::VirtualAccount => write!(f, "VIRTUAL_ACCOUNT"),
        }
    }
}
