/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// IssueB2bTaxInvoiceImmediatelyBody : 세금계산서 즉시 정발행 요청 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueB2bTaxInvoiceImmediatelyBody {
    #[serde(rename = "taxInvoice")]
    pub tax_invoice: Box<models::B2bTaxInvoiceInput>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "modification", skip_serializing_if = "Option::is_none")]
    pub modification: Option<Box<models::B2bTaxInvoiceModificationCreateBody>>,
    /// true인 경우 공급받는자 정보로 거래처를 자동 생성합니다.
    #[serde(
        rename = "createRecipientCounterparty",
        skip_serializing_if = "Option::is_none"
    )]
    pub create_recipient_counterparty: Option<bool>,
}

impl IssueB2bTaxInvoiceImmediatelyBody {
    /// 세금계산서 즉시 정발행 요청 정보
    pub fn new(tax_invoice: models::B2bTaxInvoiceInput) -> IssueB2bTaxInvoiceImmediatelyBody {
        IssueB2bTaxInvoiceImmediatelyBody {
            tax_invoice: Box::new(tax_invoice),
            memo: None,
            modification: None,
            create_recipient_counterparty: None,
        }
    }
}
