/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// IssuedBillingKeyInfo : 빌링키 발급 완료 상태 건
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuedBillingKeyInfo {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "billingKey")]
    pub billing_key: String,
    #[serde(rename = "merchantId")]
    pub merchant_id: String,
    #[serde(rename = "storeId")]
    pub store_id: String,
    /// 추후 슈퍼빌링키 기능 제공 시 여러 결제수단 정보가 담길 수 있습니다.
    #[serde(rename = "methods", skip_serializing_if = "Option::is_none")]
    pub methods: Option<Vec<models::BillingKeyPaymentMethod>>,
    /// 추후 슈퍼빌링키 기능 제공 시 여러 채널 정보가 담길 수 있습니다.
    #[serde(rename = "channels")]
    pub channels: Vec<models::SelectedChannel>,
    #[serde(rename = "customer")]
    pub customer: Box<models::Customer>,
    #[serde(rename = "customData", skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<String>,
    #[serde(rename = "issueId", skip_serializing_if = "Option::is_none")]
    pub issue_id: Option<String>,
    #[serde(rename = "issueName", skip_serializing_if = "Option::is_none")]
    pub issue_name: Option<String>,
    #[serde(rename = "requestedAt", skip_serializing_if = "Option::is_none")]
    pub requested_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "issuedAt")]
    pub issued_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "channelGroup", skip_serializing_if = "Option::is_none")]
    pub channel_group: Option<Box<models::ChannelGroupSummary>>,
    /// 슈퍼빌링키의 경우, 빌링키 발급이 성공하더라도 일부 채널에 대한 빌링키 발급은 실패할 수 있습니다.
    #[serde(
        rename = "pgBillingKeyIssueResponses",
        skip_serializing_if = "Option::is_none"
    )]
    pub pg_billing_key_issue_responses: Option<Vec<models::PgBillingKeyIssueResponse>>,
}

impl IssuedBillingKeyInfo {
    /// 빌링키 발급 완료 상태 건
    pub fn new(
        status: String,
        billing_key: String,
        merchant_id: String,
        store_id: String,
        channels: Vec<models::SelectedChannel>,
        customer: models::Customer,
        issued_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> IssuedBillingKeyInfo {
        IssuedBillingKeyInfo {
            status,
            billing_key,
            merchant_id,
            store_id,
            methods: None,
            channels,
            customer: Box::new(customer),
            custom_data: None,
            issue_id: None,
            issue_name: None,
            requested_at: None,
            issued_at,
            channel_group: None,
            pg_billing_key_issue_responses: None,
        }
    }
}
