/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// IssueB2bTaxInvoiceResponse : 세금계산서 발행 승인 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueB2bTaxInvoiceResponse {
    #[serde(rename = "taxInvoice")]
    pub tax_invoice: Box<models::B2bTaxInvoice>,
}

impl IssueB2bTaxInvoiceResponse {
    /// 세금계산서 발행 승인 응답
    pub fn new(tax_invoice: models::B2bTaxInvoice) -> IssueB2bTaxInvoiceResponse {
        IssueB2bTaxInvoiceResponse {
            tax_invoice: Box::new(tax_invoice),
        }
    }
}
