/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// IssueCashReceiptCustomerInputIdentityNumberType : 현금영수증 발급 시 고객 식별 정보 유형
/// 현금영수증 발급 시 고객 식별 정보 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum IssueCashReceiptCustomerInputIdentityNumberType {
    #[serde(rename = "PHONE")]
    #[default]
    Phone,
    #[serde(rename = "CARD")]
    Card,
    #[serde(rename = "BUSINESS")]
    Business,
}

impl std::fmt::Display for IssueCashReceiptCustomerInputIdentityNumberType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Phone => write!(f, "PHONE"),
            Self::Card => write!(f, "CARD"),
            Self::Business => write!(f, "BUSINESS"),
        }
    }
}
