/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum IssueCashReceiptError {
    #[serde(rename = "CASH_RECEIPT_ALREADY_ISSUED")]
    CashReceiptAlreadyIssued(Box<models::CashReceiptAlreadyIssuedError>),
    #[serde(rename = "CHANNEL_NOT_FOUND")]
    ChannelNotFound(Box<models::ChannelNotFoundError>),
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PG_PROVIDER")]
    PgProvider(Box<models::PgProviderError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for IssueCashReceiptError {
    fn default() -> Self {
        Self::CashReceiptAlreadyIssued(Default::default())
    }
}
