/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// Locale : 결제 언어
/// 결제 언어
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Locale {
    #[serde(rename = "KO_KR")]
    #[default]
    KoKr,
    #[serde(rename = "EN_US")]
    EnUs,
    #[serde(rename = "ZH_CN")]
    ZhCn,
    #[serde(rename = "ZH_TW")]
    ZhTw,
    #[serde(rename = "JA_JP")]
    JaJp,
    #[serde(rename = "RU_RU")]
    RuRu,
    #[serde(rename = "TH_TH")]
    ThTh,
    #[serde(rename = "VI_VN")]
    ViVn,
}

impl std::fmt::Display for Locale {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::KoKr => write!(f, "KO_KR"),
            Self::EnUs => write!(f, "EN_US"),
            Self::ZhCn => write!(f, "ZH_CN"),
            Self::ZhTw => write!(f, "ZH_TW"),
            Self::JaJp => write!(f, "JA_JP"),
            Self::RuRu => write!(f, "RU_RU"),
            Self::ThTh => write!(f, "TH_TH"),
            Self::ViVn => write!(f, "VI_VN"),
        }
    }
}
