/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MaxCancelCountReachedError : 취소 시도 횟수가 초과된 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaxCancelCountReachedError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl MaxCancelCountReachedError {
    /// 취소 시도 횟수가 초과된 경우
    pub fn new(r#type: String) -> MaxCancelCountReachedError {
        MaxCancelCountReachedError {
            r#type,
            message: None,
        }
    }
}
