/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ModifyEscrowLogisticsBody : 에스크로 배송 정보 수정 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifyEscrowLogisticsBody {
    /// 접근 권한이 있는 상점 아이디만 입력 가능하며, 미입력시 인증 정보의 상점 아이디를 사용합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
    pub sender: Option<Box<models::PaymentEscrowSenderInput>>,
    #[serde(rename = "receiver", skip_serializing_if = "Option::is_none")]
    pub receiver: Option<Box<models::PaymentEscrowReceiverInput>>,
    #[serde(rename = "logistics")]
    pub logistics: Box<models::PaymentLogistics>,
    /// 에스크로 구매 확정 시 이메일로 알림을 보낼지 여부입니다.
    #[serde(rename = "sendEmail", skip_serializing_if = "Option::is_none")]
    pub send_email: Option<bool>,
    #[serde(rename = "products", skip_serializing_if = "Option::is_none")]
    pub products: Option<Vec<models::PaymentProduct>>,
}

impl ModifyEscrowLogisticsBody {
    /// 에스크로 배송 정보 수정 입력 정보
    pub fn new(logistics: models::PaymentLogistics) -> ModifyEscrowLogisticsBody {
        ModifyEscrowLogisticsBody {
            store_id: None,
            sender: None,
            receiver: None,
            logistics: Box::new(logistics),
            send_email: None,
            products: None,
        }
    }
}
