/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ModifyEscrowLogisticsResponse : 에스크로 배송 정보 수정 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifyEscrowLogisticsResponse {
    #[serde(rename = "invoiceNumber")]
    pub invoice_number: String,
    #[serde(rename = "sentAt")]
    pub sent_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "modifiedAt")]
    pub modified_at: chrono::DateTime<chrono::FixedOffset>,
}

impl ModifyEscrowLogisticsResponse {
    /// 에스크로 배송 정보 수정 성공 응답
    pub fn new(
        invoice_number: String,
        sent_at: chrono::DateTime<chrono::FixedOffset>,
        modified_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> ModifyEscrowLogisticsResponse {
        ModifyEscrowLogisticsResponse {
            invoice_number,
            sent_at,
            modified_at,
        }
    }
}
