/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MonthDay : 월 및 일자 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonthDay {
    #[serde(rename = "month")]
    pub month: i32,
    #[serde(rename = "day")]
    pub day: i32,
}

impl MonthDay {
    /// 월 및 일자 정보
    pub fn new(month: i32, day: i32) -> MonthDay {
        MonthDay { month, day }
    }
}
