/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// OneLineAddress : 한 줄 형식 주소  한 줄 형식 주소만 존재합니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OneLineAddress {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "oneLine")]
    pub one_line: String,
}

impl OneLineAddress {
    /// 한 줄 형식 주소  한 줄 형식 주소만 존재합니다.
    pub fn new(r#type: String, one_line: String) -> OneLineAddress {
        OneLineAddress { r#type, one_line }
    }
}
