/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PayWithBillingKeyError {
    #[serde(rename = "ALREADY_PAID")]
    AlreadyPaid(Box<models::AlreadyPaidError>),
    #[serde(rename = "BILLING_KEY_ALREADY_DELETED")]
    BillingKeyAlreadyDeleted(Box<models::BillingKeyAlreadyDeletedError>),
    #[serde(rename = "BILLING_KEY_NOT_FOUND")]
    BillingKeyNotFound(Box<models::BillingKeyNotFoundError>),
    #[serde(rename = "CHANNEL_NOT_FOUND")]
    ChannelNotFound(Box<models::ChannelNotFoundError>),
    #[serde(rename = "DISCOUNT_AMOUNT_EXCEEDS_TOTAL_AMOUNT")]
    DiscountAmountExceedsTotalAmount(Box<models::DiscountAmountExceedsTotalAmountError>),
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "MAX_TRANSACTION_COUNT_REACHED")]
    MaxTransactionCountReached(Box<models::MaxTransactionCountReachedError>),
    #[serde(rename = "PAYMENT_SCHEDULE_ALREADY_EXISTS")]
    PaymentScheduleAlreadyExists(Box<models::PaymentScheduleAlreadyExistsError>),
    #[serde(rename = "PG_PROVIDER")]
    PgProvider(Box<models::PgProviderError>),
    #[serde(rename = "PROMOTION_PAY_METHOD_DOES_NOT_MATCH")]
    PromotionPayMethodDoesNotMatch(Box<models::PromotionPayMethodDoesNotMatchError>),
    #[serde(rename = "SUM_OF_PARTS_EXCEEDS_TOTAL_AMOUNT")]
    SumOfPartsExceedsTotalAmount(Box<models::SumOfPartsExceedsTotalAmountError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for PayWithBillingKeyError {
    fn default() -> Self {
        Self::AlreadyPaid(Default::default())
    }
}
