/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentTextSearchField : 통합검색 항목
/// 통합검색 항목
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentTextSearchField {
    #[serde(rename = "ALL")]
    #[default]
    All,
    #[serde(rename = "PAYMENT_ID")]
    PaymentId,
    #[serde(rename = "TX_ID")]
    TxId,
    #[serde(rename = "SCHEDULE_ID")]
    ScheduleId,
    #[serde(rename = "FAIL_REASON")]
    FailReason,
    #[serde(rename = "CARD_ISSUER")]
    CardIssuer,
    #[serde(rename = "CARD_ACQUIRER")]
    CardAcquirer,
    #[serde(rename = "CARD_BIN")]
    CardBin,
    #[serde(rename = "CARD_NUMBER")]
    CardNumber,
    #[serde(rename = "CARD_APPROVAL_NUMBER")]
    CardApprovalNumber,
    #[serde(rename = "CARD_RECEIPT_NAME")]
    CardReceiptName,
    #[serde(rename = "CARD_INSTALLMENT")]
    CardInstallment,
    #[serde(rename = "TRANS_BANK")]
    TransBank,
    #[serde(rename = "VIRTUAL_ACCOUNT_HOLDER_NAME")]
    VirtualAccountHolderName,
    #[serde(rename = "VIRTUAL_ACCOUNT_BANK")]
    VirtualAccountBank,
    #[serde(rename = "VIRTUAL_ACCOUNT_NUMBER")]
    VirtualAccountNumber,
    #[serde(rename = "PG_MERCHANT_ID")]
    PgMerchantId,
    #[serde(rename = "PG_TX_ID")]
    PgTxId,
    #[serde(rename = "PG_RECEIPT_ID")]
    PgReceiptId,
    #[serde(rename = "RECEIPT_APPROVAL_NUMBER")]
    ReceiptApprovalNumber,
    #[serde(rename = "PG_CANCELLATION_ID")]
    PgCancellationId,
    #[serde(rename = "CANCEL_REASON")]
    CancelReason,
    #[serde(rename = "ORDER_NAME")]
    OrderName,
    #[serde(rename = "CUSTOMER_NAME")]
    CustomerName,
    #[serde(rename = "CUSTOMER_EMAIL")]
    CustomerEmail,
    #[serde(rename = "CUSTOMER_PHONE_NUMBER")]
    CustomerPhoneNumber,
    #[serde(rename = "CUSTOMER_ADDRESS")]
    CustomerAddress,
    #[serde(rename = "CUSTOMER_ZIPCODE")]
    CustomerZipcode,
    #[serde(rename = "USER_AGENT")]
    UserAgent,
    #[serde(rename = "BILLING_KEY")]
    BillingKey,
    #[serde(rename = "PROMOTION_ID")]
    PromotionId,
    #[serde(rename = "GIFT_CERTIFICATION_APPROVAL_NUMBER")]
    GiftCertificationApprovalNumber,
}

impl std::fmt::Display for PaymentTextSearchField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::All => write!(f, "ALL"),
            Self::PaymentId => write!(f, "PAYMENT_ID"),
            Self::TxId => write!(f, "TX_ID"),
            Self::ScheduleId => write!(f, "SCHEDULE_ID"),
            Self::FailReason => write!(f, "FAIL_REASON"),
            Self::CardIssuer => write!(f, "CARD_ISSUER"),
            Self::CardAcquirer => write!(f, "CARD_ACQUIRER"),
            Self::CardBin => write!(f, "CARD_BIN"),
            Self::CardNumber => write!(f, "CARD_NUMBER"),
            Self::CardApprovalNumber => write!(f, "CARD_APPROVAL_NUMBER"),
            Self::CardReceiptName => write!(f, "CARD_RECEIPT_NAME"),
            Self::CardInstallment => write!(f, "CARD_INSTALLMENT"),
            Self::TransBank => write!(f, "TRANS_BANK"),
            Self::VirtualAccountHolderName => write!(f, "VIRTUAL_ACCOUNT_HOLDER_NAME"),
            Self::VirtualAccountBank => write!(f, "VIRTUAL_ACCOUNT_BANK"),
            Self::VirtualAccountNumber => write!(f, "VIRTUAL_ACCOUNT_NUMBER"),
            Self::PgMerchantId => write!(f, "PG_MERCHANT_ID"),
            Self::PgTxId => write!(f, "PG_TX_ID"),
            Self::PgReceiptId => write!(f, "PG_RECEIPT_ID"),
            Self::ReceiptApprovalNumber => write!(f, "RECEIPT_APPROVAL_NUMBER"),
            Self::PgCancellationId => write!(f, "PG_CANCELLATION_ID"),
            Self::CancelReason => write!(f, "CANCEL_REASON"),
            Self::OrderName => write!(f, "ORDER_NAME"),
            Self::CustomerName => write!(f, "CUSTOMER_NAME"),
            Self::CustomerEmail => write!(f, "CUSTOMER_EMAIL"),
            Self::CustomerPhoneNumber => write!(f, "CUSTOMER_PHONE_NUMBER"),
            Self::CustomerAddress => write!(f, "CUSTOMER_ADDRESS"),
            Self::CustomerZipcode => write!(f, "CUSTOMER_ZIPCODE"),
            Self::UserAgent => write!(f, "USER_AGENT"),
            Self::BillingKey => write!(f, "BILLING_KEY"),
            Self::PromotionId => write!(f, "PROMOTION_ID"),
            Self::GiftCertificationApprovalNumber => {
                write!(f, "GIFT_CERTIFICATION_APPROVAL_NUMBER")
            }
        }
    }
}
