/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentLogistics : 배송정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentLogistics {
    #[serde(rename = "company")]
    pub company: models::PaymentLogisticsCompany,
    #[serde(rename = "invoiceNumber")]
    pub invoice_number: String,
    #[serde(rename = "sentAt")]
    pub sent_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "receivedAt", skip_serializing_if = "Option::is_none")]
    pub received_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::SeparatedAddressInput>>,
}

impl PaymentLogistics {
    /// 배송정보
    pub fn new(
        company: models::PaymentLogisticsCompany,
        invoice_number: String,
        sent_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> PaymentLogistics {
        PaymentLogistics {
            company,
            invoice_number,
            sent_at,
            received_at: None,
            address: None,
        }
    }
}
