/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentCancellation : 결제 취소 내역
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum PaymentCancellation {
    #[serde(rename = "FAILED")]
    Failed(Box<models::FailedPaymentCancellation>),
    #[serde(rename = "REQUESTED")]
    Requested(Box<models::RequestedPaymentCancellation>),
    #[serde(rename = "SUCCEEDED")]
    Succeeded(Box<models::SucceededPaymentCancellation>),
}

impl Default for PaymentCancellation {
    fn default() -> Self {
        Self::Failed(Default::default())
    }
}
