/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentWebhookResponse : 웹훅 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentWebhookResponse {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "header")]
    pub header: String,
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "respondedAt")]
    pub responded_at: chrono::DateTime<chrono::FixedOffset>,
}

impl PaymentWebhookResponse {
    /// 웹훅 응답 정보
    pub fn new(
        code: String,
        header: String,
        body: String,
        responded_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> PaymentWebhookResponse {
        PaymentWebhookResponse {
            code,
            header,
            body,
            responded_at,
        }
    }
}
