/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentMethodConvenienceStore : 편의점 결제 상세 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentMethodConvenienceStore {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(
        rename = "convenienceStoreBrand",
        skip_serializing_if = "Option::is_none"
    )]
    pub convenience_store_brand: Option<models::ConvenienceStoreBrand>,
    #[serde(rename = "confirmationNumber", skip_serializing_if = "Option::is_none")]
    pub confirmation_number: Option<String>,
    #[serde(rename = "receiptNumber", skip_serializing_if = "Option::is_none")]
    pub receipt_number: Option<String>,
    #[serde(rename = "paymentDeadline", skip_serializing_if = "Option::is_none")]
    pub payment_deadline: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl PaymentMethodConvenienceStore {
    /// 편의점 결제 상세 정보
    pub fn new(r#type: String) -> PaymentMethodConvenienceStore {
        PaymentMethodConvenienceStore {
            r#type,
            convenience_store_brand: None,
            confirmation_number: None,
            receipt_number: None,
            payment_deadline: None,
        }
    }
}
