/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentReconciliationStatus : 결제 건의 대사 상태
/// 결제 건의 대사 상태
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentReconciliationStatus {
    #[serde(rename = "MATCHED")]
    #[default]
    Matched,
    #[serde(rename = "NOT_MATCHED")]
    NotMatched,
    #[serde(rename = "INCOMPARABLE")]
    Incomparable,
    #[serde(rename = "NOT_COLLECTED")]
    NotCollected,
}

impl std::fmt::Display for PaymentReconciliationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Matched => write!(f, "MATCHED"),
            Self::NotMatched => write!(f, "NOT_MATCHED"),
            Self::Incomparable => write!(f, "INCOMPARABLE"),
            Self::NotCollected => write!(f, "NOT_COLLECTED"),
        }
    }
}
