/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentWebhookTrigger : 웹훅 실행 트리거  수동 웹훅 재발송, 가상계좌 입금, 비동기 취소 승인 시 발생한 웹훅일 때 필드의 값이 존재합니다.
/// 웹훅 실행 트리거  수동 웹훅 재발송, 가상계좌 입금, 비동기 취소 승인 시 발생한 웹훅일 때 필드의 값이 존재합니다.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentWebhookTrigger {
    #[serde(rename = "MANUAL")]
    #[default]
    Manual,
    #[serde(rename = "VIRTUAL_ACCOUNT_DEPOSIT")]
    VirtualAccountDeposit,
    #[serde(rename = "ASYNC_CANCEL_APPROVED")]
    AsyncCancelApproved,
    #[serde(rename = "ASYNC_CANCEL_FAILED")]
    AsyncCancelFailed,
    #[serde(rename = "ASYNC_PAY_APPROVED")]
    AsyncPayApproved,
    #[serde(rename = "ASYNC_PAY_FAILED")]
    AsyncPayFailed,
    #[serde(rename = "ASYNC_PAY_PENDING")]
    AsyncPayPending,
    #[serde(rename = "DISPUTE_CREATED")]
    DisputeCreated,
    #[serde(rename = "DISPUTE_RESOLVED")]
    DisputeResolved,
}

impl std::fmt::Display for PaymentWebhookTrigger {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Manual => write!(f, "MANUAL"),
            Self::VirtualAccountDeposit => write!(f, "VIRTUAL_ACCOUNT_DEPOSIT"),
            Self::AsyncCancelApproved => write!(f, "ASYNC_CANCEL_APPROVED"),
            Self::AsyncCancelFailed => write!(f, "ASYNC_CANCEL_FAILED"),
            Self::AsyncPayApproved => write!(f, "ASYNC_PAY_APPROVED"),
            Self::AsyncPayFailed => write!(f, "ASYNC_PAY_FAILED"),
            Self::AsyncPayPending => write!(f, "ASYNC_PAY_PENDING"),
            Self::DisputeCreated => write!(f, "DISPUTE_CREATED"),
            Self::DisputeResolved => write!(f, "DISPUTE_RESOLVED"),
        }
    }
}
