/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentMethod : 결제수단 정보
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PaymentMethod {
    #[serde(rename = "PaymentMethodCard")]
    PaymentMethodCard(Box<models::PaymentMethodCard>),
    #[serde(rename = "PaymentMethodConvenienceStore")]
    PaymentMethodConvenienceStore(Box<models::PaymentMethodConvenienceStore>),
    #[serde(rename = "PaymentMethodCrypto")]
    PaymentMethodCrypto(Box<models::PaymentMethodCrypto>),
    #[serde(rename = "PaymentMethodEasyPay")]
    PaymentMethodEasyPay(Box<models::PaymentMethodEasyPay>),
    #[serde(rename = "PaymentMethodGiftCertificate")]
    PaymentMethodGiftCertificate(Box<models::PaymentMethodGiftCertificate>),
    #[serde(rename = "PaymentMethodMobile")]
    PaymentMethodMobile(Box<models::PaymentMethodMobile>),
    #[serde(rename = "PaymentMethodTransfer")]
    PaymentMethodTransfer(Box<models::PaymentMethodTransfer>),
    #[serde(rename = "PaymentMethodVirtualAccount")]
    PaymentMethodVirtualAccount(Box<models::PaymentMethodVirtualAccount>),
}

impl Default for PaymentMethod {
    fn default() -> Self {
        Self::PaymentMethodCard(Default::default())
    }
}
