/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentInstallment : 할부 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentInstallment {
    #[serde(rename = "month")]
    pub month: i32,
    #[serde(rename = "isInterestFree")]
    pub is_interest_free: bool,
    /// 정보 필요시 포트원과 협의해 주세요.
    #[serde(
        rename = "isInterestFreeFromMerchant",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_interest_free_from_merchant: Option<bool>,
}

impl PaymentInstallment {
    /// 할부 정보
    pub fn new(month: i32, is_interest_free: bool) -> PaymentInstallment {
        PaymentInstallment {
            month,
            is_interest_free,
            is_interest_free_from_merchant: None,
        }
    }
}
