/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentCashReceipt : 결제 건 내 현금영수증 정보
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum PaymentCashReceipt {
    #[serde(rename = "CANCELLED")]
    Cancelled(Box<models::CancelledPaymentCashReceipt>),
    #[serde(rename = "ISSUED")]
    Issued(Box<models::IssuedPaymentCashReceipt>),
}

impl Default for PaymentCashReceipt {
    fn default() -> Self {
        Self::Cancelled(Default::default())
    }
}
