/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentClientType : 결제가 발생한 클라이언트 환경
/// 결제가 발생한 클라이언트 환경
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentClientType {
    #[serde(rename = "SDK_MOBILE")]
    #[default]
    SdkMobile,
    #[serde(rename = "SDK_PC")]
    SdkPc,
    #[serde(rename = "API")]
    Api,
}

impl std::fmt::Display for PaymentClientType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SdkMobile => write!(f, "SDK_MOBILE"),
            Self::SdkPc => write!(f, "SDK_PC"),
            Self::Api => write!(f, "API"),
        }
    }
}
