/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentOriginPlatformType : 플랫폼 타입
/// 플랫폼 타입
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentOriginPlatformType {
    #[serde(rename = "PC")]
    #[default]
    Pc,
    #[serde(rename = "MOBILE")]
    Mobile,
    #[serde(rename = "API")]
    Api,
}

impl std::fmt::Display for PaymentOriginPlatformType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pc => write!(f, "PC"),
            Self::Mobile => write!(f, "MOBILE"),
            Self::Api => write!(f, "API"),
        }
    }
}
