/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentSessionAgreement : 결제 세션 약관
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentSessionAgreement {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl PaymentSessionAgreement {
    /// 결제 세션 약관
    pub fn new(name: String, url: String) -> PaymentSessionAgreement {
        PaymentSessionAgreement { name, url }
    }
}
