/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentMethodVirtualAccount : 가상계좌 상세 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentMethodVirtualAccount {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "bank", skip_serializing_if = "Option::is_none")]
    pub bank: Option<models::Bank>,
    #[serde(rename = "accountNumber")]
    pub account_number: String,
    #[serde(rename = "accountType", skip_serializing_if = "Option::is_none")]
    pub account_type: Option<models::PaymentMethodVirtualAccountType>,
    #[serde(rename = "remitteeName", skip_serializing_if = "Option::is_none")]
    pub remittee_name: Option<String>,
    #[serde(rename = "remitterName", skip_serializing_if = "Option::is_none")]
    pub remitter_name: Option<String>,
    #[serde(rename = "expiredAt", skip_serializing_if = "Option::is_none")]
    pub expired_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "issuedAt", skip_serializing_if = "Option::is_none")]
    pub issued_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "refundStatus", skip_serializing_if = "Option::is_none")]
    pub refund_status: Option<models::PaymentMethodVirtualAccountRefundStatus>,
}

impl PaymentMethodVirtualAccount {
    /// 가상계좌 상세 정보
    pub fn new(r#type: String, account_number: String) -> PaymentMethodVirtualAccount {
        PaymentMethodVirtualAccount {
            r#type,
            bank: None,
            account_number,
            account_type: None,
            remittee_name: None,
            remitter_name: None,
            expired_at: None,
            issued_at: None,
            refund_status: None,
        }
    }
}
