/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentFilterInputEscrowStatus : 에스크로 상태
/// 에스크로 상태
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentFilterInputEscrowStatus {
    #[serde(rename = "REGISTERED")]
    #[default]
    Registered,
    #[serde(rename = "DELIVERED")]
    Delivered,
    #[serde(rename = "CONFIRMED")]
    Confirmed,
    #[serde(rename = "REJECTED")]
    Rejected,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "REJECT_CONFIRMED")]
    RejectConfirmed,
}

impl std::fmt::Display for PaymentFilterInputEscrowStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Registered => write!(f, "REGISTERED"),
            Self::Delivered => write!(f, "DELIVERED"),
            Self::Confirmed => write!(f, "CONFIRMED"),
            Self::Rejected => write!(f, "REJECTED"),
            Self::Cancelled => write!(f, "CANCELLED"),
            Self::RejectConfirmed => write!(f, "REJECT_CONFIRMED"),
        }
    }
}
