/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentReconciliationTransactionSummaryFilterInput : 거래대사 거래내역 필터
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentReconciliationTransactionSummaryFilterInput {
    #[serde(
        rename = "reconciliationStatuses",
        skip_serializing_if = "Option::is_none"
    )]
    pub reconciliation_statuses: Option<Vec<models::PaymentReconciliationStatus>>,
    #[serde(rename = "pgSpecifiers", skip_serializing_if = "Option::is_none")]
    pub pg_specifiers: Option<Vec<models::ReconciliationPgSpecifier>>,
    #[serde(rename = "storeIds", skip_serializing_if = "Option::is_none")]
    pub store_ids: Option<Vec<String>>,
}

impl PaymentReconciliationTransactionSummaryFilterInput {
    /// 거래대사 거래내역 필터
    pub fn new() -> PaymentReconciliationTransactionSummaryFilterInput {
        PaymentReconciliationTransactionSummaryFilterInput {
            reconciliation_statuses: None,
            pg_specifiers: None,
            store_ids: None,
        }
    }
}
