/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentScheduleFilterInput : 결제 예약 건 다건 조회를 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentScheduleFilterInput {
    /// 접근 권한이 있는 상점 아이디만 입력 가능하며, 미입력시 인증 정보의 상점 아이디를 사용합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    #[serde(rename = "billingKey", skip_serializing_if = "Option::is_none")]
    pub billing_key: Option<String>,
    /// 값을 입력하지 않으면 파라미터 end의 90일 전으로 설정됩니다.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// 값을 입력하지 않으면 현재 시점으로 설정됩니다.
    #[serde(rename = "until", skip_serializing_if = "Option::is_none")]
    pub until: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// 값을 입력하지 않으면 상태 필터링이 적용되지 않습니다.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Vec<models::PaymentScheduleStatus>>,
    #[serde(rename = "isForTest", skip_serializing_if = "Option::is_none")]
    pub is_for_test: Option<bool>,
}

impl PaymentScheduleFilterInput {
    /// 결제 예약 건 다건 조회를 위한 입력 정보
    pub fn new() -> PaymentScheduleFilterInput {
        PaymentScheduleFilterInput {
            store_id: None,
            billing_key: None,
            from: None,
            until: None,
            status: None,
            is_for_test: None,
        }
    }
}
