/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// Payment : 결제 건
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum Payment {
    #[serde(rename = "CANCELLED")]
    Cancelled(Box<models::CancelledPayment>),
    #[serde(rename = "FAILED")]
    Failed(Box<models::FailedPayment>),
    #[serde(rename = "PAID")]
    Paid(Box<models::PaidPayment>),
    #[serde(rename = "PARTIAL_CANCELLED")]
    PartialCancelled(Box<models::PartialCancelledPayment>),
    #[serde(rename = "PAY_PENDING")]
    PayPending(Box<models::PayPendingPayment>),
    #[serde(rename = "READY")]
    Ready(Box<models::ReadyPayment>),
    #[serde(rename = "VIRTUAL_ACCOUNT_ISSUED")]
    VirtualAccountIssued(Box<models::VirtualAccountIssuedPayment>),
}

impl Default for Payment {
    fn default() -> Self {
        Self::Cancelled(Default::default())
    }
}
