/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentSessionColors : 체크아웃 페이지 색 설정
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentSessionColors {
    /// CSS 색 문자열 형식
    #[serde(rename = "primary", skip_serializing_if = "Option::is_none")]
    pub primary: Option<String>,
    /// CSS 색 문자열 형식
    #[serde(rename = "primaryHover", skip_serializing_if = "Option::is_none")]
    pub primary_hover: Option<String>,
    /// CSS 색 문자열 형식
    #[serde(rename = "primaryLight", skip_serializing_if = "Option::is_none")]
    pub primary_light: Option<String>,
}

impl PaymentSessionColors {
    /// 체크아웃 페이지 색 설정
    pub fn new() -> PaymentSessionColors {
        PaymentSessionColors {
            primary: None,
            primary_hover: None,
            primary_light: None,
        }
    }
}
