/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentAmount : 결제 금액 세부 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentAmount {
    #[serde(rename = "total")]
    pub total: i64,
    #[serde(rename = "taxFree")]
    pub tax_free: i64,
    #[serde(rename = "vat", skip_serializing_if = "Option::is_none")]
    pub vat: Option<i64>,
    #[serde(rename = "supply", skip_serializing_if = "Option::is_none")]
    pub supply: Option<i64>,
    /// 카드사 할인금액, 포트원 프로모션 할인금액, 간편결제 할인금액(적립형 포인트 결제, 쿠폰 할인) 등을 포함합니다.
    #[serde(rename = "discount")]
    pub discount: i64,
    #[serde(rename = "paid")]
    pub paid: i64,
    #[serde(rename = "cancelled")]
    pub cancelled: i64,
    #[serde(rename = "cancelledTaxFree")]
    pub cancelled_tax_free: i64,
}

impl PaymentAmount {
    /// 결제 금액 세부 정보
    pub fn new(
        total: i64,
        tax_free: i64,
        discount: i64,
        paid: i64,
        cancelled: i64,
        cancelled_tax_free: i64,
    ) -> PaymentAmount {
        PaymentAmount {
            total,
            tax_free,
            vat: None,
            supply: None,
            discount,
            paid,
            cancelled,
            cancelled_tax_free,
        }
    }
}
