/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentEvent : 결제 이벤트
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PaymentEvent {
    #[serde(rename = "CANCELLED")]
    Cancelled(Box<models::CancelledPaymentEvent>),
    #[serde(rename = "PAID")]
    Paid(Box<models::PaidPaymentEvent>),
    #[serde(rename = "PARTIAL_CANCELLED")]
    PartialCancelled(Box<models::PartialCancelledPaymentEvent>),
}

impl Default for PaymentEvent {
    fn default() -> Self {
        Self::Cancelled(Default::default())
    }
}
