/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentMethodCard : 결제수단 카드 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentMethodCard {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<Box<models::Card>>,
    #[serde(rename = "approvalNumber", skip_serializing_if = "Option::is_none")]
    pub approval_number: Option<String>,
    #[serde(rename = "installment", skip_serializing_if = "Option::is_none")]
    pub installment: Option<Box<models::PaymentInstallment>>,
    #[serde(rename = "pointUsed", skip_serializing_if = "Option::is_none")]
    pub point_used: Option<bool>,
}

impl PaymentMethodCard {
    /// 결제수단 카드 정보
    pub fn new(r#type: String) -> PaymentMethodCard {
        PaymentMethodCard {
            r#type,
            card: None,
            approval_number: None,
            installment: None,
            point_used: None,
        }
    }
}
