/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentTextSearch : 통합검색 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentTextSearch {
    #[serde(rename = "field")]
    pub field: models::PaymentTextSearchField,
    #[serde(rename = "value")]
    pub value: String,
}

impl PaymentTextSearch {
    /// 통합검색 입력 정보
    pub fn new(field: models::PaymentTextSearchField, value: String) -> PaymentTextSearch {
        PaymentTextSearch { field, value }
    }
}
