/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentWithCursor : 결제 건 및 커서 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentWithCursor {
    #[serde(rename = "payment")]
    pub payment: Box<models::Payment>,
    #[serde(rename = "cursor")]
    pub cursor: String,
}

impl PaymentWithCursor {
    /// 결제 건 및 커서 정보
    pub fn new(payment: models::Payment, cursor: String) -> PaymentWithCursor {
        PaymentWithCursor {
            payment: Box::new(payment),
            cursor,
        }
    }
}
