/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentSession : 결제 세션
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentSession {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "storeId")]
    pub store_id: String,
    #[serde(rename = "paymentId")]
    pub payment_id: String,
    #[serde(rename = "profileKey")]
    pub profile_key: String,
    #[serde(rename = "paymentMethod", skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<models::CheckoutPaymentMethod>,
    #[serde(rename = "country")]
    pub country: models::Country,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "totalAmount")]
    pub total_amount: i64,
    #[serde(rename = "orderName")]
    pub order_name: String,
    /// 지정하지 않으면 기본 결과 페이지가 표시됩니다.
    #[serde(rename = "redirectUrl", skip_serializing_if = "Option::is_none")]
    pub redirect_url: Option<String>,
    #[serde(rename = "products", skip_serializing_if = "Option::is_none")]
    pub products: Option<Box<Vec<models::PaymentSessionProduct>>>,
    #[serde(rename = "customerName", skip_serializing_if = "Option::is_none")]
    pub customer_name: Option<String>,
    #[serde(rename = "customerEmail", skip_serializing_if = "Option::is_none")]
    pub customer_email: Option<String>,
    /// 페이지 헤더 및 결제사 UI에 표시됩니다.
    #[serde(rename = "storeName", skip_serializing_if = "Option::is_none")]
    pub store_name: Option<String>,
    /// 구매자가 모든 약관에 동의해야 결제 버튼이 활성화됩니다.
    #[serde(rename = "agreements", skip_serializing_if = "Option::is_none")]
    pub agreements: Option<Box<Vec<models::PaymentSessionAgreement>>>,
    #[serde(rename = "orderImageUrl", skip_serializing_if = "Option::is_none")]
    pub order_image_url: Option<String>,
    /// 결제 완료 후 결제 건 조회에서도 확인할 수 있습니다.
    #[serde(rename = "customData", skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<String>,
    #[serde(rename = "colors", skip_serializing_if = "Option::is_none")]
    pub colors: Option<Box<models::PaymentSessionColors>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "expiresAt")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
}

impl PaymentSession {
    /// 결제 세션
    pub fn new(
        id: String,
        store_id: String,
        payment_id: String,
        profile_key: String,
        country: models::Country,
        currency: models::Currency,
        total_amount: i64,
        order_name: String,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        expires_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> PaymentSession {
        PaymentSession {
            id,
            store_id,
            payment_id,
            profile_key,
            payment_method: None,
            country,
            currency,
            total_amount,
            order_name,
            redirect_url: None,
            products: None,
            customer_name: None,
            customer_email: None,
            store_name: None,
            agreements: None,
            order_image_url: None,
            custom_data: None,
            colors: None,
            created_at,
            expires_at,
        }
    }
}
