/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentProduct : 상품 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentProduct {
    /// 고객사가 직접 부여한 식별자입니다.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    /// 카테고리 등으로 활용될 수 있습니다.
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
}

impl PaymentProduct {
    /// 상품 정보
    pub fn new(id: String, name: String, amount: i64, quantity: i32) -> PaymentProduct {
        PaymentProduct {
            id,
            name,
            tag: None,
            code: None,
            amount,
            quantity,
            link: None,
        }
    }
}
