/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentScheduleAlreadyExistsError : 결제 예약건이 이미 존재하는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentScheduleAlreadyExistsError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PaymentScheduleAlreadyExistsError {
    /// 결제 예약건이 이미 존재하는 경우
    pub fn new(r#type: String) -> PaymentScheduleAlreadyExistsError {
        PaymentScheduleAlreadyExistsError {
            r#type,
            message: None,
        }
    }
}
