/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentMethodTransfer : 계좌 이체 상세 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentMethodTransfer {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "bank", skip_serializing_if = "Option::is_none")]
    pub bank: Option<models::Bank>,
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
}

impl PaymentMethodTransfer {
    /// 계좌 이체 상세 정보
    pub fn new(r#type: String) -> PaymentMethodTransfer {
        PaymentMethodTransfer {
            r#type,
            bank: None,
            account_number: None,
        }
    }
}
