/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentReconciliationVatReportSummary {
    #[serde(rename = "totalSupplyAmount")]
    pub total_supply_amount: i64,
    #[serde(rename = "totalVatAmount")]
    pub total_vat_amount: i64,
    #[serde(rename = "totalTaxFreeAmount")]
    pub total_tax_free_amount: i64,
    #[serde(rename = "totalAmount")]
    pub total_amount: i64,
}

impl PaymentReconciliationVatReportSummary {
    pub fn new(
        total_supply_amount: i64,
        total_vat_amount: i64,
        total_tax_free_amount: i64,
        total_amount: i64,
    ) -> PaymentReconciliationVatReportSummary {
        PaymentReconciliationVatReportSummary {
            total_supply_amount,
            total_vat_amount,
            total_tax_free_amount,
            total_amount,
        }
    }
}
