/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentLogisticsCompany : 물류 회사
/// 물류 회사
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentLogisticsCompany {
    #[serde(rename = "LOTTE")]
    #[default]
    Lotte,
    #[serde(rename = "LOGEN")]
    Logen,
    #[serde(rename = "DONGWON")]
    Dongwon,
    #[serde(rename = "POST")]
    Post,
    #[serde(rename = "CJ")]
    Cj,
    #[serde(rename = "HANJIN")]
    Hanjin,
    #[serde(rename = "DAESIN")]
    Daesin,
    #[serde(rename = "ILYANG")]
    Ilyang,
    #[serde(rename = "KYUNGDONG")]
    Kyungdong,
    #[serde(rename = "CHUNIL")]
    Chunil,
    #[serde(rename = "POST_REGISTERED")]
    PostRegistered,
    #[serde(rename = "GS")]
    Gs,
    #[serde(rename = "WOORI")]
    Woori,
    #[serde(rename = "HAPDONG")]
    Hapdong,
    #[serde(rename = "FEDEX")]
    Fedex,
    #[serde(rename = "UPS")]
    Ups,
    #[serde(rename = "GSM_NTON")]
    GsmNton,
    #[serde(rename = "SUNGWON")]
    Sungwon,
    #[serde(rename = "LX_PANTOS")]
    LxPantos,
    #[serde(rename = "ACI")]
    Aci,
    #[serde(rename = "CJ_INTL")]
    CjIntl,
    #[serde(rename = "USPS")]
    Usps,
    #[serde(rename = "EMS")]
    Ems,
    #[serde(rename = "DHL")]
    Dhl,
    #[serde(rename = "KGL")]
    Kgl,
    #[serde(rename = "GOODSTOLUCK")]
    Goodstoluck,
    #[serde(rename = "KUNYOUNG")]
    Kunyoung,
    #[serde(rename = "SLX")]
    Slx,
    #[serde(rename = "SF")]
    Sf,
    #[serde(rename = "ETC")]
    Etc,
}

impl std::fmt::Display for PaymentLogisticsCompany {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Lotte => write!(f, "LOTTE"),
            Self::Logen => write!(f, "LOGEN"),
            Self::Dongwon => write!(f, "DONGWON"),
            Self::Post => write!(f, "POST"),
            Self::Cj => write!(f, "CJ"),
            Self::Hanjin => write!(f, "HANJIN"),
            Self::Daesin => write!(f, "DAESIN"),
            Self::Ilyang => write!(f, "ILYANG"),
            Self::Kyungdong => write!(f, "KYUNGDONG"),
            Self::Chunil => write!(f, "CHUNIL"),
            Self::PostRegistered => write!(f, "POST_REGISTERED"),
            Self::Gs => write!(f, "GS"),
            Self::Woori => write!(f, "WOORI"),
            Self::Hapdong => write!(f, "HAPDONG"),
            Self::Fedex => write!(f, "FEDEX"),
            Self::Ups => write!(f, "UPS"),
            Self::GsmNton => write!(f, "GSM_NTON"),
            Self::Sungwon => write!(f, "SUNGWON"),
            Self::LxPantos => write!(f, "LX_PANTOS"),
            Self::Aci => write!(f, "ACI"),
            Self::CjIntl => write!(f, "CJ_INTL"),
            Self::Usps => write!(f, "USPS"),
            Self::Ems => write!(f, "EMS"),
            Self::Dhl => write!(f, "DHL"),
            Self::Kgl => write!(f, "KGL"),
            Self::Goodstoluck => write!(f, "GOODSTOLUCK"),
            Self::Kunyoung => write!(f, "KUNYOUNG"),
            Self::Slx => write!(f, "SLX"),
            Self::Sf => write!(f, "SF"),
            Self::Etc => write!(f, "ETC"),
        }
    }
}
