/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentSortBy : 결제 건 정렬 기준
/// 결제 건 정렬 기준
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentSortBy {
    #[serde(rename = "REQUESTED_AT")]
    #[default]
    RequestedAt,
    #[serde(rename = "STATUS_CHANGED_AT")]
    StatusChangedAt,
}

impl std::fmt::Display for PaymentSortBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RequestedAt => write!(f, "REQUESTED_AT"),
            Self::StatusChangedAt => write!(f, "STATUS_CHANGED_AT"),
        }
    }
}
