/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PaymentMethodType {
    #[serde(rename = "CARD")]
    #[default]
    Card,
    #[serde(rename = "TRANSFER")]
    Transfer,
    #[serde(rename = "VIRTUAL_ACCOUNT")]
    VirtualAccount,
    #[serde(rename = "GIFT_CERTIFICATE")]
    GiftCertificate,
    #[serde(rename = "MOBILE")]
    Mobile,
    #[serde(rename = "EASY_PAY")]
    EasyPay,
    #[serde(rename = "CONVENIENCE_STORE")]
    ConvenienceStore,
    #[serde(rename = "CRYPTO")]
    Crypto,
}

impl std::fmt::Display for PaymentMethodType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Card => write!(f, "CARD"),
            Self::Transfer => write!(f, "TRANSFER"),
            Self::VirtualAccount => write!(f, "VIRTUAL_ACCOUNT"),
            Self::GiftCertificate => write!(f, "GIFT_CERTIFICATE"),
            Self::Mobile => write!(f, "MOBILE"),
            Self::EasyPay => write!(f, "EASY_PAY"),
            Self::ConvenienceStore => write!(f, "CONVENIENCE_STORE"),
            Self::Crypto => write!(f, "CRYPTO"),
        }
    }
}
