/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentMethodEasyPayMethodCharge : 충전식 포인트 결제 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentMethodEasyPayMethodCharge {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "bank", skip_serializing_if = "Option::is_none")]
    pub bank: Option<models::Bank>,
}

impl PaymentMethodEasyPayMethodCharge {
    /// 충전식 포인트 결제 정보
    pub fn new(r#type: String) -> PaymentMethodEasyPayMethodCharge {
        PaymentMethodEasyPayMethodCharge { r#type, bank: None }
    }
}
