/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PaymentWebhookRequest : 웹훅 요청 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentWebhookRequest {
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<String>,
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "requestedAt", skip_serializing_if = "Option::is_none")]
    pub requested_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl PaymentWebhookRequest {
    /// 웹훅 요청 정보
    pub fn new(body: String) -> PaymentWebhookRequest {
        PaymentWebhookRequest {
            header: None,
            body,
            requested_at: None,
        }
    }
}
