/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PaymentTransaction : 결제 시도
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum PaymentTransaction {
    #[serde(rename = "CANCELLED")]
    Cancelled(Box<models::CancelledPaymentTransaction>),
    #[serde(rename = "FAILED")]
    Failed(Box<models::FailedPaymentTransaction>),
    #[serde(rename = "PAID")]
    Paid(Box<models::PaidPaymentTransaction>),
    #[serde(rename = "PARTIAL_CANCELLED")]
    PartialCancelled(Box<models::PartialCancelledPaymentTransaction>),
    #[serde(rename = "PAY_PENDING")]
    PayPending(Box<models::PayPendingPaymentTransaction>),
    #[serde(rename = "READY")]
    Ready(Box<models::ReadyPaymentTransaction>),
    #[serde(rename = "VIRTUAL_ACCOUNT_ISSUED")]
    VirtualAccountIssued(Box<models::VirtualAccountIssuedPaymentTransaction>),
}

impl Default for PaymentTransaction {
    fn default() -> Self {
        Self::Cancelled(Default::default())
    }
}
