/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PgBillingKeyIssueResponse : 채널 별 빌링키 발급 응답
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PgBillingKeyIssueResponse {
    #[serde(rename = "FAILED")]
    Failed(Box<models::FailedPgBillingKeyIssueResponse>),
    #[serde(rename = "ISSUED")]
    Issued(Box<models::IssuedPgBillingKeyIssueResponse>),
}

impl Default for PgBillingKeyIssueResponse {
    fn default() -> Self {
        Self::Failed(Default::default())
    }
}
