/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PgCompany : PG사
/// PG사
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PgCompany {
    #[serde(rename = "INICIS")]
    #[default]
    Inicis,
    #[serde(rename = "NICE")]
    Nice,
    #[serde(rename = "KCP")]
    Kcp,
    #[serde(rename = "DANAL")]
    Danal,
    #[serde(rename = "TOSSPAYMENTS")]
    Tosspayments,
    #[serde(rename = "MOBILIANS")]
    Mobilians,
    #[serde(rename = "KICC")]
    Kicc,
    #[serde(rename = "SMARTRO")]
    Smartro,
    #[serde(rename = "DAOU")]
    Daou,
    #[serde(rename = "BLUEWALNUT")]
    Bluewalnut,
    #[serde(rename = "PAYPAL")]
    Paypal,
    #[serde(rename = "ALIPAY")]
    Alipay,
    #[serde(rename = "EXIMBAY")]
    Eximbay,
    #[serde(rename = "PAYMENTWALL")]
    Paymentwall,
    #[serde(rename = "SETTLE")]
    Settle,
    #[serde(rename = "GALAXIA")]
    Galaxia,
    #[serde(rename = "NAVERPAY")]
    Naverpay,
    #[serde(rename = "KAKAOPAY")]
    Kakaopay,
    #[serde(rename = "SMILEPAY")]
    Smilepay,
    #[serde(rename = "KAKAO")]
    Kakao,
    #[serde(rename = "TOSSPAY")]
    Tosspay,
    #[serde(rename = "CHAI")]
    Chai,
    #[serde(rename = "PAYCO")]
    Payco,
    #[serde(rename = "PAYPLE")]
    Payple,
    #[serde(rename = "SYRUP")]
    Syrup,
    #[serde(rename = "KSNET")]
    Ksnet,
    #[serde(rename = "WELCOME")]
    Welcome,
    #[serde(rename = "JTNET")]
    Jtnet,
    #[serde(rename = "KPN")]
    Kpn,
    #[serde(rename = "HYPHEN")]
    Hyphen,
    #[serde(rename = "PAYLETTER")]
    Payletter,
    #[serde(rename = "TRIPLE_A")]
    TripleA,
    #[serde(rename = "INNOPAY")]
    Innopay,
}

impl std::fmt::Display for PgCompany {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Inicis => write!(f, "INICIS"),
            Self::Nice => write!(f, "NICE"),
            Self::Kcp => write!(f, "KCP"),
            Self::Danal => write!(f, "DANAL"),
            Self::Tosspayments => write!(f, "TOSSPAYMENTS"),
            Self::Mobilians => write!(f, "MOBILIANS"),
            Self::Kicc => write!(f, "KICC"),
            Self::Smartro => write!(f, "SMARTRO"),
            Self::Daou => write!(f, "DAOU"),
            Self::Bluewalnut => write!(f, "BLUEWALNUT"),
            Self::Paypal => write!(f, "PAYPAL"),
            Self::Alipay => write!(f, "ALIPAY"),
            Self::Eximbay => write!(f, "EXIMBAY"),
            Self::Paymentwall => write!(f, "PAYMENTWALL"),
            Self::Settle => write!(f, "SETTLE"),
            Self::Galaxia => write!(f, "GALAXIA"),
            Self::Naverpay => write!(f, "NAVERPAY"),
            Self::Kakaopay => write!(f, "KAKAOPAY"),
            Self::Smilepay => write!(f, "SMILEPAY"),
            Self::Kakao => write!(f, "KAKAO"),
            Self::Tosspay => write!(f, "TOSSPAY"),
            Self::Chai => write!(f, "CHAI"),
            Self::Payco => write!(f, "PAYCO"),
            Self::Payple => write!(f, "PAYPLE"),
            Self::Syrup => write!(f, "SYRUP"),
            Self::Ksnet => write!(f, "KSNET"),
            Self::Welcome => write!(f, "WELCOME"),
            Self::Jtnet => write!(f, "JTNET"),
            Self::Kpn => write!(f, "KPN"),
            Self::Hyphen => write!(f, "HYPHEN"),
            Self::Payletter => write!(f, "PAYLETTER"),
            Self::TripleA => write!(f, "TRIPLE_A"),
            Self::Innopay => write!(f, "INNOPAY"),
        }
    }
}
