/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PgProviderError : PG사에서 오류를 전달한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PgProviderError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "pgCode")]
    pub pg_code: String,
    #[serde(rename = "pgMessage")]
    pub pg_message: String,
}

impl PgProviderError {
    /// PG사에서 오류를 전달한 경우
    pub fn new(r#type: String, pg_code: String, pg_message: String) -> PgProviderError {
        PgProviderError {
            r#type,
            message: None,
            pg_code,
            pg_message,
        }
    }
}
