/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformSettlementPaymentAmountExceededPortOnePaymentError : 정산 요청 결제 금액이 포트원 결제 내역의 결제 금액을 초과한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformSettlementPaymentAmountExceededPortOnePaymentError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "registeredSettlementPaymentAmount")]
    pub registered_settlement_payment_amount: i64,
    #[serde(rename = "requestSettlementPaymentAmount")]
    pub request_settlement_payment_amount: i64,
    #[serde(rename = "portOnePaymentAmount")]
    pub port_one_payment_amount: i64,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformSettlementPaymentAmountExceededPortOnePaymentError {
    /// 정산 요청 결제 금액이 포트원 결제 내역의 결제 금액을 초과한 경우
    pub fn new(
        r#type: String,
        registered_settlement_payment_amount: i64,
        request_settlement_payment_amount: i64,
        port_one_payment_amount: i64,
    ) -> PlatformSettlementPaymentAmountExceededPortOnePaymentError {
        PlatformSettlementPaymentAmountExceededPortOnePaymentError {
            r#type,
            registered_settlement_payment_amount,
            request_settlement_payment_amount,
            port_one_payment_amount,
            message: None,
        }
    }
}
