/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPartnerManualSettlement {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "graphqlId")]
    pub graphql_id: String,
    #[serde(rename = "partner")]
    pub partner: Box<models::PlatformPartner>,
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "settlementDate")]
    pub settlement_date: chrono::NaiveDate,
    #[serde(rename = "settlementCurrency")]
    pub settlement_currency: models::Currency,
    #[serde(rename = "status")]
    pub status: models::PlatformPartnerSettlementStatus,
    #[serde(rename = "statusUpdatedAt", skip_serializing_if = "Option::is_none")]
    pub status_updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "taxFreeAmount")]
    pub tax_free_amount: i64,
    #[serde(rename = "isForTest")]
    pub is_for_test: bool,
}

impl PlatformPartnerManualSettlement {
    pub fn new(
        r#type: String,
        id: String,
        graphql_id: String,
        partner: models::PlatformPartner,
        settlement_date: chrono::NaiveDate,
        settlement_currency: models::Currency,
        status: models::PlatformPartnerSettlementStatus,
        amount: i64,
        tax_free_amount: i64,
        is_for_test: bool,
    ) -> PlatformPartnerManualSettlement {
        PlatformPartnerManualSettlement {
            r#type,
            id,
            graphql_id,
            partner: Box::new(partner),
            settlement_date,
            settlement_currency,
            status,
            status_updated_at: None,
            memo: None,
            amount,
            tax_free_amount,
            is_for_test,
        }
    }
}
