/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformAccountVerificationNotFoundError : 파트너 계좌 검증 아이디를 찾을 수 없는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformAccountVerificationNotFoundError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformAccountVerificationNotFoundError {
    /// 파트너 계좌 검증 아이디를 찾을 수 없는 경우
    pub fn new(r#type: String) -> PlatformAccountVerificationNotFoundError {
        PlatformAccountVerificationNotFoundError {
            r#type,
            message: None,
        }
    }
}
