/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PlatformTransferSummary {
    #[serde(rename = "MANUAL")]
    Manual(Box<models::PlatformManualTransferSummary>),
    #[serde(rename = "ORDER_CANCEL")]
    OrderCancel(Box<models::PlatformOrderCancelTransferSummary>),
    #[serde(rename = "ORDER")]
    Order(Box<models::PlatformOrderTransferSummary>),
}

impl Default for PlatformTransferSummary {
    fn default() -> Self {
        Self::Manual(Default::default())
    }
}
