/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformAccountVerificationFailedError : 파트너 계좌 인증이 실패한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformAccountVerificationFailedError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformAccountVerificationFailedError {
    /// 파트너 계좌 인증이 실패한 경우
    pub fn new(r#type: String) -> PlatformAccountVerificationFailedError {
        PlatformAccountVerificationFailedError {
            r#type,
            message: None,
        }
    }
}
