/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformSettlementCycleMethod : 플랫폼 정산 주기 계산 방식
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PlatformSettlementCycleMethod {
    #[serde(rename = "DAILY")]
    Daily(Box<models::PlatformSettlementCycleMethodDaily>),
    #[serde(rename = "MANUAL_DATES")]
    ManualDates(Box<models::PlatformSettlementCycleMethodManualDates>),
    #[serde(rename = "MONTHLY")]
    Monthly(Box<models::PlatformSettlementCycleMethodMonthly>),
    #[serde(rename = "WEEKLY")]
    Weekly(Box<models::PlatformSettlementCycleMethodWeekly>),
}

impl Default for PlatformSettlementCycleMethod {
    fn default() -> Self {
        Self::Daily(Default::default())
    }
}
