/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformAccountTransfer : 계좌 이체  송금 대행을 통해 일어난 정산 금액 지급, 인출 목적의 계좌 이체 결과 정보입니다.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PlatformAccountTransfer {
    #[serde(rename = "DEPOSIT")]
    Deposit(Box<models::PlatformDepositAccountTransfer>),
    #[serde(rename = "WITHDRAWAL")]
    Withdrawal(Box<models::PlatformWithdrawalAccountTransfer>),
}

impl Default for PlatformAccountTransfer {
    fn default() -> Self {
        Self::Deposit(Default::default())
    }
}
