/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformPayer : 금액 부담 주체  플랫폼에서 발생한 결제 수수료, 부가세 등 금액을 부담하는 주체를 나타냅니다.
/// 금액 부담 주체  플랫폼에서 발생한 결제 수수료, 부가세 등 금액을 부담하는 주체를 나타냅니다.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformPayer {
    #[serde(rename = "PARTNER")]
    #[default]
    Partner,
    #[serde(rename = "MERCHANT")]
    Merchant,
}

impl std::fmt::Display for PlatformPayer {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Partner => write!(f, "PARTNER"),
            Self::Merchant => write!(f, "MERCHANT"),
        }
    }
}
