/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformDiscountSharePolicy : 할인 분담 정책  할인 분담은 고객사의 주문건에 쿠폰 및 포인트와 같은 할인금액이 적용될 때, 파트너 정산 시 할인금액에 대한 분담 정책을 가지는 객체입니다. 할인 유형에 대한 아이디와 메모, 그리고 파트너 분담율을 가집니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformDiscountSharePolicy {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "graphqlId")]
    pub graphql_id: String,
    #[serde(rename = "name")]
    pub name: String,
    /// 파트너가 분담할 할인금액의 비율을 의미하는 밀리 퍼센트 단위 (10^-5) 의 음이 아닌 정수이며, 파트너가 부담할 금액은 `할인금액 * partnerShareRate * 10^5` 로 책정합니다.
    #[serde(rename = "partnerShareRate")]
    pub partner_share_rate: i32,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "isArchived")]
    pub is_archived: bool,
    #[serde(rename = "appliedAt")]
    pub applied_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "isForTest")]
    pub is_for_test: bool,
}

impl PlatformDiscountSharePolicy {
    /// 할인 분담 정책  할인 분담은 고객사의 주문건에 쿠폰 및 포인트와 같은 할인금액이 적용될 때, 파트너 정산 시 할인금액에 대한 분담 정책을 가지는 객체입니다. 할인 유형에 대한 아이디와 메모, 그리고 파트너 분담율을 가집니다.
    pub fn new(
        id: String,
        graphql_id: String,
        name: String,
        partner_share_rate: i32,
        is_archived: bool,
        applied_at: chrono::DateTime<chrono::FixedOffset>,
        is_for_test: bool,
    ) -> PlatformDiscountSharePolicy {
        PlatformDiscountSharePolicy {
            id,
            graphql_id,
            name,
            partner_share_rate,
            memo: None,
            is_archived,
            applied_at,
            is_for_test,
        }
    }
}
