/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformCancellableAmountExceededError : 취소 가능한 금액이 초과한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformCancellableAmountExceededError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "cancellableAmount")]
    pub cancellable_amount: i64,
    #[serde(rename = "requestAmount")]
    pub request_amount: i64,
    #[serde(rename = "amountType")]
    pub amount_type: models::PlatformCancellableAmountType,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformCancellableAmountExceededError {
    /// 취소 가능한 금액이 초과한 경우
    pub fn new(
        r#type: String,
        cancellable_amount: i64,
        request_amount: i64,
        amount_type: models::PlatformCancellableAmountType,
    ) -> PlatformCancellableAmountExceededError {
        PlatformCancellableAmountExceededError {
            r#type,
            cancellable_amount,
            request_amount,
            amount_type,
            message: None,
        }
    }
}
