/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformTransferSummaryPartnerType : 파트너 유형
/// 파트너 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformTransferSummaryPartnerType {
    #[serde(rename = "BUSINESS")]
    #[default]
    Business,
    #[serde(rename = "WHT_PAYER")]
    WhtPayer,
    #[serde(rename = "NON_WHT_PAYER")]
    NonWhtPayer,
}

impl std::fmt::Display for PlatformTransferSummaryPartnerType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Business => write!(f, "BUSINESS"),
            Self::WhtPayer => write!(f, "WHT_PAYER"),
            Self::NonWhtPayer => write!(f, "NON_WHT_PAYER"),
        }
    }
}
