/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformDiscountSharePolicyIdDuplicatedError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "graphqlId")]
    pub graphql_id: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformDiscountSharePolicyIdDuplicatedError {
    pub fn new(
        r#type: String,
        id: String,
        graphql_id: String,
    ) -> PlatformDiscountSharePolicyIdDuplicatedError {
        PlatformDiscountSharePolicyIdDuplicatedError {
            r#type,
            id,
            graphql_id,
            message: None,
        }
    }
}
