/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformBulkPayoutStatus {
    #[serde(rename = "PREPARING")]
    #[default]
    Preparing,
    #[serde(rename = "PREPARED")]
    Prepared,
    #[serde(rename = "ONGOING")]
    Ongoing,
    #[serde(rename = "POST_PROCESS_PENDING")]
    PostProcessPending,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "COMPLETED")]
    Completed,
}

impl std::fmt::Display for PlatformBulkPayoutStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Preparing => write!(f, "PREPARING"),
            Self::Prepared => write!(f, "PREPARED"),
            Self::Ongoing => write!(f, "ONGOING"),
            Self::PostProcessPending => write!(f, "POST_PROCESS_PENDING"),
            Self::Cancelled => write!(f, "CANCELLED"),
            Self::Completed => write!(f, "COMPLETED"),
        }
    }
}
