/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPartnerSettlementStatusStats {
    #[serde(rename = "payoutScheduled")]
    pub payout_scheduled: i64,
    #[serde(rename = "payoutPrepared")]
    pub payout_prepared: i64,
    #[serde(rename = "payoutWithheld")]
    pub payout_withheld: i64,
    #[serde(rename = "payoutExcluded")]
    pub payout_excluded: i64,
    #[serde(rename = "payoutFailed")]
    pub payout_failed: i64,
    #[serde(rename = "payoutCancelled")]
    pub payout_cancelled: i64,
    #[serde(rename = "payoutConfirmed")]
    pub payout_confirmed: i64,
    #[serde(rename = "inPayout")]
    pub in_payout: i64,
    #[serde(rename = "paidOut")]
    pub paid_out: i64,
}

impl PlatformPartnerSettlementStatusStats {
    pub fn new(
        payout_scheduled: i64,
        payout_prepared: i64,
        payout_withheld: i64,
        payout_excluded: i64,
        payout_failed: i64,
        payout_cancelled: i64,
        payout_confirmed: i64,
        in_payout: i64,
        paid_out: i64,
    ) -> PlatformPartnerSettlementStatusStats {
        PlatformPartnerSettlementStatusStats {
            payout_scheduled,
            payout_prepared,
            payout_withheld,
            payout_excluded,
            payout_failed,
            payout_cancelled,
            payout_confirmed,
            in_payout,
            paid_out,
        }
    }
}
