/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformNegativePayoutAmountPartnersError : 지급 금액의 총합이 음수인 파트너가 존재하는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformNegativePayoutAmountPartnersError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformNegativePayoutAmountPartnersError {
    /// 지급 금액의 총합이 음수인 파트너가 존재하는 경우
    pub fn new(r#type: String) -> PlatformNegativePayoutAmountPartnersError {
        PlatformNegativePayoutAmountPartnersError {
            r#type,
            message: None,
        }
    }
}
