/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformPartnerContractSummary : 파트너 계약 요약 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPartnerContractSummary {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl PlatformPartnerContractSummary {
    /// 파트너 계약 요약 정보
    pub fn new(id: String, name: String) -> PlatformPartnerContractSummary {
        PlatformPartnerContractSummary { id, name }
    }
}
