/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformDiscountSharePolicyFilterInput : 할인 분담 정책 다건 조회를 위한 필터 조건
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformDiscountSharePolicyFilterInput {
    /// true 이면 보관된 할인 분담 정책을 조회하고, false 이면 보관되지 않은 할인 분담 정책을 조회합니다. 기본값은 false 입니다.
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    /// 하나 이상의 값이 존재하는 경우 해당 리스트에 포함되는 파트너 분담율을 가진 할인 분담 정책만 조회합니다.
    #[serde(rename = "partnerShareRates", skip_serializing_if = "Option::is_none")]
    pub partner_share_rates: Option<Vec<i32>>,
    #[serde(rename = "keyword", skip_serializing_if = "Option::is_none")]
    pub keyword: Option<Box<models::PlatformDiscountSharePolicyFilterInputKeyword>>,
}

impl PlatformDiscountSharePolicyFilterInput {
    /// 할인 분담 정책 다건 조회를 위한 필터 조건
    pub fn new() -> PlatformDiscountSharePolicyFilterInput {
        PlatformDiscountSharePolicyFilterInput {
            is_archived: None,
            partner_share_rates: None,
            keyword: None,
        }
    }
}
