/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformBulkTaskProgressStats {
    #[serde(rename = "preparedCount")]
    pub prepared_count: i64,
    #[serde(rename = "processingCount")]
    pub processing_count: i64,
    #[serde(rename = "succeededCount")]
    pub succeeded_count: i64,
    #[serde(rename = "failedCount")]
    pub failed_count: i64,
    #[serde(rename = "canceledCount")]
    pub canceled_count: i64,
}

impl PlatformBulkTaskProgressStats {
    pub fn new(
        prepared_count: i64,
        processing_count: i64,
        succeeded_count: i64,
        failed_count: i64,
        canceled_count: i64,
    ) -> PlatformBulkTaskProgressStats {
        PlatformBulkTaskProgressStats {
            prepared_count,
            processing_count,
            succeeded_count,
            failed_count,
            canceled_count,
        }
    }
}
