/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformPaymentMethodCard : 카드
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPaymentMethodCard {
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PlatformPaymentMethodCard {
    /// 카드
    pub fn new(r#type: String) -> PlatformPaymentMethodCard {
        PlatformPaymentMethodCard { r#type }
    }
}
