/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformDiscountSharePolicyFilterOptions : 할인 분담 정책 필터 옵션 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformDiscountSharePolicyFilterOptions {
    #[serde(rename = "partnerShareRates")]
    pub partner_share_rates: Vec<i32>,
}

impl PlatformDiscountSharePolicyFilterOptions {
    /// 할인 분담 정책 필터 옵션 조회 성공 응답 정보
    pub fn new(partner_share_rates: Vec<i32>) -> PlatformDiscountSharePolicyFilterOptions {
        PlatformDiscountSharePolicyFilterOptions {
            partner_share_rates,
        }
    }
}
