/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformSettlementCycleMethodMonthlyInput {
    #[serde(rename = "daysOfMonth")]
    pub days_of_month: Vec<i32>,
}

impl PlatformSettlementCycleMethodMonthlyInput {
    pub fn new(days_of_month: Vec<i32>) -> PlatformSettlementCycleMethodMonthlyInput {
        PlatformSettlementCycleMethodMonthlyInput { days_of_month }
    }
}
