/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformMemberCompanyConnectedPartnerTypeUnchangeableError : 연동 사업자로 연동된 파트너의 파트너 유형을 변경하려고 시도한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformMemberCompanyConnectedPartnerTypeUnchangeableError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformMemberCompanyConnectedPartnerTypeUnchangeableError {
    /// 연동 사업자로 연동된 파트너의 파트너 유형을 변경하려고 시도한 경우
    pub fn new(r#type: String) -> PlatformMemberCompanyConnectedPartnerTypeUnchangeableError {
        PlatformMemberCompanyConnectedPartnerTypeUnchangeableError {
            r#type,
            message: None,
        }
    }
}
