/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformPartnerTaxationType : 플랫폼 파트너 과세 유형
/// 플랫폼 파트너 과세 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformPartnerTaxationType {
    #[serde(rename = "NORMAL")]
    #[default]
    Normal,
    #[serde(rename = "SIMPLE_TAX_INVOICE_ISSUER")]
    SimpleTaxInvoiceIssuer,
    #[serde(rename = "SIMPLE")]
    Simple,
    #[serde(rename = "TAX_FREE")]
    TaxFree,
}

impl std::fmt::Display for PlatformPartnerTaxationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal => write!(f, "NORMAL"),
            Self::SimpleTaxInvoiceIssuer => write!(f, "SIMPLE_TAX_INVOICE_ISSUER"),
            Self::Simple => write!(f, "SIMPLE"),
            Self::TaxFree => write!(f, "TAX_FREE"),
        }
    }
}
