/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformCounterpartyOngoingTaxInvoiceExistsError : 연동된 거래처에 진행 중인 세금계산서가 있는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformCounterpartyOngoingTaxInvoiceExistsError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformCounterpartyOngoingTaxInvoiceExistsError {
    /// 연동된 거래처에 진행 중인 세금계산서가 있는 경우
    pub fn new(r#type: String) -> PlatformCounterpartyOngoingTaxInvoiceExistsError {
        PlatformCounterpartyOngoingTaxInvoiceExistsError {
            r#type,
            message: None,
        }
    }
}
