/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformBulkAccountTransferFilterInputCriteria {
    #[serde(rename = "timestampRange", skip_serializing_if = "Option::is_none")]
    pub timestamp_range: Option<Box<models::DateTimeRange>>,
    #[serde(
        rename = "statusUpdatedTimestampRange",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_updated_timestamp_range: Option<Box<models::DateTimeRange>>,
    #[serde(
        rename = "bulkAccountTransferId",
        skip_serializing_if = "Option::is_none"
    )]
    pub bulk_account_transfer_id: Option<String>,
}

impl PlatformBulkAccountTransferFilterInputCriteria {
    pub fn new() -> PlatformBulkAccountTransferFilterInputCriteria {
        PlatformBulkAccountTransferFilterInputCriteria {
            timestamp_range: None,
            status_updated_timestamp_range: None,
            bulk_account_transfer_id: None,
        }
    }
}
