/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformAccount : 플랫폼 정산 계좌  `currency` 가 KRW 일 경우 예금주 조회 API 를 통해 올바른 계좌인지 검증합니다. 그 외의 화폐일 경우 따로 검증하지는 않습니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformAccount {
    #[serde(rename = "bank")]
    pub bank: models::Bank,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "number")]
    pub number: String,
    #[serde(rename = "holder")]
    pub holder: String,
    #[serde(rename = "status")]
    pub status: models::PlatformAccountStatus,
}

impl PlatformAccount {
    /// 플랫폼 정산 계좌  `currency` 가 KRW 일 경우 예금주 조회 API 를 통해 올바른 계좌인지 검증합니다. 그 외의 화폐일 경우 따로 검증하지는 않습니다.
    pub fn new(
        bank: models::Bank,
        currency: models::Currency,
        number: String,
        holder: String,
        status: models::PlatformAccountStatus,
    ) -> PlatformAccount {
        PlatformAccount {
            bank,
            currency,
            number,
            holder,
            status,
        }
    }
}
