/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformContract : 계약  계약은 플랫폼 고객사가 파트너에게 정산해줄 대금과 정산일을 계산하는 데 적용되는 정보입니다. 고객사의 플랫폼에서 재화 및 서비스를 판매하기 위한 중개수수료와 판매금에 대한 정산일로 구성되어 있습니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformContract {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "graphqlId")]
    pub graphql_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "platformFee")]
    pub platform_fee: Box<models::PlatformFee>,
    #[serde(rename = "settlementCycle")]
    pub settlement_cycle: Box<models::PlatformSettlementCycle>,
    #[serde(rename = "platformFeeVatPayer")]
    pub platform_fee_vat_payer: models::PlatformPayer,
    /// false인 경우 정산금에서 결제 금액 부가세를 감액하지 않고, true인 경우 정산금에서 결제 금액 부가세를 감액합니다.
    #[serde(rename = "subtractPaymentVatAmount")]
    pub subtract_payment_vat_amount: bool,
    #[serde(rename = "isArchived")]
    pub is_archived: bool,
    #[serde(rename = "appliedAt")]
    pub applied_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "isForTest")]
    pub is_for_test: bool,
}

impl PlatformContract {
    /// 계약  계약은 플랫폼 고객사가 파트너에게 정산해줄 대금과 정산일을 계산하는 데 적용되는 정보입니다. 고객사의 플랫폼에서 재화 및 서비스를 판매하기 위한 중개수수료와 판매금에 대한 정산일로 구성되어 있습니다.
    pub fn new(
        id: String,
        graphql_id: String,
        name: String,
        platform_fee: models::PlatformFee,
        settlement_cycle: models::PlatformSettlementCycle,
        platform_fee_vat_payer: models::PlatformPayer,
        subtract_payment_vat_amount: bool,
        is_archived: bool,
        applied_at: chrono::DateTime<chrono::FixedOffset>,
        is_for_test: bool,
    ) -> PlatformContract {
        PlatformContract {
            id,
            graphql_id,
            name,
            memo: None,
            platform_fee: Box::new(platform_fee),
            settlement_cycle: Box::new(settlement_cycle),
            platform_fee_vat_payer,
            subtract_payment_vat_amount,
            is_archived,
            applied_at,
            is_for_test,
        }
    }
}
