/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformBulkPayoutStatusStats {
    #[serde(rename = "preparing")]
    pub preparing: i64,
    #[serde(rename = "prepared")]
    pub prepared: i64,
    #[serde(rename = "ongoing")]
    pub ongoing: i64,
    #[serde(rename = "postProcessPending")]
    pub post_process_pending: i64,
    #[serde(rename = "completed")]
    pub completed: i64,
    #[serde(rename = "cancelled")]
    pub cancelled: i64,
}

impl PlatformBulkPayoutStatusStats {
    pub fn new(
        preparing: i64,
        prepared: i64,
        ongoing: i64,
        post_process_pending: i64,
        completed: i64,
        cancelled: i64,
    ) -> PlatformBulkPayoutStatusStats {
        PlatformBulkPayoutStatusStats {
            preparing,
            prepared,
            ongoing,
            post_process_pending,
            completed,
            cancelled,
        }
    }
}
