/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformManualTransferSummary {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "graphqlId")]
    pub graphql_id: String,
    #[serde(rename = "partner")]
    pub partner: Box<models::PlatformTransferSummaryPartner>,
    #[serde(rename = "status")]
    pub status: models::PlatformTransferStatus,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    /// 날짜를 나타내는 문자열로, `yyyy-MM-dd` 형식을 따릅니다.
    #[serde(rename = "settlementDate")]
    pub settlement_date: chrono::NaiveDate,
    #[serde(rename = "settlementCurrency")]
    pub settlement_currency: models::Currency,
    #[serde(rename = "isForTest")]
    pub is_for_test: bool,
    /// 5월 삭제 예정 필드입니다. partner.userDefinedProperties를 사용해주시길 바랍니다.
    #[serde(rename = "partnerUserDefinedProperties")]
    pub partner_user_defined_properties: Vec<models::PlatformUserDefinedPropertyKeyValue>,
    #[serde(rename = "userDefinedProperties")]
    pub user_defined_properties: Vec<models::PlatformUserDefinedPropertyKeyValue>,
    #[serde(rename = "settlementAmount")]
    pub settlement_amount: i64,
    #[serde(rename = "settlementTaxFreeAmount")]
    pub settlement_tax_free_amount: i64,
}

impl PlatformManualTransferSummary {
    pub fn new(
        r#type: String,
        id: String,
        graphql_id: String,
        partner: models::PlatformTransferSummaryPartner,
        status: models::PlatformTransferStatus,
        settlement_date: chrono::NaiveDate,
        settlement_currency: models::Currency,
        is_for_test: bool,
        partner_user_defined_properties: Vec<models::PlatformUserDefinedPropertyKeyValue>,
        user_defined_properties: Vec<models::PlatformUserDefinedPropertyKeyValue>,
        settlement_amount: i64,
        settlement_tax_free_amount: i64,
    ) -> PlatformManualTransferSummary {
        PlatformManualTransferSummary {
            r#type,
            id,
            graphql_id,
            partner: Box::new(partner),
            status,
            memo: None,
            settlement_date,
            settlement_currency,
            is_for_test,
            partner_user_defined_properties,
            user_defined_properties,
            settlement_amount,
            settlement_tax_free_amount,
        }
    }
}
