/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformOrderTransferProduct : 상품
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformOrderTransferProduct {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "taxFreeAmount")]
    pub tax_free_amount: i64,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

impl PlatformOrderTransferProduct {
    /// 상품
    pub fn new(
        id: String,
        name: String,
        amount: i64,
        tax_free_amount: i64,
    ) -> PlatformOrderTransferProduct {
        PlatformOrderTransferProduct {
            id,
            name,
            amount,
            tax_free_amount,
            tag: None,
        }
    }
}
