/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformCancellationAndPaymentTypeMismatchedError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformCancellationAndPaymentTypeMismatchedError {
    pub fn new(r#type: String) -> PlatformCancellationAndPaymentTypeMismatchedError {
        PlatformCancellationAndPaymentTypeMismatchedError {
            r#type,
            message: None,
        }
    }
}
