/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformTransferDiscountSharePolicyNotFoundError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "discountSharePolicyId")]
    pub discount_share_policy_id: String,
    #[serde(rename = "discountSharePolicyGraphqlId")]
    pub discount_share_policy_graphql_id: String,
    #[serde(rename = "productId", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformTransferDiscountSharePolicyNotFoundError {
    pub fn new(
        r#type: String,
        discount_share_policy_id: String,
        discount_share_policy_graphql_id: String,
    ) -> PlatformTransferDiscountSharePolicyNotFoundError {
        PlatformTransferDiscountSharePolicyNotFoundError {
            r#type,
            discount_share_policy_id,
            discount_share_policy_graphql_id,
            product_id: None,
            message: None,
        }
    }
}
