/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformPartnerType : 파트너 유형별 추가 정보
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PlatformPartnerType {
    #[serde(rename = "BUSINESS")]
    Business(Box<models::PlatformPartnerTypeBusiness>),
    #[serde(rename = "NON_WHT_PAYER")]
    NonWhtPayer(Box<models::PlatformPartnerTypeNonWhtPayer>),
    #[serde(rename = "WHT_PAYER")]
    WhtPayer(Box<models::PlatformPartnerTypeWhtPayer>),
}

impl Default for PlatformPartnerType {
    fn default() -> Self {
        Self::Business(Default::default())
    }
}
