/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformPayoutSettlementStatementStatus : 정산 내역서 발송 상태
/// 정산 내역서 발송 상태
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformPayoutSettlementStatementStatus {
    #[serde(rename = "UNSENT")]
    #[default]
    Unsent,
    #[serde(rename = "SENT")]
    Sent,
    #[serde(rename = "SEND_FAILED")]
    SendFailed,
    #[serde(rename = "SEND_PREPARED")]
    SendPrepared,
}

impl std::fmt::Display for PlatformPayoutSettlementStatementStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unsent => write!(f, "UNSENT"),
            Self::Sent => write!(f, "SENT"),
            Self::SendFailed => write!(f, "SEND_FAILED"),
            Self::SendPrepared => write!(f, "SEND_PREPARED"),
        }
    }
}
