/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformMemberCompanyConnectedPartnersCannotBeScheduledError : 연동 사업자로 연동된 파트너들을 예약 수정하려고 시도한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformMemberCompanyConnectedPartnersCannotBeScheduledError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "ids")]
    pub ids: Vec<String>,
    #[serde(rename = "graphqlIds")]
    pub graphql_ids: Vec<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformMemberCompanyConnectedPartnersCannotBeScheduledError {
    /// 연동 사업자로 연동된 파트너들을 예약 수정하려고 시도한 경우
    pub fn new(
        r#type: String,
        ids: Vec<String>,
        graphql_ids: Vec<String>,
    ) -> PlatformMemberCompanyConnectedPartnersCannotBeScheduledError {
        PlatformMemberCompanyConnectedPartnersCannotBeScheduledError {
            r#type,
            ids,
            graphql_ids,
            message: None,
        }
    }
}
