/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformPartnerBusinessStatus : 플랫폼 파트너 사업자 상태
/// 플랫폼 파트너 사업자 상태
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformPartnerBusinessStatus {
    #[serde(rename = "NOT_VERIFIED")]
    #[default]
    NotVerified,
    #[serde(rename = "VERIFY_ERROR")]
    VerifyError,
    #[serde(rename = "NOT_FOUND")]
    NotFound,
    #[serde(rename = "IN_BUSINESS")]
    InBusiness,
    #[serde(rename = "CLOSED")]
    Closed,
    #[serde(rename = "SUSPENDED")]
    Suspended,
}

impl std::fmt::Display for PlatformPartnerBusinessStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NotVerified => write!(f, "NOT_VERIFIED"),
            Self::VerifyError => write!(f, "VERIFY_ERROR"),
            Self::NotFound => write!(f, "NOT_FOUND"),
            Self::InBusiness => write!(f, "IN_BUSINESS"),
            Self::Closed => write!(f, "CLOSED"),
            Self::Suspended => write!(f, "SUSPENDED"),
        }
    }
}
