/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformPayoutStatus {
    #[serde(rename = "CONFIRMED")]
    #[default]
    Confirmed,
    #[serde(rename = "PREPARED")]
    Prepared,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "STOPPED")]
    Stopped,
    #[serde(rename = "PROCESSING")]
    Processing,
    #[serde(rename = "SUCCEEDED")]
    Succeeded,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "SCHEDULED")]
    Scheduled,
}

impl std::fmt::Display for PlatformPayoutStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Confirmed => write!(f, "CONFIRMED"),
            Self::Prepared => write!(f, "PREPARED"),
            Self::Cancelled => write!(f, "CANCELLED"),
            Self::Stopped => write!(f, "STOPPED"),
            Self::Processing => write!(f, "PROCESSING"),
            Self::Succeeded => write!(f, "SUCCEEDED"),
            Self::Failed => write!(f, "FAILED"),
            Self::Scheduled => write!(f, "SCHEDULED"),
        }
    }
}
