/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformPaymentMethodTransfer : 계좌이체
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPaymentMethodTransfer {
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PlatformPaymentMethodTransfer {
    /// 계좌이체
    pub fn new(r#type: String) -> PlatformPaymentMethodTransfer {
        PlatformPaymentMethodTransfer { r#type }
    }
}
