/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformPartnerFilterOptions : 파트너 필터 옵션 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPartnerFilterOptions {
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "contractSummary")]
    pub contract_summary: Vec<models::PlatformPartnerContractSummary>,
}

impl PlatformPartnerFilterOptions {
    /// 파트너 필터 옵션 조회 성공 응답 정보
    pub fn new(
        tags: Vec<String>,
        contract_summary: Vec<models::PlatformPartnerContractSummary>,
    ) -> PlatformPartnerFilterOptions {
        PlatformPartnerFilterOptions {
            tags,
            contract_summary,
        }
    }
}
