/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformSettlementCancelAmountExceededPortOneCancelError : 정산 취소 요청 금액이 포트원 결제 취소 내역의 취소 금액을 초과한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformSettlementCancelAmountExceededPortOneCancelError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "registeredSettlementCancelAmount")]
    pub registered_settlement_cancel_amount: i64,
    #[serde(rename = "requestSettlementCancelAmount")]
    pub request_settlement_cancel_amount: i64,
    #[serde(rename = "portOneCancelAmount")]
    pub port_one_cancel_amount: i64,
    #[serde(rename = "amountType")]
    pub amount_type: models::PlatformCancellableAmountType,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformSettlementCancelAmountExceededPortOneCancelError {
    /// 정산 취소 요청 금액이 포트원 결제 취소 내역의 취소 금액을 초과한 경우
    pub fn new(
        r#type: String,
        registered_settlement_cancel_amount: i64,
        request_settlement_cancel_amount: i64,
        port_one_cancel_amount: i64,
        amount_type: models::PlatformCancellableAmountType,
    ) -> PlatformSettlementCancelAmountExceededPortOneCancelError {
        PlatformSettlementCancelAmountExceededPortOneCancelError {
            r#type,
            registered_settlement_cancel_amount,
            request_settlement_cancel_amount,
            port_one_cancel_amount,
            amount_type,
            message: None,
        }
    }
}
