/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformCounterpartyNotConnectableStatusError : 파트너 거래처 연동 상태가 연동 가능한 상태가 아닌 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformCounterpartyNotConnectableStatusError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformCounterpartyNotConnectableStatusError {
    /// 파트너 거래처 연동 상태가 연동 가능한 상태가 아닌 경우
    pub fn new(r#type: String) -> PlatformCounterpartyNotConnectableStatusError {
        PlatformCounterpartyNotConnectableStatusError {
            r#type,
            message: None,
        }
    }
}
