/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformSettlementCycleDatePolicy : 플랫폼 정산 기준일
/// 플랫폼 정산 기준일
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformSettlementCycleDatePolicy {
    #[serde(rename = "HOLIDAY_BEFORE")]
    #[default]
    HolidayBefore,
    #[serde(rename = "HOLIDAY_AFTER")]
    HolidayAfter,
    #[serde(rename = "CALENDAR_DAY")]
    CalendarDay,
}

impl std::fmt::Display for PlatformSettlementCycleDatePolicy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HolidayBefore => write!(f, "HOLIDAY_BEFORE"),
            Self::HolidayAfter => write!(f, "HOLIDAY_AFTER"),
            Self::CalendarDay => write!(f, "CALENDAR_DAY"),
        }
    }
}
