/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformDuplicatedPartnerSettlementIdsError : 선택된 정산건 아이디에 중복이 있는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformDuplicatedPartnerSettlementIdsError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformDuplicatedPartnerSettlementIdsError {
    /// 선택된 정산건 아이디에 중복이 있는 경우
    pub fn new(r#type: String) -> PlatformDuplicatedPartnerSettlementIdsError {
        PlatformDuplicatedPartnerSettlementIdsError {
            r#type,
            message: None,
        }
    }
}
