/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformSettlementCycleMethodDaily : 매일 정산
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformSettlementCycleMethodDaily {
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PlatformSettlementCycleMethodDaily {
    /// 매일 정산
    pub fn new(r#type: String) -> PlatformSettlementCycleMethodDaily {
        PlatformSettlementCycleMethodDaily { r#type }
    }
}
