/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformBankAccountProvider : 제공자
/// 제공자
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformBankAccountProvider {
    #[serde(rename = "HYPHEN_DATA")]
    #[default]
    HyphenData,
    #[serde(rename = "HYPHEN_FIRM")]
    HyphenFirm,
    #[serde(rename = "DOZN")]
    Dozn,
    #[serde(rename = "MOCK")]
    Mock,
}

impl std::fmt::Display for PlatformBankAccountProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HyphenData => write!(f, "HYPHEN_DATA"),
            Self::HyphenFirm => write!(f, "HYPHEN_FIRM"),
            Self::Dozn => write!(f, "DOZN"),
            Self::Mock => write!(f, "MOCK"),
        }
    }
}
