/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformPaymentMethodMobile : 모바일
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPaymentMethodMobile {
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PlatformPaymentMethodMobile {
    /// 모바일
    pub fn new(r#type: String) -> PlatformPaymentMethodMobile {
        PlatformPaymentMethodMobile { r#type }
    }
}
