/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformPayment : 결제 정보
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PlatformPayment {
    #[serde(rename = "EXTERNAL")]
    External(Box<models::PlatformExternalPayment>),
    #[serde(rename = "PORT_ONE")]
    PortOne(Box<models::PlatformPortOnePayment>),
}

impl Default for PlatformPayment {
    fn default() -> Self {
        Self::External(Default::default())
    }
}
