/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformFixedAmountFee : 정액 수수료  총 금액에 무관하게 정해진 수수료 금액을 책정합니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformFixedAmountFee {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "amount")]
    pub amount: i64,
}

impl PlatformFixedAmountFee {
    /// 정액 수수료  총 금액에 무관하게 정해진 수수료 금액을 책정합니다.
    pub fn new(r#type: String, amount: i64) -> PlatformFixedAmountFee {
        PlatformFixedAmountFee { r#type, amount }
    }
}
