/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformArchivedAdditionalFeePolicyError : 보관된 추가 수수료 정책을 업데이트하려고 하는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformArchivedAdditionalFeePolicyError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformArchivedAdditionalFeePolicyError {
    /// 보관된 추가 수수료 정책을 업데이트하려고 하는 경우
    pub fn new(r#type: String) -> PlatformArchivedAdditionalFeePolicyError {
        PlatformArchivedAdditionalFeePolicyError {
            r#type,
            message: None,
        }
    }
}
