/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformCancellableAmountType : 금액 타입
/// 금액 타입
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformCancellableAmountType {
    #[serde(rename = "SUPPLY_WITH_VAT")]
    #[default]
    SupplyWithVat,
    #[serde(rename = "TAX_FREE")]
    TaxFree,
}

impl std::fmt::Display for PlatformCancellableAmountType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SupplyWithVat => write!(f, "SUPPLY_WITH_VAT"),
            Self::TaxFree => write!(f, "TAX_FREE"),
        }
    }
}
