/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformAccountTransferStatusStats {
    #[serde(rename = "prepared")]
    pub prepared: i64,
    #[serde(rename = "scheduled")]
    pub scheduled: i64,
    #[serde(rename = "cancelled")]
    pub cancelled: i64,
    #[serde(rename = "stopped")]
    pub stopped: i64,
    #[serde(rename = "processing")]
    pub processing: i64,
    #[serde(rename = "asyncProcessing")]
    pub async_processing: i64,
    #[serde(rename = "succeeded")]
    pub succeeded: i64,
    #[serde(rename = "failed")]
    pub failed: i64,
}

impl PlatformAccountTransferStatusStats {
    pub fn new(
        prepared: i64,
        scheduled: i64,
        cancelled: i64,
        stopped: i64,
        processing: i64,
        async_processing: i64,
        succeeded: i64,
        failed: i64,
    ) -> PlatformAccountTransferStatusStats {
        PlatformAccountTransferStatusStats {
            prepared,
            scheduled,
            cancelled,
            stopped,
            processing,
            async_processing,
            succeeded,
            failed,
        }
    }
}
