/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformSettlementCycleMethodWeekly : 매주 정해진 요일에 정산
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformSettlementCycleMethodWeekly {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "daysOfWeek")]
    pub days_of_week: Vec<models::DayOfWeek>,
}

impl PlatformSettlementCycleMethodWeekly {
    /// 매주 정해진 요일에 정산
    pub fn new(
        r#type: String,
        days_of_week: Vec<models::DayOfWeek>,
    ) -> PlatformSettlementCycleMethodWeekly {
        PlatformSettlementCycleMethodWeekly {
            r#type,
            days_of_week,
        }
    }
}
