/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformPaymentMethodEasyPayInput : 간편 결제 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPaymentMethodEasyPayInput {
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<models::EasyPayProvider>,
    #[serde(rename = "methodType", skip_serializing_if = "Option::is_none")]
    pub method_type: Option<models::EasyPayMethodType>,
}

impl PlatformPaymentMethodEasyPayInput {
    /// 간편 결제 입력 정보
    pub fn new() -> PlatformPaymentMethodEasyPayInput {
        PlatformPaymentMethodEasyPayInput {
            provider: None,
            method_type: None,
        }
    }
}
