/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformPortOnePayment : 포트원 결제 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPortOnePayment {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "storeId")]
    pub store_id: String,
    #[serde(rename = "channelKey")]
    pub channel_key: String,
    #[serde(rename = "orderName")]
    pub order_name: String,
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<Box<models::PlatformPaymentMethod>>,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "paidAt")]
    pub paid_at: chrono::DateTime<chrono::FixedOffset>,
}

impl PlatformPortOnePayment {
    /// 포트원 결제 정보
    pub fn new(
        r#type: String,
        id: String,
        store_id: String,
        channel_key: String,
        order_name: String,
        currency: models::Currency,
        paid_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> PlatformPortOnePayment {
        PlatformPortOnePayment {
            r#type,
            id,
            store_id,
            channel_key,
            order_name,
            method: None,
            currency,
            paid_at,
        }
    }
}
