/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformSettlementParameterValue : 플랫폼 정산 파라미터 값
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformSettlementParameterValue {
    #[serde(rename = "decimal")]
    pub decimal: i64,
    /// 정산 시 필요한 `decimalScale`이 지정되지 않은 경우 기본값으로 0을 사용합니다. 입력 가능한 법위는 0 ~ 5 입니다.
    #[serde(rename = "decimalScale", skip_serializing_if = "Option::is_none")]
    pub decimal_scale: Option<i32>,
}

impl PlatformSettlementParameterValue {
    /// 플랫폼 정산 파라미터 값
    pub fn new(decimal: i64) -> PlatformSettlementParameterValue {
        PlatformSettlementParameterValue {
            decimal,
            decimal_scale: None,
        }
    }
}
