/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformInsufficientDataToChangePartnerTypeError : 파트너 타입 수정에 필요한 데이터가 부족한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformInsufficientDataToChangePartnerTypeError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformInsufficientDataToChangePartnerTypeError {
    /// 파트너 타입 수정에 필요한 데이터가 부족한 경우
    pub fn new(r#type: String) -> PlatformInsufficientDataToChangePartnerTypeError {
        PlatformInsufficientDataToChangePartnerTypeError {
            r#type,
            message: None,
        }
    }
}
