/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformPaymentMethodInput : 결제 수단 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPaymentMethodInput {
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<serde_json::Value>,
    #[serde(rename = "transfer", skip_serializing_if = "Option::is_none")]
    pub transfer: Option<serde_json::Value>,
    #[serde(rename = "virtualAccount", skip_serializing_if = "Option::is_none")]
    pub virtual_account: Option<serde_json::Value>,
    #[serde(rename = "giftCertificate", skip_serializing_if = "Option::is_none")]
    pub gift_certificate: Option<serde_json::Value>,
    #[serde(rename = "mobile", skip_serializing_if = "Option::is_none")]
    pub mobile: Option<serde_json::Value>,
    #[serde(rename = "easyPay", skip_serializing_if = "Option::is_none")]
    pub easy_pay: Option<Box<models::PlatformPaymentMethodEasyPayInput>>,
}

impl PlatformPaymentMethodInput {
    /// 결제 수단 입력 정보
    pub fn new() -> PlatformPaymentMethodInput {
        PlatformPaymentMethodInput {
            card: None,
            transfer: None,
            virtual_account: None,
            gift_certificate: None,
            mobile: None,
            easy_pay: None,
        }
    }
}
