/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformReferencedCancelOrderTransfersExistError : 취소 정산건이 참조 중인 정산건이 포함된 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformReferencedCancelOrderTransfersExistError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "ids")]
    pub ids: Vec<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformReferencedCancelOrderTransfersExistError {
    /// 취소 정산건이 참조 중인 정산건이 포함된 경우
    pub fn new(
        r#type: String,
        ids: Vec<String>,
    ) -> PlatformReferencedCancelOrderTransfersExistError {
        PlatformReferencedCancelOrderTransfersExistError {
            r#type,
            ids,
            message: None,
        }
    }
}
