/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformSettlementSupplyWithVatAmountExceededPortOnePaymentError : 정산 요청 공급대가가 포트원 결제 내역의 공급대가를 초과한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformSettlementSupplyWithVatAmountExceededPortOnePaymentError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "registeredSettlementSupplyWithVatAmount")]
    pub registered_settlement_supply_with_vat_amount: i64,
    #[serde(rename = "requestSettlementSupplyWithVatAmount")]
    pub request_settlement_supply_with_vat_amount: i64,
    #[serde(rename = "portOneSupplyWithVatAmount")]
    pub port_one_supply_with_vat_amount: i64,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PlatformSettlementSupplyWithVatAmountExceededPortOnePaymentError {
    /// 정산 요청 공급대가가 포트원 결제 내역의 공급대가를 초과한 경우
    pub fn new(
        r#type: String,
        registered_settlement_supply_with_vat_amount: i64,
        request_settlement_supply_with_vat_amount: i64,
        port_one_supply_with_vat_amount: i64,
    ) -> PlatformSettlementSupplyWithVatAmountExceededPortOnePaymentError {
        PlatformSettlementSupplyWithVatAmountExceededPortOnePaymentError {
            r#type,
            registered_settlement_supply_with_vat_amount,
            request_settlement_supply_with_vat_amount,
            port_one_supply_with_vat_amount,
            message: None,
        }
    }
}
