/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PlatformSetting : 플랫폼 설정
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformSetting {
    #[serde(
        rename = "defaultWithdrawalMemo",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_withdrawal_memo: Option<String>,
    #[serde(rename = "defaultDepositMemo", skip_serializing_if = "Option::is_none")]
    pub default_deposit_memo: Option<String>,
    #[serde(rename = "supportsMultipleOrderTransfersPerPartner")]
    pub supports_multiple_order_transfers_per_partner: bool,
    #[serde(rename = "adjustSettlementDateAfterHolidayIfEarlier")]
    pub adjust_settlement_date_after_holiday_if_earlier: bool,
    #[serde(rename = "deductWht")]
    pub deduct_wht: bool,
    #[serde(rename = "settlementAmountType")]
    pub settlement_amount_type: models::SettlementAmountType,
    #[serde(rename = "isForTest")]
    pub is_for_test: bool,
    #[serde(rename = "manualSettlementPerTransfer")]
    pub manual_settlement_per_transfer: bool,
}

impl PlatformSetting {
    /// 플랫폼 설정
    pub fn new(
        supports_multiple_order_transfers_per_partner: bool,
        adjust_settlement_date_after_holiday_if_earlier: bool,
        deduct_wht: bool,
        settlement_amount_type: models::SettlementAmountType,
        is_for_test: bool,
        manual_settlement_per_transfer: bool,
    ) -> PlatformSetting {
        PlatformSetting {
            default_withdrawal_memo: None,
            default_deposit_memo: None,
            supports_multiple_order_transfers_per_partner,
            adjust_settlement_date_after_holiday_if_earlier,
            deduct_wht,
            settlement_amount_type,
            is_for_test,
            manual_settlement_per_transfer,
        }
    }
}
