/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformTransferSummaryExternalPayment {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "orderName", skip_serializing_if = "Option::is_none")]
    pub order_name: Option<String>,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "methodType", skip_serializing_if = "Option::is_none")]
    pub method_type: Option<models::PaymentMethodType>,
}

impl PlatformTransferSummaryExternalPayment {
    pub fn new(
        r#type: String,
        id: String,
        currency: models::Currency,
    ) -> PlatformTransferSummaryExternalPayment {
        PlatformTransferSummaryExternalPayment {
            r#type,
            id,
            order_name: None,
            currency,
            method_type: None,
        }
    }
}
