/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformPayout {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "graphqlId")]
    pub graphql_id: String,
    #[serde(rename = "bulkPayoutId")]
    pub bulk_payout_id: String,
    #[serde(rename = "bulkPayoutGraphqlId")]
    pub bulk_payout_graphql_id: String,
    #[serde(rename = "method")]
    pub method: models::PlatformPayoutMethod,
    #[serde(rename = "status")]
    pub status: models::PlatformPayoutStatus,
    #[serde(rename = "statusUpdatedAt")]
    pub status_updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
    #[serde(rename = "partner")]
    pub partner: Box<models::PlatformPartner>,
    #[serde(rename = "account")]
    pub account: Box<models::PlatformPayoutAccount>,
    #[serde(rename = "taxInvoiceId", skip_serializing_if = "Option::is_none")]
    pub tax_invoice_id: Option<String>,
    #[serde(rename = "taxInvoiceStatus")]
    pub tax_invoice_status: models::PlatformPayoutTaxInvoiceStatus,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "amount")]
    pub amount: i64,
    #[serde(rename = "supplyAmount")]
    pub supply_amount: i64,
    #[serde(rename = "taxFreeAmount")]
    pub tax_free_amount: i64,
    #[serde(rename = "vatAmount")]
    pub vat_amount: i64,
    #[serde(rename = "settlementAmount")]
    pub settlement_amount: i64,
    #[serde(rename = "settlementTaxFreeAmount")]
    pub settlement_tax_free_amount: i64,
    #[serde(rename = "incomeTaxAmount")]
    pub income_tax_amount: i64,
    #[serde(rename = "localIncomeTaxAmount")]
    pub local_income_tax_amount: i64,
    #[serde(rename = "withdrawalMemo", skip_serializing_if = "Option::is_none")]
    pub withdrawal_memo: Option<String>,
    #[serde(rename = "depositMemo", skip_serializing_if = "Option::is_none")]
    pub deposit_memo: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "scheduledAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "failReason", skip_serializing_if = "Option::is_none")]
    pub fail_reason: Option<String>,
    #[serde(rename = "deductWht")]
    pub deduct_wht: bool,
    #[serde(rename = "settlementAmountType")]
    pub settlement_amount_type: models::SettlementAmountType,
    #[serde(rename = "settlementStatement")]
    pub settlement_statement: Box<models::PlatformPayoutSettlementStatementSummary>,
}

impl PlatformPayout {
    pub fn new(
        id: String,
        graphql_id: String,
        bulk_payout_id: String,
        bulk_payout_graphql_id: String,
        method: models::PlatformPayoutMethod,
        status: models::PlatformPayoutStatus,
        status_updated_at: chrono::DateTime<chrono::FixedOffset>,
        partner: models::PlatformPartner,
        account: models::PlatformPayoutAccount,
        tax_invoice_status: models::PlatformPayoutTaxInvoiceStatus,
        currency: models::Currency,
        amount: i64,
        supply_amount: i64,
        tax_free_amount: i64,
        vat_amount: i64,
        settlement_amount: i64,
        settlement_tax_free_amount: i64,
        income_tax_amount: i64,
        local_income_tax_amount: i64,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        deduct_wht: bool,
        settlement_amount_type: models::SettlementAmountType,
        settlement_statement: models::PlatformPayoutSettlementStatementSummary,
    ) -> PlatformPayout {
        PlatformPayout {
            id,
            graphql_id,
            bulk_payout_id,
            bulk_payout_graphql_id,
            method,
            status,
            status_updated_at,
            memo: None,
            partner: Box::new(partner),
            account: Box::new(account),
            tax_invoice_id: None,
            tax_invoice_status,
            currency,
            amount,
            supply_amount,
            tax_free_amount,
            vat_amount,
            settlement_amount,
            settlement_tax_free_amount,
            income_tax_amount,
            local_income_tax_amount,
            withdrawal_memo: None,
            deposit_memo: None,
            created_at,
            scheduled_at: None,
            fail_reason: None,
            deduct_wht,
            settlement_amount_type,
            settlement_statement: Box::new(settlement_statement),
        }
    }
}
