/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformAccountHolder : 예금주 조회 성공 응답 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformAccountHolder {
    #[serde(rename = "holderName")]
    pub holder_name: String,
    #[serde(rename = "accountVerificationId")]
    pub account_verification_id: String,
}

impl PlatformAccountHolder {
    /// 예금주 조회 성공 응답 정보
    pub fn new(holder_name: String, account_verification_id: String) -> PlatformAccountHolder {
        PlatformAccountHolder {
            holder_name,
            account_verification_id,
        }
    }
}
