/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PlatformPartnerSettlementType : 정산 유형
/// 정산 유형
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PlatformPartnerSettlementType {
    #[serde(rename = "MANUAL")]
    #[default]
    Manual,
    #[serde(rename = "ORDER")]
    Order,
    #[serde(rename = "ORDER_CANCEL")]
    OrderCancel,
}

impl std::fmt::Display for PlatformPartnerSettlementType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Manual => write!(f, "MANUAL"),
            Self::Order => write!(f, "ORDER"),
            Self::OrderCancel => write!(f, "ORDER_CANCEL"),
        }
    }
}
