/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PortOneVersion : 포트원 버전
/// 포트원 버전
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PortOneVersion {
    #[serde(rename = "V1")]
    #[default]
    V1,
    #[serde(rename = "V2")]
    V2,
}

impl std::fmt::Display for PortOneVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::V1 => write!(f, "V1"),
            Self::V2 => write!(f, "V2"),
        }
    }
}
