/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PromotionPayMethodDoesNotMatchError : 결제수단이 프로모션에 지정된 것과 일치하지 않는 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromotionPayMethodDoesNotMatchError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PromotionPayMethodDoesNotMatchError {
    /// 결제수단이 프로모션에 지정된 것과 일치하지 않는 경우
    pub fn new(r#type: String) -> PromotionPayMethodDoesNotMatchError {
        PromotionPayMethodDoesNotMatchError {
            r#type,
            message: None,
        }
    }
}
