/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PromotionRecoverOptionRecover : 결제 취소 시 프로모션 예산 복구
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromotionRecoverOptionRecover {
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PromotionRecoverOptionRecover {
    /// 결제 취소 시 프로모션 예산 복구
    pub fn new(r#type: String) -> PromotionRecoverOptionRecover {
        PromotionRecoverOptionRecover { r#type }
    }
}
