/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PromotionRecoverOption {
    #[serde(rename = "NO_RECOVER")]
    NoRecover(Box<models::PromotionRecoverOptionNoRecover>),
    #[serde(rename = "RECOVER")]
    Recover(Box<models::PromotionRecoverOptionRecover>),
}

impl Default for PromotionRecoverOption {
    fn default() -> Self {
        Self::NoRecover(Default::default())
    }
}
