/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PromotionCardCompany : 프로모션 적용 가능한 카드사
/// 프로모션 적용 가능한 카드사
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum PromotionCardCompany {
    #[serde(rename = "WOORI_CARD")]
    #[default]
    WooriCard,
    #[serde(rename = "BC_CARD")]
    BcCard,
    #[serde(rename = "SAMSUNG_CARD")]
    SamsungCard,
    #[serde(rename = "SHINHAN_CARD")]
    ShinhanCard,
    #[serde(rename = "HYUNDAI_CARD")]
    HyundaiCard,
    #[serde(rename = "LOTTE_CARD")]
    LotteCard,
    #[serde(rename = "NH_CARD")]
    NhCard,
    #[serde(rename = "HANA_CARD")]
    HanaCard,
    #[serde(rename = "KOOKMIN_CARD")]
    KookminCard,
}

impl std::fmt::Display for PromotionCardCompany {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::WooriCard => write!(f, "WOORI_CARD"),
            Self::BcCard => write!(f, "BC_CARD"),
            Self::SamsungCard => write!(f, "SAMSUNG_CARD"),
            Self::ShinhanCard => write!(f, "SHINHAN_CARD"),
            Self::HyundaiCard => write!(f, "HYUNDAI_CARD"),
            Self::LotteCard => write!(f, "LOTTE_CARD"),
            Self::NhCard => write!(f, "NH_CARD"),
            Self::HanaCard => write!(f, "HANA_CARD"),
            Self::KookminCard => write!(f, "KOOKMIN_CARD"),
        }
    }
}
