/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PromotionRecoverOptionNoRecover : 결제 취소 시 프로모션 예산 미복구
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromotionRecoverOptionNoRecover {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "spareBudget", skip_serializing_if = "Option::is_none")]
    pub spare_budget: Option<Box<models::PromotionSpareBudget>>,
}

impl PromotionRecoverOptionNoRecover {
    /// 결제 취소 시 프로모션 예산 미복구
    pub fn new(r#type: String) -> PromotionRecoverOptionNoRecover {
        PromotionRecoverOptionNoRecover {
            r#type,
            spare_budget: None,
        }
    }
}
