/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromotionAmountDiscountScheme {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "amount")]
    pub amount: i64,
}

impl PromotionAmountDiscountScheme {
    pub fn new(r#type: String, amount: i64) -> PromotionAmountDiscountScheme {
        PromotionAmountDiscountScheme { r#type, amount }
    }
}
