/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// PromotionDiscountPartition : 금액 구간별 프로모션 할인 정책
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromotionDiscountPartition {
    #[serde(rename = "amountFrom")]
    pub amount_from: i64,
    #[serde(rename = "scheme")]
    pub scheme: Box<models::PromotionDiscountScheme>,
}

impl PromotionDiscountPartition {
    /// 금액 구간별 프로모션 할인 정책
    pub fn new(
        amount_from: i64,
        scheme: models::PromotionDiscountScheme,
    ) -> PromotionDiscountPartition {
        PromotionDiscountPartition {
            amount_from,
            scheme: Box::new(scheme),
        }
    }
}
