/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PromotionDiscountScheme {
    #[serde(rename = "AMOUNT")]
    Amount(Box<models::PromotionAmountDiscountScheme>),
    #[serde(rename = "PERCENT")]
    Percent(Box<models::PromotionPercentDiscountScheme>),
}

impl Default for PromotionDiscountScheme {
    fn default() -> Self {
        Self::Amount(Default::default())
    }
}
