/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ReadyPayment : 준비 상태 건
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadyPayment {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "id")]
    pub id: String,
    /// V1 결제 건의 경우 imp_uid에 해당합니다.
    #[serde(rename = "transactionId")]
    pub transaction_id: String,
    #[serde(rename = "merchantId")]
    pub merchant_id: String,
    #[serde(rename = "storeId")]
    pub store_id: String,
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<Box<models::PaymentMethod>>,
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Box<models::SelectedChannel>>,
    #[serde(rename = "channelGroup", skip_serializing_if = "Option::is_none")]
    pub channel_group: Option<Box<models::ChannelGroupSummary>>,
    #[serde(rename = "version")]
    pub version: models::PortOneVersion,
    /// 결제 예약을 이용한 경우에만 존재
    #[serde(rename = "scheduleId", skip_serializing_if = "Option::is_none")]
    pub schedule_id: Option<String>,
    /// 빌링키 결제인 경우에만 존재
    #[serde(rename = "billingKey", skip_serializing_if = "Option::is_none")]
    pub billing_key: Option<String>,
    #[serde(rename = "webhooks", skip_serializing_if = "Option::is_none")]
    pub webhooks: Option<Vec<models::PaymentWebhook>>,
    #[serde(rename = "requestedAt")]
    pub requested_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "statusChangedAt")]
    pub status_changed_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "orderName")]
    pub order_name: String,
    #[serde(rename = "amount")]
    pub amount: Box<models::PaymentAmount>,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "customer")]
    pub customer: Box<models::Customer>,
    #[serde(rename = "origin")]
    pub origin: Box<models::PaymentOrigin>,
    #[serde(rename = "promotionId", skip_serializing_if = "Option::is_none")]
    pub promotion_id: Option<String>,
    #[serde(rename = "isCulturalExpense", skip_serializing_if = "Option::is_none")]
    pub is_cultural_expense: Option<bool>,
    #[serde(rename = "escrow", skip_serializing_if = "Option::is_none")]
    pub escrow: Option<Box<models::PaymentEscrow>>,
    #[serde(rename = "products", skip_serializing_if = "Option::is_none")]
    pub products: Option<Vec<models::PaymentProduct>>,
    #[serde(rename = "productCount", skip_serializing_if = "Option::is_none")]
    pub product_count: Option<i32>,
    #[serde(rename = "customData", skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<models::Country>,
}

impl ReadyPayment {
    /// 준비 상태 건
    pub fn new(
        status: String,
        id: String,
        transaction_id: String,
        merchant_id: String,
        store_id: String,
        version: models::PortOneVersion,
        requested_at: chrono::DateTime<chrono::FixedOffset>,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        status_changed_at: chrono::DateTime<chrono::FixedOffset>,
        order_name: String,
        amount: models::PaymentAmount,
        currency: models::Currency,
        customer: models::Customer,
        origin: models::PaymentOrigin,
    ) -> ReadyPayment {
        ReadyPayment {
            status,
            id,
            transaction_id,
            merchant_id,
            store_id,
            method: None,
            channel: None,
            channel_group: None,
            version,
            schedule_id: None,
            billing_key: None,
            webhooks: None,
            requested_at,
            updated_at,
            status_changed_at,
            order_name,
            amount: Box::new(amount),
            currency,
            customer: Box::new(customer),
            origin: Box::new(origin),
            promotion_id: None,
            is_cultural_expense: None,
            escrow: None,
            products: None,
            product_count: None,
            custom_data: None,
            country: None,
        }
    }
}
