/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// RecoverPlatformContractResponse : 계약 복원 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecoverPlatformContractResponse {
    #[serde(rename = "contract")]
    pub contract: Box<models::PlatformContract>,
}

impl RecoverPlatformContractResponse {
    /// 계약 복원 성공 응답
    pub fn new(contract: models::PlatformContract) -> RecoverPlatformContractResponse {
        RecoverPlatformContractResponse {
            contract: Box::new(contract),
        }
    }
}
