/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// RecoverPlatformAdditionalFeePolicyResponse : 추가 수수료 정책 복원 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecoverPlatformAdditionalFeePolicyResponse {
    #[serde(rename = "additionalFeePolicy")]
    pub additional_fee_policy: Box<models::PlatformAdditionalFeePolicy>,
}

impl RecoverPlatformAdditionalFeePolicyResponse {
    /// 추가 수수료 정책 복원 성공 응답
    pub fn new(
        additional_fee_policy: models::PlatformAdditionalFeePolicy,
    ) -> RecoverPlatformAdditionalFeePolicyResponse {
        RecoverPlatformAdditionalFeePolicyResponse {
            additional_fee_policy: Box::new(additional_fee_policy),
        }
    }
}
