/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// RefreshTokenResponse : 토큰 재발급 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshTokenResponse {
    /// 30분의 유효기간을 가지고 있습니다.
    #[serde(rename = "accessToken")]
    pub access_token: String,
    /// 하루의 유효기간을 가지고 있으며, 리프레시 토큰을 통해 유효기간이 연장된 새로운 엑세스 토큰을 발급받을 수 있습니다. 동일한 유저가 로그인 또는 토큰 재발급을 진행할 때마다 기존에 발급된 리프레시 토큰은 즉시 만료되므로 API 사용에 유의해주세요.
    #[serde(rename = "refreshToken")]
    pub refresh_token: String,
}

impl RefreshTokenResponse {
    /// 토큰 재발급 성공 응답
    pub fn new(access_token: String, refresh_token: String) -> RefreshTokenResponse {
        RefreshTokenResponse {
            access_token,
            refresh_token,
        }
    }
}
