/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// RefuseB2bTaxInvoiceRequestBody : 세금계산서 역발행 요청 거부 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefuseB2bTaxInvoiceRequestBody {
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
}

impl RefuseB2bTaxInvoiceRequestBody {
    /// 세금계산서 역발행 요청 거부 정보
    pub fn new() -> RefuseB2bTaxInvoiceRequestBody {
        RefuseB2bTaxInvoiceRequestBody { memo: None }
    }
}
