/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// RegisterStoreReceiptBodyItem : 하위 상점 거래 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterStoreReceiptBodyItem {
    #[serde(rename = "storeBusinessRegistrationNumber")]
    pub store_business_registration_number: String,
    #[serde(rename = "storeName")]
    pub store_name: String,
    #[serde(rename = "totalAmount")]
    pub total_amount: i64,
    #[serde(rename = "taxFreeAmount", skip_serializing_if = "Option::is_none")]
    pub tax_free_amount: Option<i64>,
    #[serde(rename = "vatAmount", skip_serializing_if = "Option::is_none")]
    pub vat_amount: Option<i64>,
    #[serde(rename = "supplyAmount", skip_serializing_if = "Option::is_none")]
    pub supply_amount: Option<i64>,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
}

impl RegisterStoreReceiptBodyItem {
    /// 하위 상점 거래 정보
    pub fn new(
        store_business_registration_number: String,
        store_name: String,
        total_amount: i64,
        currency: models::Currency,
    ) -> RegisterStoreReceiptBodyItem {
        RegisterStoreReceiptBodyItem {
            store_business_registration_number,
            store_name,
            total_amount,
            tax_free_amount: None,
            vat_amount: None,
            supply_amount: None,
            currency,
        }
    }
}
