/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// RejectedPaymentEscrow : 구매 거절
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RejectedPaymentEscrow {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "company")]
    pub company: String,
    #[serde(rename = "invoiceNumber")]
    pub invoice_number: String,
    #[serde(rename = "sentAt", skip_serializing_if = "Option::is_none")]
    pub sent_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "appliedAt", skip_serializing_if = "Option::is_none")]
    pub applied_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl RejectedPaymentEscrow {
    /// 구매 거절
    pub fn new(status: String, company: String, invoice_number: String) -> RejectedPaymentEscrow {
        RejectedPaymentEscrow {
            status,
            company,
            invoice_number,
            sent_at: None,
            applied_at: None,
        }
    }
}
