/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ReschedulePlatformPartnerBody : 파트너 예약 업데이트 재설정을 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReschedulePlatformPartnerBody {
    #[serde(rename = "update")]
    pub update: Box<models::UpdatePlatformPartnerBody>,
    #[serde(rename = "appliedAt")]
    pub applied_at: chrono::DateTime<chrono::FixedOffset>,
}

impl ReschedulePlatformPartnerBody {
    /// 파트너 예약 업데이트 재설정을 위한 입력 정보
    pub fn new(
        update: models::UpdatePlatformPartnerBody,
        applied_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> ReschedulePlatformPartnerBody {
        ReschedulePlatformPartnerBody {
            update: Box::new(update),
            applied_at,
        }
    }
}
