/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ReschedulePlatformAdditionalFeePolicyResponse : 추가 수수료 정책 예약 업데이트 재설정 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReschedulePlatformAdditionalFeePolicyResponse {
    #[serde(rename = "scheduledAdditionalFeePolicy")]
    pub scheduled_additional_fee_policy: Box<models::PlatformAdditionalFeePolicy>,
}

impl ReschedulePlatformAdditionalFeePolicyResponse {
    /// 추가 수수료 정책 예약 업데이트 재설정 성공 응답
    pub fn new(
        scheduled_additional_fee_policy: models::PlatformAdditionalFeePolicy,
    ) -> ReschedulePlatformAdditionalFeePolicyResponse {
        ReschedulePlatformAdditionalFeePolicyResponse {
            scheduled_additional_fee_policy: Box::new(scheduled_additional_fee_policy),
        }
    }
}
