/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ReschedulePlatformDiscountSharePolicyResponse : 할인 분담 정책 예약 업데이트 재설정 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReschedulePlatformDiscountSharePolicyResponse {
    #[serde(rename = "scheduledDiscountSharePolicy")]
    pub scheduled_discount_share_policy: Box<models::PlatformDiscountSharePolicy>,
}

impl ReschedulePlatformDiscountSharePolicyResponse {
    /// 할인 분담 정책 예약 업데이트 재설정 성공 응답
    pub fn new(
        scheduled_discount_share_policy: models::PlatformDiscountSharePolicy,
    ) -> ReschedulePlatformDiscountSharePolicyResponse {
        ReschedulePlatformDiscountSharePolicyResponse {
            scheduled_discount_share_policy: Box::new(scheduled_discount_share_policy),
        }
    }
}
