/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ReschedulePlatformPartnerResponse : 파트너 예약 업데이트 재설정 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReschedulePlatformPartnerResponse {
    #[serde(rename = "scheduledPartner")]
    pub scheduled_partner: Box<models::PlatformPartner>,
}

impl ReschedulePlatformPartnerResponse {
    /// 파트너 예약 업데이트 재설정 성공 응답
    pub fn new(scheduled_partner: models::PlatformPartner) -> ReschedulePlatformPartnerResponse {
        ReschedulePlatformPartnerResponse {
            scheduled_partner: Box::new(scheduled_partner),
        }
    }
}
