/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ReschedulePlatformContractResponse : 계약 예약 업데이트 재설정 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReschedulePlatformContractResponse {
    #[serde(rename = "scheduledContract")]
    pub scheduled_contract: Box<models::PlatformContract>,
}

impl ReschedulePlatformContractResponse {
    /// 계약 예약 업데이트 재설정 성공 응답
    pub fn new(scheduled_contract: models::PlatformContract) -> ReschedulePlatformContractResponse {
        ReschedulePlatformContractResponse {
            scheduled_contract: Box::new(scheduled_contract),
        }
    }
}
