/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// ReschedulePlatformAdditionalFeePolicyBody : 추가 수수료 정책 예약 업데이트 재설정을 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReschedulePlatformAdditionalFeePolicyBody {
    #[serde(rename = "update")]
    pub update: Box<models::UpdatePlatformAdditionalFeePolicyBody>,
    #[serde(rename = "appliedAt")]
    pub applied_at: chrono::DateTime<chrono::FixedOffset>,
}

impl ReschedulePlatformAdditionalFeePolicyBody {
    /// 추가 수수료 정책 예약 업데이트 재설정을 위한 입력 정보
    pub fn new(
        update: models::UpdatePlatformAdditionalFeePolicyBody,
        applied_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> ReschedulePlatformAdditionalFeePolicyBody {
        ReschedulePlatformAdditionalFeePolicyBody {
            update: Box::new(update),
            applied_at,
        }
    }
}
