/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ResendIdentityVerificationError {
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "IDENTITY_VERIFICATION_ALREADY_VERIFIED")]
    IdentityVerificationAlreadyVerified(Box<models::IdentityVerificationAlreadyVerifiedError>),
    #[serde(rename = "IDENTITY_VERIFICATION_NOT_FOUND")]
    IdentityVerificationNotFound(Box<models::IdentityVerificationNotFoundError>),
    #[serde(rename = "IDENTITY_VERIFICATION_NOT_SENT")]
    IdentityVerificationNotSent(Box<models::IdentityVerificationNotSentError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PG_PROVIDER")]
    PgProvider(Box<models::PgProviderError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for ResendIdentityVerificationError {
    fn default() -> Self {
        Self::Forbidden(Default::default())
    }
}
