/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ResendWebhookBody : 웹훅 재발송을 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResendWebhookBody {
    /// 접근 권한이 있는 상점 아이디만 입력 가능하며, 미입력시 인증 정보의 상점 아이디를 사용합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    /// 입력하지 않으면 결제 건의 가장 최근 웹훅 아이디가 기본 적용됩니다
    #[serde(rename = "webhookId", skip_serializing_if = "Option::is_none")]
    pub webhook_id: Option<String>,
}

impl ResendWebhookBody {
    /// 웹훅 재발송을 위한 입력 정보
    pub fn new() -> ResendWebhookBody {
        ResendWebhookBody {
            store_id: None,
            webhook_id: None,
        }
    }
}
