/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ResendWebhookError {
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "MAX_WEBHOOK_RETRY_COUNT_REACHED")]
    MaxWebhookRetryCountReached(Box<models::MaxWebhookRetryCountReachedError>),
    #[serde(rename = "PAYMENT_NOT_FOUND")]
    PaymentNotFound(Box<models::PaymentNotFoundError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
    #[serde(rename = "WEBHOOK_NOT_FOUND")]
    WebhookNotFound(Box<models::WebhookNotFoundError>),
}

impl Default for ResendWebhookError {
    fn default() -> Self {
        Self::Forbidden(Default::default())
    }
}
