/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// RevokePaymentSchedulesResponse : 결제 예약 건 취소 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokePaymentSchedulesResponse {
    #[serde(rename = "revokedScheduleIds")]
    pub revoked_schedule_ids: Vec<String>,
    #[serde(rename = "revokedAt", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl RevokePaymentSchedulesResponse {
    /// 결제 예약 건 취소 성공 응답
    pub fn new(revoked_schedule_ids: Vec<String>) -> RevokePaymentSchedulesResponse {
        RevokePaymentSchedulesResponse {
            revoked_schedule_ids,
            revoked_at: None,
        }
    }
}
