/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// RevokePaymentSchedulesBody : 결제 예약 건 취소 요청 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokePaymentSchedulesBody {
    /// 접근 권한이 있는 상점 아이디만 입력 가능하며, 미입력시 인증 정보의 상점 아이디를 사용합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    #[serde(rename = "billingKey", skip_serializing_if = "Option::is_none")]
    pub billing_key: Option<String>,
    #[serde(rename = "scheduleIds", skip_serializing_if = "Option::is_none")]
    pub schedule_ids: Option<Vec<String>>,
}

impl RevokePaymentSchedulesBody {
    /// 결제 예약 건 취소 요청 입력 정보
    pub fn new() -> RevokePaymentSchedulesBody {
        RevokePaymentSchedulesBody {
            store_id: None,
            billing_key: None,
            schedule_ids: None,
        }
    }
}
