/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum RevokePaymentSchedulesError {
    #[serde(rename = "BILLING_KEY_ALREADY_DELETED")]
    BillingKeyAlreadyDeleted(Box<models::BillingKeyAlreadyDeletedError>),
    #[serde(rename = "BILLING_KEY_NOT_FOUND")]
    BillingKeyNotFound(Box<models::BillingKeyNotFoundError>),
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PAYMENT_SCHEDULE_ALREADY_PROCESSED")]
    PaymentScheduleAlreadyProcessed(Box<models::PaymentScheduleAlreadyProcessedError>),
    #[serde(rename = "PAYMENT_SCHEDULE_ALREADY_REVOKED")]
    PaymentScheduleAlreadyRevoked(Box<models::PaymentScheduleAlreadyRevokedError>),
    #[serde(rename = "PAYMENT_SCHEDULE_NOT_FOUND")]
    PaymentScheduleNotFound(Box<models::PaymentScheduleNotFoundError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for RevokePaymentSchedulesError {
    fn default() -> Self {
        Self::BillingKeyAlreadyDeleted(Default::default())
    }
}
