/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchedulePlatformPartnersBody {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::PlatformPartnerFilterInput>>,
    #[serde(rename = "update")]
    pub update: Box<models::SchedulePlatformPartnersBodyUpdate>,
    #[serde(rename = "appliedAt")]
    pub applied_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SchedulePlatformPartnersBody {
    pub fn new(
        update: models::SchedulePlatformPartnersBodyUpdate,
        applied_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> SchedulePlatformPartnersBody {
        SchedulePlatformPartnersBody {
            filter: None,
            update: Box::new(update),
            applied_at,
        }
    }
}
