/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ScheduleContractError {
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PLATFORM_ARCHIVED_CONTRACT")]
    PlatformArchivedContract(Box<models::PlatformArchivedContractError>),
    #[serde(rename = "PLATFORM_CONTRACT_NOT_FOUND")]
    PlatformContractNotFound(Box<models::PlatformContractNotFoundError>),
    #[serde(rename = "PLATFORM_CONTRACT_SCHEDULE_ALREADY_EXISTS")]
    PlatformContractScheduleAlreadyExists(Box<models::PlatformContractScheduleAlreadyExistsError>),
    #[serde(rename = "PLATFORM_NOT_ENABLED")]
    PlatformNotEnabled(Box<models::PlatformNotEnabledError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for ScheduleContractError {
    fn default() -> Self {
        Self::Forbidden(Default::default())
    }
}
