/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SchedulePlatformPartnersError {
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PLATFORM_ARCHIVED_PARTNERS_CANNOT_BE_SCHEDULED")]
    PlatformArchivedPartnersCannotBeScheduled(
        Box<models::PlatformArchivedPartnersCannotBeScheduledError>,
    ),
    #[serde(rename = "PLATFORM_CONTRACT_NOT_FOUND")]
    PlatformContractNotFound(Box<models::PlatformContractNotFoundError>),
    #[serde(rename = "PLATFORM_MEMBER_COMPANY_CONNECTED_PARTNERS_CANNOT_BE_SCHEDULED")]
    PlatformMemberCompanyConnectedPartnersCannotBeScheduled(
        Box<models::PlatformMemberCompanyConnectedPartnersCannotBeScheduledError>,
    ),
    #[serde(rename = "PLATFORM_NOT_ENABLED")]
    PlatformNotEnabled(Box<models::PlatformNotEnabledError>),
    #[serde(rename = "PLATFORM_PARTNER_SCHEDULES_ALREADY_EXIST")]
    PlatformPartnerSchedulesAlreadyExist(Box<models::PlatformPartnerSchedulesAlreadyExistError>),
    #[serde(rename = "PLATFORM_USER_DEFINED_PROPERTY_NOT_FOUND")]
    PlatformUserDefinedPropertyNotFound(Box<models::PlatformUserDefinedPropertyNotFoundError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for SchedulePlatformPartnersError {
    fn default() -> Self {
        Self::Forbidden(Default::default())
    }
}
