/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ScheduleAdditionalFeePolicyError {
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "PLATFORM_ADDITIONAL_FEE_POLICY_NOT_FOUND")]
    PlatformAdditionalFeePolicyNotFound(Box<models::PlatformAdditionalFeePolicyNotFoundError>),
    #[serde(rename = "PLATFORM_ADDITIONAL_FEE_POLICY_SCHEDULE_ALREADY_EXISTS")]
    PlatformAdditionalFeePolicyScheduleAlreadyExists(
        Box<models::PlatformAdditionalFeePolicyScheduleAlreadyExistsError>,
    ),
    #[serde(rename = "PLATFORM_ARCHIVED_ADDITIONAL_FEE_POLICY")]
    PlatformArchivedAdditionalFeePolicy(Box<models::PlatformArchivedAdditionalFeePolicyError>),
    #[serde(rename = "PLATFORM_NOT_ENABLED")]
    PlatformNotEnabled(Box<models::PlatformNotEnabledError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for ScheduleAdditionalFeePolicyError {
    fn default() -> Self {
        Self::Forbidden(Default::default())
    }
}
