/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// SelectedChannel : (결제, 본인인증 등에) 선택된 채널 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectedChannel {
    #[serde(rename = "type")]
    pub r#type: models::SelectedChannelType,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "pgProvider")]
    pub pg_provider: models::PgProvider,
    #[serde(rename = "pgMerchantId")]
    pub pg_merchant_id: String,
}

impl SelectedChannel {
    /// (결제, 본인인증 등에) 선택된 채널 정보
    pub fn new(
        r#type: models::SelectedChannelType,
        pg_provider: models::PgProvider,
        pg_merchant_id: String,
    ) -> SelectedChannel {
        SelectedChannel {
            r#type,
            id: None,
            key: None,
            name: None,
            pg_provider,
            pg_merchant_id,
        }
    }
}
