/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// SendIdentityVerificationBody : 본인인증 요청을 위한 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendIdentityVerificationBody {
    /// 접근 권한이 있는 상점 아이디만 입력 가능하며, 미입력시 인증 정보의 상점 아이디를 사용합니다.
    #[serde(rename = "storeId", skip_serializing_if = "Option::is_none")]
    pub store_id: Option<String>,
    #[serde(rename = "channelKey")]
    pub channel_key: String,
    #[serde(rename = "customer")]
    pub customer: Box<models::SendIdentityVerificationBodyCustomer>,
    #[serde(rename = "customData", skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<String>,
    #[serde(rename = "bypass", skip_serializing_if = "Option::is_none")]
    pub bypass: Option<serde_json::Value>,
    #[serde(rename = "operator")]
    pub operator: models::IdentityVerificationOperator,
    #[serde(rename = "method")]
    pub method: models::IdentityVerificationMethod,
}

impl SendIdentityVerificationBody {
    /// 본인인증 요청을 위한 입력 정보
    pub fn new(
        channel_key: String,
        customer: models::SendIdentityVerificationBodyCustomer,
        operator: models::IdentityVerificationOperator,
        method: models::IdentityVerificationMethod,
    ) -> SendIdentityVerificationBody {
        SendIdentityVerificationBody {
            store_id: None,
            channel_key,
            customer: Box::new(customer),
            custom_data: None,
            bypass: None,
            operator,
            method,
        }
    }
}
