/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// SeparatedAddressInput : 분리 형식 주소 입력 정보
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeparatedAddressInput {
    #[serde(rename = "addressLine1")]
    pub address_line1: String,
    #[serde(rename = "addressLine2")]
    pub address_line2: String,
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(rename = "province", skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<models::Country>,
}

impl SeparatedAddressInput {
    /// 분리 형식 주소 입력 정보
    pub fn new(address_line1: String, address_line2: String) -> SeparatedAddressInput {
        SeparatedAddressInput {
            address_line1,
            address_line2,
            city: None,
            province: None,
            country: None,
        }
    }
}
