/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// SessionExpiredError : 결제 세션이 만료된 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionExpiredError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl SessionExpiredError {
    /// 결제 세션이 만료된 경우
    pub fn new(r#type: String) -> SessionExpiredError {
        SessionExpiredError {
            r#type,
            message: None,
        }
    }
}
