/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// SumOfPartsExceedsTotalAmountError : 면세 금액 등 하위 항목들의 합이 전체 결제 금액을 초과한 경우
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SumOfPartsExceedsTotalAmountError {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl SumOfPartsExceedsTotalAmountError {
    /// 면세 금액 등 하위 항목들의 합이 전체 결제 금액을 초과한 경우
    pub fn new(r#type: String) -> SumOfPartsExceedsTotalAmountError {
        SumOfPartsExceedsTotalAmountError {
            r#type,
            message: None,
        }
    }
}
