/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// UpdateB2bCounterpartyBody : 거래처 정보 수정 요청
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateB2bCounterpartyBody {
    #[serde(rename = "counterparty")]
    pub counterparty: Box<models::B2bCounterpartyInput>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<models::B2bCounterpartyCreateOptions>>,
}

impl UpdateB2bCounterpartyBody {
    /// 거래처 정보 수정 요청
    pub fn new(counterparty: models::B2bCounterpartyInput) -> UpdateB2bCounterpartyBody {
        UpdateB2bCounterpartyBody {
            counterparty: Box::new(counterparty),
            options: None,
        }
    }
}
