/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum UpdateB2bCounterpartyError {
    #[serde(rename = "B2B_COUNTERPARTY_BRN_MODIFICATION_NOT_ALLOWED")]
    B2BCounterpartyBrnModificationNotAllowed(
        Box<models::B2bCounterpartyBrnModificationNotAllowedError>,
    ),
    #[serde(rename = "B2B_COUNTERPARTY_MISSING_REQUIRED_FIELDS")]
    B2BCounterpartyMissingRequiredFields(Box<models::B2bCounterpartyMissingRequiredFieldsError>),
    #[serde(rename = "B2B_COUNTERPARTY_NOT_FOUND")]
    B2BCounterpartyNotFound(Box<models::B2bCounterpartyNotFoundError>),
    #[serde(rename = "B2B_COUNTERPARTY_PARTNER_NOT_UPDATABLE")]
    B2BCounterpartyPartnerNotUpdatable(Box<models::B2bCounterpartyPartnerNotUpdatableError>),
    #[serde(rename = "B2B_COUNTERPARTY_TOO_MANY_ADDITIONAL_CONTACTS")]
    B2BCounterpartyTooManyAdditionalContacts(
        Box<models::B2bCounterpartyTooManyAdditionalContactsError>,
    ),
    #[serde(rename = "B2B_COUNTERPARTY_VERIFICATION_BRN_MISMATCH")]
    B2BCounterpartyVerificationBrnMismatch(
        Box<models::B2bCounterpartyVerificationBrnMismatchError>,
    ),
    #[serde(rename = "B2B_COUNTERPARTY_VERIFICATION_INVALID")]
    B2BCounterpartyVerificationInvalid(Box<models::B2bCounterpartyVerificationInvalidError>),
    #[serde(rename = "B2B_COUNTERPARTY_VERIFICATION_NOT_FOUND")]
    B2BCounterpartyVerificationNotFound(Box<models::B2bCounterpartyVerificationNotFoundError>),
    #[serde(rename = "B2B_COUNTERPARTY_VERIFICATION_TYPE_MISMATCH")]
    B2BCounterpartyVerificationTypeMismatch(
        Box<models::B2bCounterpartyVerificationTypeMismatchError>,
    ),
    #[serde(rename = "B2B_EXTERNAL_SERVICE")]
    B2BExternalService(Box<models::B2bExternalServiceError>),
    #[serde(rename = "B2B_NOT_ENABLED")]
    B2BNotEnabled(Box<models::B2bNotEnabledError>),
    #[serde(rename = "FORBIDDEN")]
    Forbidden(Box<models::ForbiddenError>),
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest(Box<models::InvalidRequestError>),
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized(Box<models::UnauthorizedError>),
}

impl Default for UpdateB2bCounterpartyError {
    fn default() -> Self {
        Self::B2BCounterpartyBrnModificationNotAllowed(Default::default())
    }
}
