/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// UpdatePlatformAdditionalFeePolicyResponse : 추가 수수료 정책 업데이트 성공 응답
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePlatformAdditionalFeePolicyResponse {
    #[serde(rename = "additionalFeePolicy")]
    pub additional_fee_policy: Box<models::PlatformAdditionalFeePolicy>,
}

impl UpdatePlatformAdditionalFeePolicyResponse {
    /// 추가 수수료 정책 업데이트 성공 응답
    pub fn new(
        additional_fee_policy: models::PlatformAdditionalFeePolicy,
    ) -> UpdatePlatformAdditionalFeePolicyResponse {
        UpdatePlatformAdditionalFeePolicyResponse {
            additional_fee_policy: Box::new(additional_fee_policy),
        }
    }
}
