/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// UpdatePlatformDiscountSharePolicyBody : 할인 분담 정책 업데이트를 위한 입력 정보  값이 명시되지 않은 필드는 업데이트하지 않습니다.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePlatformDiscountSharePolicyBody {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 파트너가 분담할 할인금액의 비율을 의미하는 밀리 퍼센트 단위 (10^-5) 의 음이 아닌 정수이며, 파트너가 부담할 금액은 `할인금액 * partnerShareRate * 10^5` 로 책정합니다.
    #[serde(rename = "partnerShareRate", skip_serializing_if = "Option::is_none")]
    pub partner_share_rate: Option<i32>,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
}

impl UpdatePlatformDiscountSharePolicyBody {
    /// 할인 분담 정책 업데이트를 위한 입력 정보  값이 명시되지 않은 필드는 업데이트하지 않습니다.
    pub fn new() -> UpdatePlatformDiscountSharePolicyBody {
        UpdatePlatformDiscountSharePolicyBody {
            name: None,
            partner_share_rate: None,
            memo: None,
        }
    }
}
