/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// UpdatePlatformSettingResponse : 플랫폼 설정 업데이트 결과
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePlatformSettingResponse {
    #[serde(rename = "setting")]
    pub setting: Box<models::PlatformSetting>,
}

impl UpdatePlatformSettingResponse {
    /// 플랫폼 설정 업데이트 결과
    pub fn new(setting: models::PlatformSetting) -> UpdatePlatformSettingResponse {
        UpdatePlatformSettingResponse {
            setting: Box::new(setting),
        }
    }
}
