/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePlatformPartnerBodyTypeBusiness {
    #[serde(rename = "companyName", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    #[serde(rename = "taxationType", skip_serializing_if = "Option::is_none")]
    pub taxation_type: Option<models::PlatformPartnerTaxationType>,
    #[serde(
        rename = "businessRegistrationNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_registration_number: Option<String>,
    #[serde(rename = "representativeName", skip_serializing_if = "Option::is_none")]
    pub representative_name: Option<String>,
    #[serde(rename = "companyAddress", skip_serializing_if = "Option::is_none")]
    pub company_address: Option<String>,
    #[serde(rename = "businessType", skip_serializing_if = "Option::is_none")]
    pub business_type: Option<String>,
    #[serde(rename = "businessClass", skip_serializing_if = "Option::is_none")]
    pub business_class: Option<String>,
    #[serde(
        rename = "companyVerificationId",
        skip_serializing_if = "Option::is_none"
    )]
    pub company_verification_id: Option<String>,
}

impl UpdatePlatformPartnerBodyTypeBusiness {
    pub fn new() -> UpdatePlatformPartnerBodyTypeBusiness {
        UpdatePlatformPartnerBodyTypeBusiness {
            company_name: None,
            taxation_type: None,
            business_registration_number: None,
            representative_name: None,
            company_address: None,
            business_type: None,
            business_class: None,
            company_verification_id: None,
        }
    }
}
