/*
 * PortOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.16.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::domain::models;
use serde::{Deserialize, Serialize};

/// VerifiedIdentityVerification : 완료된 본인인증 내역
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifiedIdentityVerification {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Box<models::SelectedChannel>>,
    #[serde(rename = "verifiedCustomer")]
    pub verified_customer: Box<models::IdentityVerificationVerifiedCustomer>,
    #[serde(rename = "customData", skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<String>,
    #[serde(rename = "requestedAt")]
    pub requested_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "statusChangedAt")]
    pub status_changed_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "verifiedAt")]
    pub verified_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "pgTxId")]
    pub pg_tx_id: String,
    #[serde(rename = "pgRawResponse")]
    pub pg_raw_response: String,
    #[serde(rename = "version")]
    pub version: models::PortOneVersion,
}

impl VerifiedIdentityVerification {
    /// 완료된 본인인증 내역
    pub fn new(
        status: String,
        id: String,
        verified_customer: models::IdentityVerificationVerifiedCustomer,
        requested_at: chrono::DateTime<chrono::FixedOffset>,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        status_changed_at: chrono::DateTime<chrono::FixedOffset>,
        verified_at: chrono::DateTime<chrono::FixedOffset>,
        pg_tx_id: String,
        pg_raw_response: String,
        version: models::PortOneVersion,
    ) -> VerifiedIdentityVerification {
        VerifiedIdentityVerification {
            status,
            id,
            channel: None,
            verified_customer: Box::new(verified_customer),
            custom_data: None,
            requested_at,
            updated_at,
            status_changed_at,
            verified_at,
            pg_tx_id,
            pg_raw_response,
            version,
        }
    }
}
